// Package runtimegen combines locked registry and inventory data.
package runtimegen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"go/format"
	"slices"
	"sort"

	"github.com/bedrock-mc/protocolgen/data/source"
)

// RegistryEntry matches protocolgen's required_item_list.json format.
type RegistryEntry struct {
	RuntimeID      int32 `json:"runtime_id"`
	ComponentBased bool  `json:"component_based"`
	Version        int32 `json:"version"`
}

// Properties contains the inventory fields needed from a vanilla item extract.
type Properties struct {
	MaxStackSize int      `json:"maxStackSize"`
	Tags         []string `json:"tags"`
}

// Corrections fills known omissions in the locked extraction. A correction
// becomes an error when its source gains the field or its item leaves the registry.
type Corrections struct {
	StackSizes map[string]int    `json:"stack_sizes"`
	Offhand    []string          `json:"offhand"`
	Helmets    []string          `json:"helmets"`
	Evidence   map[string]string `json:"evidence"`
}

// FromSources authenticates all inputs and generates the complete runtime catalog.
func FromSources(ctx context.Context, inputs *source.Sources, cache string) ([]byte, error) {
	var registry map[string]RegistryEntry
	var properties map[string]Properties
	var tags map[string][]string
	var corrections Corrections
	for _, input := range []struct {
		name string
		out  any
	}{{"item_registry", &registry}, {"item_properties", &properties}, {"item_tags", &tags}, {"item_corrections", &corrections}} {
		data, err := inputs.Read(ctx, input.name, cache)
		if err != nil {
			return nil, err
		}
		if err := json.Unmarshal(data, input.out); err != nil {
			return nil, fmt.Errorf("decode %s: %w", input.name, err)
		}
	}
	return Generate(registry, properties, tags, corrections)
}

// Generate emits one deterministic inventory catalog without importing consumers.
func Generate(registry map[string]RegistryEntry, properties map[string]Properties, tags map[string][]string, corrections Corrections) ([]byte, error) {
	if len(registry) == 0 {
		return nil, fmt.Errorf("item registry is empty")
	}
	for _, required := range []string{"minecraft:allow_offhand", "minecraft:head"} {
		if len(tags[required]) == 0 {
			return nil, fmt.Errorf("required item tag %q is missing or empty", required)
		}
	}
	if len(corrections.Evidence) == 0 && (len(corrections.StackSizes)+len(corrections.Offhand)+len(corrections.Helmets) > 0) {
		return nil, fmt.Errorf("item corrections need evidence")
	}
	for name, size := range corrections.StackSizes {
		if _, ok := registry[name]; !ok {
			return nil, fmt.Errorf("stack correction references unknown item %s", name)
		}
		if properties[name].MaxStackSize > 0 {
			return nil, fmt.Errorf("stack correction for %s is stale: source now supplies a value", name)
		}
		if size < 1 || size > 64 {
			return nil, fmt.Errorf("stack correction for %s has invalid count %d", name, size)
		}
	}
	offhand, err := correctedTag(registry, tags["minecraft:allow_offhand"], corrections.Offhand)
	if err != nil {
		return nil, err
	}
	helmet, err := correctedTag(registry, tags["minecraft:head"], corrections.Helmets)
	if err != nil {
		return nil, err
	}
	names := make([]string, 0, len(registry))
	for name := range registry {
		names = append(names, name)
	}
	sort.Strings(names)
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by data/cmd/runtimegen; DO NOT EDIT.\n\npackage item\n\nvar runtimeItems = []Runtime{")
	ids := make(map[int32]string)
	for _, name := range names {
		entry, props := registry[name], properties[name]
		if previous, ok := ids[entry.RuntimeID]; ok {
			return nil, fmt.Errorf("items %s and %s share runtime ID %d", previous, name, entry.RuntimeID)
		}
		ids[entry.RuntimeID] = name
		count := props.MaxStackSize
		if count <= 0 {
			count = corrections.StackSizes[name]
		}
		if count < 1 || count > 64 {
			return nil, fmt.Errorf("item %s has missing or invalid stack size %d", name, count)
		}
		body := slices.Contains(props.Tags, "minecraft:horse_armor") || slices.Contains(props.Tags, "minecraft:nautilus_armor") || slices.Contains(props.Tags, "minecraft:harness")
		fmt.Fprintf(&output, "{Name:%q, RuntimeID:%d, ComponentBased:%t, Version:%d, MaxCount:%d, BodyWearable:%t, AllowOffHand:%t, ArmourSlot:0, ArmourWearable:%t},\n", name, entry.RuntimeID, entry.ComponentBased, entry.Version, count, body, offhand[name], helmet[name])
	}
	fmt.Fprintln(&output, "}")
	return format.Source(output.Bytes())
}

// correctedTag applies missing-membership corrections and rejects stale entries.
func correctedTag(registry map[string]RegistryEntry, members, corrections []string) (map[string]bool, error) {
	result := make(map[string]bool, len(members)+len(corrections))
	for _, name := range members {
		result[name] = true
	}
	for _, name := range corrections {
		if _, ok := registry[name]; !ok {
			return nil, fmt.Errorf("tag correction references unknown item %s", name)
		}
		if result[name] {
			return nil, fmt.Errorf("tag correction for %s is stale or duplicated", name)
		}
		result[name] = true
	}
	return result, nil
}
