// Package registrygen projects authenticated vanilla registries into consumer NBT payloads.
package registrygen

import (
	"bytes"
	"compress/gzip"
	"context"
	"fmt"
	"go/format"
	"io"
	"math"
	"sort"

	"github.com/bedrock-mc/protocolgen/data/internal/runtimegen"
	"github.com/bedrock-mc/protocolgen/data/source"
	"github.com/sandertv/gophertunnel/minecraft/nbt"
)

// GeneratedMarker identifies the registry projection's generated files.
const GeneratedMarker = "// Code generated by data/cmd/registrygen; DO NOT EDIT."

// Inputs contains the four public Cloudburst inputs in their original encodings.
type Inputs struct {
	BlockPalette, DataDrivenBlocks, ItemRegistry, ItemComponents []byte
}

// blockState is the consumer's versioned palette record; source-only indexes are omitted.
type blockState struct {
	Name    string         `nbt:"name"`
	States  map[string]any `nbt:"states"`
	Version int32          `nbt:"version"`
}

// rawBlockState includes every field in the source palette so unknown additions fail decoding.
type rawBlockState struct {
	Name      string         `nbt:"name"`
	States    map[string]any `nbt:"states"`
	Version   int32          `nbt:"version"`
	BlockID   int32          `nbt:"block_id"`
	NameHash  int64          `nbt:"name_hash"`
	NetworkID int32          `nbt:"network_id"`
}

// dataDrivenBlock preserves one complete component compound under its block name.
type dataDrivenBlock struct {
	Name       string         `nbt:"name"`
	Components map[string]any `nbt:"components"`
}

// itemEntry joins registry identity with the item's complete component compound.
type itemEntry struct {
	RuntimeID      int32          `nbt:"runtime_id"`
	ComponentBased bool           `nbt:"component_based"`
	Version        int32          `nbt:"version"`
	Data           map[string]any `nbt:"data"`
}

// FromSources reads all registry inputs through the authenticated source loader.
func FromSources(ctx context.Context, sources *source.Sources, cache string) (map[string][]byte, error) {
	var input Inputs
	for _, field := range []struct {
		name string
		out  *[]byte
	}{
		{"block_palette", &input.BlockPalette},
		{"data_driven_blocks", &input.DataDrivenBlocks},
		{"item_registry", &input.ItemRegistry},
		{"item_components", &input.ItemComponents},
	} {
		data, err := sources.Read(ctx, field.name, cache)
		if err != nil {
			return nil, err
		}
		*field.out = data
	}
	digest, err := sources.Lock.SHA256()
	if err != nil {
		return nil, err
	}
	return Generate(input, digest)
}

// Generate validates and normalizes registries while preserving list order and NBT value types.
func Generate(input Inputs, sourceLockSHA256 string) (map[string][]byte, error) {
	var palette struct {
		Blocks []rawBlockState `nbt:"blocks"`
	}
	if err := decodeSource(input.BlockPalette, &palette); err != nil {
		return nil, fmt.Errorf("block palette: %w", err)
	}
	if len(palette.Blocks) == 0 {
		return nil, fmt.Errorf("block palette is empty")
	}
	var states bytes.Buffer
	stateEncoder := nbt.NewEncoder(&states)
	stateEncoder.SortMaps = true
	blockNames := make(map[string]bool)
	stateHashes := make(map[int32]bool)
	stateIdentities := make(map[string]bool)
	for _, raw := range palette.Blocks {
		if raw.Name == "" || raw.States == nil || raw.Version <= 0 {
			return nil, fmt.Errorf("block %q has incomplete state fields", raw.Name)
		}
		if stateHashes[raw.NetworkID] {
			return nil, fmt.Errorf("duplicate block network hash %d", raw.NetworkID)
		}
		stateHashes[raw.NetworkID] = true
		for name, value := range raw.States {
			switch value.(type) {
			case string, uint8, int32:
			default:
				return nil, fmt.Errorf("block %s property %s has unsupported type %T", raw.Name, name, value)
			}
		}
		state := blockState{raw.Name, raw.States, raw.Version}
		identity, err := encodeNBT(blockState{raw.Name, raw.States, 0}, nbt.NetworkLittleEndian)
		if err != nil {
			return nil, err
		}
		if stateIdentities[string(identity)] {
			return nil, fmt.Errorf("duplicate block state %s", raw.Name)
		}
		stateIdentities[string(identity)] = true
		if err := stateEncoder.Encode(state); err != nil {
			return nil, err
		}
		blockNames[raw.Name] = true
	}

	var driven map[string]map[string]any
	if err := decodeSource(input.DataDrivenBlocks, &driven); err != nil {
		return nil, fmt.Errorf("data-driven blocks: %w", err)
	}
	names := sortedNames(driven)
	blocks := make([]dataDrivenBlock, 0, len(names))
	for _, name := range names {
		if !blockNames[name] || driven[name] == nil {
			return nil, fmt.Errorf("data-driven block %q has no palette state or component compound", name)
		}
		blocks = append(blocks, dataDrivenBlock{name, driven[name]})
	}
	drivenNBT, err := encodeNBT(struct {
		Blocks []dataDrivenBlock `nbt:"blocks"`
	}{blocks}, nbt.LittleEndian)
	if err != nil {
		return nil, err
	}

	registry, err := runtimegen.DecodeRegistry(input.ItemRegistry)
	if err != nil {
		return nil, fmt.Errorf("item registry: %w", err)
	}
	if len(registry) == 0 {
		return nil, fmt.Errorf("item registry is empty")
	}
	var components map[string]map[string]any
	if err := decodeSource(input.ItemComponents, &components); err != nil {
		return nil, fmt.Errorf("item components: %w", err)
	}
	if len(components) != len(registry) {
		return nil, fmt.Errorf("item component count %d does not match registry count %d", len(components), len(registry))
	}
	items := make(map[string]itemEntry, len(registry))
	ids := make(map[int32]string, len(registry))
	for _, name := range sortedNames(registry) {
		entry := registry[name]
		data, exists := components[name]
		if !exists || data == nil {
			return nil, fmt.Errorf("item %s has no component compound", name)
		}
		if entry.RuntimeID < math.MinInt16 || entry.RuntimeID > math.MaxInt16 || entry.Version < 0 {
			return nil, fmt.Errorf("item %s has invalid runtime ID or version", name)
		}
		if other, exists := ids[entry.RuntimeID]; exists {
			return nil, fmt.Errorf("items %s and %s share runtime ID %d", other, name, entry.RuntimeID)
		}
		ids[entry.RuntimeID] = name
		items[name] = itemEntry{entry.RuntimeID, entry.ComponentBased, entry.Version, data}
	}
	itemsNBT, err := encodeNBT(items, nbt.NetworkLittleEndian)
	if err != nil {
		return nil, err
	}
	metadata, err := format.Source(fmt.Appendf(nil, `%s

package registry

import _ "embed"

// SourceLockSHA256 identifies the authenticated inputs used for these payloads.
const SourceLockSHA256 = %q

// BlockStateCount is the number of versioned states in BlockStatesNBT.
const BlockStateCount = %d

// DataDrivenBlockCount is the number of component definitions in DataDrivenBlocksNBT.
const DataDrivenBlockCount = %d

// ItemCount is the number of entries in ItemsNBT.
const ItemCount = %d

//go:embed block_states.nbt
var blockStates []byte

//go:embed data_driven_blocks.nbt
var dataDrivenBlocks []byte

//go:embed items.nbt
var items []byte
`, GeneratedMarker, sourceLockSHA256, len(palette.Blocks), len(blocks), len(items)))
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		"registry/block_states.nbt":       states.Bytes(),
		"registry/data_driven_blocks.nbt": drivenNBT,
		"registry/items.nbt":              itemsNBT,
		"registry/payloads_generated.go":  metadata,
	}, nil
}

// decodeSource reads exactly one gzip-compressed, big-endian Cloudburst compound.
func decodeSource(data []byte, out any) error {
	reader, err := gzip.NewReader(bytes.NewReader(data))
	if err != nil {
		return err
	}
	defer reader.Close()
	const maximum = 64 << 20
	uncompressed, err := io.ReadAll(io.LimitReader(reader, maximum+1))
	if err != nil {
		return err
	}
	if len(uncompressed) > maximum {
		return fmt.Errorf("registry exceeds %d bytes", maximum)
	}
	buffer := bytes.NewBuffer(uncompressed)
	if err := nbt.NewDecoderWithEncoding(buffer, nbt.BigEndian).Decode(out); err != nil {
		return err
	}
	if buffer.Len() != 0 {
		return fmt.Errorf("registry has trailing NBT data")
	}
	return nil
}

// encodeNBT writes map keys in a stable order without changing list order or tag types.
func encodeNBT(value any, encoding nbt.Encoding) ([]byte, error) {
	var output bytes.Buffer
	encoder := nbt.NewEncoderWithEncoding(&output, encoding)
	encoder.SortMaps = true
	if err := encoder.Encode(value); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

// sortedNames returns a compound's names in lexical order.
func sortedNames[T any](values map[string]T) []string {
	names := make([]string, 0, len(values))
	for name := range values {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
