use std::fs::{self, File};
use std::io::{BufReader, Write};
use std::path::Path;

mod generator;
mod ir;
mod parser;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let root = Path::new(&manifest_dir); 
    // output to ../valentine/src/bedrock
    let output_dir = root.parent().unwrap().join("valentine").join("src").join("bedrock");
    
    if !output_dir.exists() {
        fs::create_dir_all(&output_dir)?;
    }

    let data_paths = root.join("minecraft-data/data/dataPaths.json");
    let file = File::open(&data_paths)?;
    let reader = BufReader::new(file);
    let paths: serde_json::Value = serde_json::from_reader(reader)?;

    let bedrock = paths
        .get("bedrock")
        .and_then(|v| v.as_object())
        .ok_or("Missing bedrock section")?;

    let mut generated_modules = Vec::new();
    let mut versions: Vec<_> = bedrock.keys().collect();
    versions.sort(); // String sort

    for version in versions {
        let version_data = bedrock.get(version).unwrap();
        
        let protocol_path_str = version_data
            .get("protocol")
            .and_then(|v| v.as_str());

        if let Some(p) = protocol_path_str {
             let protocol_dir = root.join("minecraft-data/data").join(p);
             let protocol_file = protocol_dir.join("protocol.json");

             if !protocol_file.exists() {
                continue;
             }
             
             println!("Generating Bedrock {}...", version);
             
             match parser::parse(&protocol_file) {
                 Ok(parse_result) => {
                     if let Err(e) = generator::generate(version, &parse_result, &output_dir) {
                         eprintln!("  Error generating {}: {}", version, e);
                     } else {
                         generated_modules.push(version.to_string());
                     }
                 }
                 Err(e) => {
                     eprintln!("  Error parsing {}: {}", version, e);
                 }
             }
        }
    }

    // Generate mod.rs
    let mod_rs_path = output_dir.join("mod.rs");
    let mut mod_file = File::create(mod_rs_path)?;
    writeln!(mod_file, "// Generated by valentine_gen")?;
    
    for version in generated_modules {
        let mod_name = format!("v{}", version.replace(".", "_"));
        let feature_name = format!("bedrock_{}", version.replace(".", "_"));
        
        writeln!(mod_file, "#[cfg(feature = \"{}\")]", feature_name)?;
        writeln!(mod_file, "pub mod {};", mod_name)?;
    }

    Ok(())
}
