package generator

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

const generatedMarker = "// Code generated by data/cmd/generate; DO NOT EDIT."

// Config identifies the source directories and versions used for generation.
type Config struct {
	CloudburstDir   string
	BDSDir          string
	CloudburstRef   string
	BDSVersion      string
	BlockShapesPath string
	BlockShapesRef  string
}

// Stats reports the number of records generated from each source.
type Stats struct {
	BlockStates int `json:"block_states"`
	Biomes      int `json:"biomes"`
	VoxelShapes int `json:"voxel_shapes"`
	Entities    int `json:"entities"`
	Foods       int `json:"foods"`
}

// Generate loads the configured sources and returns deterministic repository-
// relative files. It does not write to disk.
func Generate(cfg Config) (map[string][]byte, Stats, error) {
	if cfg.CloudburstDir == "" || cfg.BDSDir == "" {
		return nil, Stats{}, errors.New("cloudburst and BDS directories are required")
	}
	files := make(map[string][]byte)
	var stats Stats

	blockFiles, count, err := generateBlocks(filepath.Join(cfg.CloudburstDir, "block_properties.json"), cfg.BlockShapesPath)
	if err != nil {
		return nil, stats, fmt.Errorf("generate blocks: %w", err)
	}
	if err := mergeFiles(files, blockFiles); err != nil {
		return nil, stats, err
	}
	stats.BlockStates = count

	biomeFiles, count, err := generateBiomes(filepath.Join(cfg.CloudburstDir, "stripped_biome_definitions.json"))
	if err != nil {
		return nil, stats, fmt.Errorf("generate biomes: %w", err)
	}
	if err := mergeFiles(files, biomeFiles); err != nil {
		return nil, stats, err
	}
	stats.Biomes = count

	shapeFiles, count, err := generateVoxelShapes(filepath.Join(
		cfg.BDSDir, "behavior_packs", "experimental_vanilla_shapes", "shapes",
	))
	if err != nil {
		return nil, stats, fmt.Errorf("generate voxel shapes: %w", err)
	}
	if err := mergeFiles(files, shapeFiles); err != nil {
		return nil, stats, err
	}
	stats.VoxelShapes = count

	entityFiles, count, err := generateEntities(filepath.Join(
		cfg.BDSDir, "behavior_packs", "vanilla", "entities",
	))
	if err != nil {
		return nil, stats, fmt.Errorf("generate entities: %w", err)
	}
	if err := mergeFiles(files, entityFiles); err != nil {
		return nil, stats, err
	}
	stats.Entities = count

	foodFiles, count, err := generateFoods(filepath.Join(
		cfg.BDSDir, "behavior_packs", "vanilla", "items",
	))
	if err != nil {
		return nil, stats, fmt.Errorf("generate foods: %w", err)
	}
	if err := mergeFiles(files, foodFiles); err != nil {
		return nil, stats, err
	}
	stats.Foods = count

	version, err := formattedGo("version_generated.go", fmt.Sprintf(`%s

package data

const (
	SchemaVersion = 1
	CloudburstRef = %q
	BDSVersion = %q
	BlockShapesRef = %q
)

var GeneratedCounts = Counts{
	BlockStates: %d,
	Biomes: %d,
	VoxelShapes: %d,
	Entities: %d,
	Foods: %d,
}
`, generatedMarker, cfg.CloudburstRef, cfg.BDSVersion, cfg.BlockShapesRef, stats.BlockStates, stats.Biomes, stats.VoxelShapes, stats.Entities, stats.Foods))
	if err != nil {
		return nil, stats, err
	}
	files["version_generated.go"] = version

	manifest, err := json.MarshalIndent(struct {
		SchemaVersion  int    `json:"schema_version"`
		CloudburstRef  string `json:"cloudburst_ref"`
		BDSVersion     string `json:"bds_version"`
		BlockShapesRef string `json:"block_shapes_ref,omitempty"`
		Counts         Stats  `json:"counts"`
	}{
		SchemaVersion:  1,
		CloudburstRef:  cfg.CloudburstRef,
		BDSVersion:     cfg.BDSVersion,
		BlockShapesRef: cfg.BlockShapesRef,
		Counts:         stats,
	}, "", "  ")
	if err != nil {
		return nil, stats, err
	}
	files["semantic_sources.json"] = append(manifest, '\n')
	return files, stats, nil
}

type rawBlockState struct {
	Name                        string          `json:"name"`
	Hash                        uint32          `json:"blockStateHash"`
	TranslationKey              string          `json:"translationKey"`
	Solid                       bool            `json:"isSolid"`
	Hardness                    float32         `json:"hardness"`
	ExplosionResistance         float32         `json:"explosionResistance"`
	Friction                    float32         `json:"friction"`
	Thickness                   float32         `json:"thickness"`
	RequiresCorrectToolForDrops bool            `json:"requiresCorrectToolForDrops"`
	Translucency                float32         `json:"translucency"`
	MapColor                    string          `json:"mapColor"`
	TintMethod                  string          `json:"tintMethod"`
	LightEmission               uint8           `json:"lightEmission"`
	LightDampening              uint8           `json:"lightDampening"`
	BurnOdds                    uint8           `json:"burnOdds"`
	FlameOdds                   uint8           `json:"flameOdds"`
	CanContainLiquidSource      bool            `json:"canContainLiquidSource"`
	LiquidReactionOnTouch       string          `json:"liquidReactionOnTouch"`
	CollisionShape              json.RawMessage `json:"collisionShape"`
	OutlineShape                json.RawMessage `json:"outlineShape"`
	VisualShape                 json.RawMessage `json:"visualShape"`
	UIShape                     json.RawMessage `json:"uiShape"`
	LiquidClipShape             json.RawMessage `json:"liquidClipShape"`
}

type generatedBox [6]float32

type generatedBlock struct {
	Name           string
	TranslationKey string
}

type generatedProperties struct {
	Hardness                    float32
	ExplosionResistance         float32
	Friction                    float32
	Thickness                   float32
	Translucency                float32
	MapColor                    uint32
	TintMethod                  string
	LiquidReactionOnTouch       string
	LightEmission               uint8
	LightDampening              uint8
	BurnOdds                    uint8
	FlameOdds                   uint8
	CollisionShape              uint16
	OutlineShape                uint16
	VisualShape                 uint16
	UIShape                     uint16
	LiquidClipShape             uint16
	Solid                       bool
	RequiresCorrectToolForDrops bool
	CanContainLiquidSource      bool
}

type generatedState struct {
	Hash       uint32
	Block      uint16
	Properties uint16
}

// generateBlocks normalizes state properties and compacts shared block shapes.
func generateBlocks(path, shapesPath string) (map[string][]byte, int, error) {
	var raw []rawBlockState
	if err := readJSON(path, &raw, false); err != nil {
		return nil, 0, err
	}
	if len(raw) > math.MaxUint16 {
		return nil, 0, fmt.Errorf("state count %d exceeds uint16 lookup capacity", len(raw))
	}
	if shapesPath != "" {
		if err := applyBlockShapes(raw, shapesPath); err != nil {
			return nil, 0, err
		}
	}

	blocks := make([]generatedBlock, 0, 2048)
	blockIndexes := make(map[generatedBlock]uint16)
	properties := make([]generatedProperties, 0, 4096)
	propertyIndexes := make(map[generatedProperties]uint16)
	shapes := make([][]generatedBox, 1)
	shapeIndexes := make(map[string]uint16)
	states := make([]generatedState, 0, len(raw))
	seenHashes := make(map[uint32]struct{}, len(raw))

	internShape := func(message json.RawMessage) (uint16, error) {
		boxes, present, err := decodeShape(message)
		if err != nil {
			return 0, err
		}
		if !present {
			return 0, nil
		}
		key := shapeKey(boxes)
		if index, ok := shapeIndexes[key]; ok {
			return index, nil
		}
		if len(shapes) == math.MaxUint16 {
			return 0, errors.New("shape count exceeds uint16 capacity")
		}
		index := uint16(len(shapes))
		shapeIndexes[key] = index
		shapes = append(shapes, boxes)
		return index, nil
	}

	for sourceIndex, value := range raw {
		if value.Name == "" {
			return nil, 0, fmt.Errorf("state %d has no name", sourceIndex)
		}
		if _, found := seenHashes[value.Hash]; found {
			return nil, 0, fmt.Errorf("duplicate block state hash %d", value.Hash)
		}
		seenHashes[value.Hash] = struct{}{}

		blockValue := generatedBlock{Name: value.Name, TranslationKey: value.TranslationKey}
		blockIndex, ok := blockIndexes[blockValue]
		if !ok {
			if len(blocks) == math.MaxUint16 {
				return nil, 0, errors.New("block count exceeds uint16 capacity")
			}
			blockIndex = uint16(len(blocks))
			blockIndexes[blockValue] = blockIndex
			blocks = append(blocks, blockValue)
		}

		collision, err := internShape(value.CollisionShape)
		if err != nil {
			return nil, 0, fmt.Errorf("%s collision shape: %w", value.Name, err)
		}
		outline, err := internShape(value.OutlineShape)
		if err != nil {
			return nil, 0, fmt.Errorf("%s outline shape: %w", value.Name, err)
		}
		visual, err := internShape(value.VisualShape)
		if err != nil {
			return nil, 0, fmt.Errorf("%s visual shape: %w", value.Name, err)
		}
		ui, err := internShape(value.UIShape)
		if err != nil {
			return nil, 0, fmt.Errorf("%s UI shape: %w", value.Name, err)
		}
		liquidClip, err := internShape(value.LiquidClipShape)
		if err != nil {
			return nil, 0, fmt.Errorf("%s liquid clip shape: %w", value.Name, err)
		}
		mapColor, err := parseRGBA(value.MapColor)
		if err != nil {
			return nil, 0, fmt.Errorf("%s map color: %w", value.Name, err)
		}
		propertyValue := generatedProperties{
			Hardness:                    value.Hardness,
			ExplosionResistance:         value.ExplosionResistance,
			Friction:                    value.Friction,
			Thickness:                   value.Thickness,
			Translucency:                value.Translucency,
			MapColor:                    mapColor,
			TintMethod:                  value.TintMethod,
			LiquidReactionOnTouch:       value.LiquidReactionOnTouch,
			LightEmission:               value.LightEmission,
			LightDampening:              value.LightDampening,
			BurnOdds:                    value.BurnOdds,
			FlameOdds:                   value.FlameOdds,
			CollisionShape:              collision,
			OutlineShape:                outline,
			VisualShape:                 visual,
			UIShape:                     ui,
			LiquidClipShape:             liquidClip,
			Solid:                       value.Solid,
			RequiresCorrectToolForDrops: value.RequiresCorrectToolForDrops,
			CanContainLiquidSource:      value.CanContainLiquidSource,
		}
		propertyIndex, ok := propertyIndexes[propertyValue]
		if !ok {
			if len(properties) == math.MaxUint16 {
				return nil, 0, errors.New("property count exceeds uint16 capacity")
			}
			propertyIndex = uint16(len(properties))
			propertyIndexes[propertyValue] = propertyIndex
			properties = append(properties, propertyValue)
		}
		states = append(states, generatedState{
			Hash: value.Hash, Block: blockIndex, Properties: propertyIndex,
		})
	}

	hashIndex := make([]uint16, len(states))
	for index := range states {
		hashIndex[index] = uint16(index)
	}
	sort.Slice(hashIndex, func(i, j int) bool {
		return states[hashIndex[i]].Hash < states[hashIndex[j]].Hash
	})

	blockNames := make([]string, len(blocks))
	for index, value := range blocks {
		blockNames[index] = value.Name
	}
	identifiers, err := exportedIdentifiers(blockNames)
	if err != nil {
		return nil, 0, err
	}
	fileNames, err := generatedFileNames(blockNames)
	if err != nil {
		return nil, 0, err
	}
	stateIndexesByBlock := make([][]int, len(blocks))
	for stateIndex, state := range states {
		stateIndexesByBlock[state.Block] = append(stateIndexesByBlock[state.Block], stateIndex)
	}

	files := make(map[string][]byte, len(blocks)+1)
	for blockIndex, value := range blocks {
		identifier := identifiers[value.Name]
		stateVariable := unexportedIdentifier(identifier) + "States"
		var output bytes.Buffer
		fmt.Fprintf(&output, `// %s is the generated definition for %s.
var %s = Block{
	Name: %q,
	TranslationKey: %q,
}

var %s = [...]State{
`, identifier, value.Name, identifier, value.Name, value.TranslationKey, stateVariable)
		for _, stateIndex := range stateIndexesByBlock[blockIndex] {
			state := states[stateIndex]
			fmt.Fprintf(&output, "{Hash: %d, Block: %d, Properties: %d},\n",
				state.Hash, state.Block, state.Properties)
		}
		output.WriteString("}\n")
		fileName := "block/" + fileNames[value.Name]
		formatted, err := formattedGo(fileName, generatedSource("block", output.String()))
		if err != nil {
			return nil, 0, err
		}
		files[fileName] = formatted
	}

	var output bytes.Buffer
	output.WriteString("var blocks = [...]Block{\n")
	for _, value := range blocks {
		fmt.Fprintf(&output, "%s,\n", identifiers[value.Name])
	}
	output.WriteString("}\n\nvar shapes = [...][]Box{\n")
	for _, shape := range shapes {
		if shape == nil {
			output.WriteString("nil,\n")
			continue
		}
		output.WriteString("{")
		for _, box := range shape {
			fmt.Fprintf(&output, "{%s, %s, %s, %s, %s, %s},",
				goFloat(box[0]), goFloat(box[1]), goFloat(box[2]),
				goFloat(box[3]), goFloat(box[4]), goFloat(box[5]))
		}
		output.WriteString("},\n")
	}
	output.WriteString("}\n\nvar properties = [...]Properties{\n")
	for _, value := range properties {
		fmt.Fprintf(&output, `{Hardness:%s, ExplosionResistance:%s, Friction:%s, Thickness:%s, Translucency:%s, MapColor:0x%08x, TintMethod:%q, LiquidReactionOnTouch:%q, LightEmission:%d, LightDampening:%d, BurnOdds:%d, FlameOdds:%d, CollisionShape:%d, OutlineShape:%d, VisualShape:%d, UIShape:%d, LiquidClipShape:%d, Solid:%t, RequiresCorrectToolForDrops:%t, CanContainLiquidSource:%t},
`,
			goFloat(value.Hardness), goFloat(value.ExplosionResistance), goFloat(value.Friction),
			goFloat(value.Thickness), goFloat(value.Translucency), value.MapColor, value.TintMethod,
			value.LiquidReactionOnTouch, value.LightEmission, value.LightDampening, value.BurnOdds,
			value.FlameOdds, value.CollisionShape, value.OutlineShape, value.VisualShape, value.UIShape,
			value.LiquidClipShape, value.Solid, value.RequiresCorrectToolForDrops, value.CanContainLiquidSource)
	}
	output.WriteString("}\n\nvar states = [...]State{\n")
	stateOffsets := make([]int, len(blocks))
	for _, value := range states {
		identifier := identifiers[blocks[value.Block].Name]
		fmt.Fprintf(&output, "%sStates[%d],\n", unexportedIdentifier(identifier), stateOffsets[value.Block])
		stateOffsets[value.Block]++
	}
	output.WriteString("}\n\nvar stateHashIndex = [...]uint16{\n")
	for _, value := range hashIndex {
		fmt.Fprintf(&output, "%d,\n", value)
	}
	output.WriteString("}\n")
	const indexName = "block/index_generated.go"
	formatted, err := formattedGo(indexName, generatedSource("block", output.String()))
	if err != nil {
		return nil, 0, err
	}
	files[indexName] = formatted
	return files, len(states), nil
}

type rawBiome struct {
	ID               *int32  `json:"id"`
	Temperature      float32 `json:"temperature"`
	Downfall         float32 `json:"downfall"`
	RedSporeDensity  float32 `json:"redSporeDensity"`
	BlueSporeDensity float32 `json:"blueSporeDensity"`
	AshDensity       float32 `json:"ashDensity"`
	WhiteAshDensity  float32 `json:"whiteAshDensity"`
	FoliageSnow      float32 `json:"foliageSnow"`
	Depth            float32 `json:"depth"`
	Scale            float32 `json:"scale"`
	MapWaterColor    struct {
		A uint8 `json:"a"`
		R uint8 `json:"r"`
		G uint8 `json:"g"`
		B uint8 `json:"b"`
	} `json:"mapWaterColor"`
	Rain bool     `json:"rain"`
	Tags []string `json:"tags"`
}

// generateBiomes emits named biome values and their lookup index.
func generateBiomes(path string) (map[string][]byte, int, error) {
	var raw map[string]rawBiome
	if err := readJSON(path, &raw, false); err != nil {
		return nil, 0, err
	}
	names := sortedKeys(raw)
	identifiers, err := exportedIdentifiers(names)
	if err != nil {
		return nil, 0, err
	}
	fileNames, err := generatedFileNames(names)
	if err != nil {
		return nil, 0, err
	}
	files := make(map[string][]byte, len(names)+1)
	for _, name := range names {
		value := raw[name]
		sort.Strings(value.Tags)
		id, hasID := int32(0), value.ID != nil
		if hasID {
			id = *value.ID
		}
		color := uint32(value.MapWaterColor.R)<<24 | uint32(value.MapWaterColor.G)<<16 |
			uint32(value.MapWaterColor.B)<<8 | uint32(value.MapWaterColor.A)
		var output bytes.Buffer
		fmt.Fprintf(&output, `// %s is the generated definition for %s.
var %s = Biome{
	Name: %q,
	ID: %d,
	HasID: %t,
	Temperature: %s,
	Downfall: %s,
	Depth: %s,
	Scale: %s,
	RedSporeDensity: %s,
	BlueSporeDensity: %s,
	AshDensity: %s,
	WhiteAshDensity: %s,
	FoliageSnow: %s,
	MapWaterColorRGBA: 0x%08x,
	Rain: %t,
	Tags: %s,
}

`, identifiers[name], name, identifiers[name], name, id, hasID, goFloat(value.Temperature), goFloat(value.Downfall), goFloat(value.Depth),
			goFloat(value.Scale), goFloat(value.RedSporeDensity), goFloat(value.BlueSporeDensity),
			goFloat(value.AshDensity), goFloat(value.WhiteAshDensity), goFloat(value.FoliageSnow),
			color, value.Rain, goStrings(value.Tags))
		fileName := "biome/" + fileNames[name]
		formatted, err := formattedGo(fileName, generatedSource("biome", output.String()))
		if err != nil {
			return nil, 0, err
		}
		files[fileName] = formatted
	}
	var output bytes.Buffer
	output.WriteString("var all = []Biome{\n")
	for _, name := range names {
		fmt.Fprintf(&output, "%s,\n", identifiers[name])
	}
	output.WriteString("}\n")
	const indexName = "biome/index_generated.go"
	formatted, err := formattedGo(indexName, generatedSource("biome", output.String()))
	if err != nil {
		return nil, 0, err
	}
	files[indexName] = formatted
	return files, len(raw), nil
}

type rawVoxelShape struct {
	VoxelShape struct {
		Description struct {
			Identifier string `json:"identifier"`
		} `json:"description"`
		Shape struct {
			Boxes []struct {
				Min [3]float32 `json:"min"`
				Max [3]float32 `json:"max"`
			} `json:"boxes"`
		} `json:"shape"`
	} `json:"minecraft:voxel_shape"`
}

type generatedVoxelShape struct {
	Name  string
	Boxes []generatedBox
}

// generateVoxelShapes converts named shape coordinates into block-local units.
func generateVoxelShapes(dir string) (map[string][]byte, int, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return nil, 0, err
	}
	if len(paths) == 0 {
		return nil, 0, fmt.Errorf("no shape files found in %s", dir)
	}
	values := make([]generatedVoxelShape, 0, len(paths))
	for _, path := range paths {
		var raw rawVoxelShape
		if err := readJSON(path, &raw, true); err != nil {
			return nil, 0, err
		}
		name := raw.VoxelShape.Description.Identifier
		if name == "" {
			return nil, 0, fmt.Errorf("%s has no voxel shape identifier", path)
		}
		value := generatedVoxelShape{Name: name, Boxes: make([]generatedBox, 0, len(raw.VoxelShape.Shape.Boxes))}
		for _, box := range raw.VoxelShape.Shape.Boxes {
			generated := generatedBox{
				box.Min[0] / 16, box.Min[1] / 16, box.Min[2] / 16,
				box.Max[0] / 16, box.Max[1] / 16, box.Max[2] / 16,
			}
			if err := validateBox(generated); err != nil {
				return nil, 0, fmt.Errorf("%s: %w", name, err)
			}
			value.Boxes = append(value.Boxes, generated)
		}
		values = append(values, value)
	}
	sort.Slice(values, func(i, j int) bool { return values[i].Name < values[j].Name })
	for index := 1; index < len(values); index++ {
		if values[index-1].Name == values[index].Name {
			return nil, 0, fmt.Errorf("duplicate voxel shape %s", values[index].Name)
		}
	}
	names := make([]string, len(values))
	for index, value := range values {
		names[index] = value.Name
	}
	identifiers, err := exportedIdentifiers(names)
	if err != nil {
		return nil, 0, err
	}
	fileNames, err := generatedFileNames(names)
	if err != nil {
		return nil, 0, err
	}

	files := make(map[string][]byte, len(values)+1)
	for _, value := range values {
		var output bytes.Buffer
		fmt.Fprintf(&output, "// %s is the generated definition for %s.\nvar %s = Shape{\nName: %q,\nBoxes: []Box{\n",
			identifiers[value.Name], value.Name, identifiers[value.Name], value.Name)
		for _, box := range value.Boxes {
			fmt.Fprintf(&output, "{%s, %s, %s, %s, %s, %s},\n",
				goFloat(box[0]), goFloat(box[1]), goFloat(box[2]),
				goFloat(box[3]), goFloat(box[4]), goFloat(box[5]))
		}
		output.WriteString("},\n}\n\n")
		fileName := "voxelshape/" + fileNames[value.Name]
		formatted, err := formattedGo(fileName, generatedSource("voxelshape", output.String()))
		if err != nil {
			return nil, 0, err
		}
		files[fileName] = formatted
	}
	var output bytes.Buffer
	output.WriteString("var all = []Shape{\n")
	for _, value := range values {
		fmt.Fprintf(&output, "%s,\n", identifiers[value.Name])
	}
	output.WriteString("}\n")
	const indexName = "voxelshape/index_generated.go"
	formatted, err := formattedGo(indexName, generatedSource("voxelshape", output.String()))
	if err != nil {
		return nil, 0, err
	}
	files[indexName] = formatted
	return files, len(values), nil
}

type rawEntity struct {
	Entity struct {
		Description struct {
			Identifier   string `json:"identifier"`
			Experimental bool   `json:"is_experimental"`
			Summonable   bool   `json:"is_summonable"`
			Spawnable    bool   `json:"is_spawnable"`
			Category     string `json:"spawn_category"`
		} `json:"description"`
		Components map[string]json.RawMessage `json:"components"`
	} `json:"minecraft:entity"`
}

type optionalFloat struct {
	Value   float32
	Present bool
}

type optionalBool struct {
	Value   bool
	Present bool
}

type optionalNumber struct {
	Value   float32
	Min     float32
	Max     float32
	Ranged  bool
	Present bool
}

type generatedEntity struct {
	Name              string
	SpawnCategory     string
	Experimental      bool
	Summonable        bool
	Spawnable         bool
	CollisionWidth    float32
	CollisionHeight   float32
	HasCollision      bool
	HealthInitial     optionalNumber
	HealthMaximum     optionalFloat
	HasHealth         bool
	Movement          optionalNumber
	Scale             optionalNumber
	ProjectileGravity optionalFloat
	ProjectilePower   optionalFloat
	ProjectileBounce  optionalBool
	Pushable          optionalBool
	PushableByPiston  optionalBool
	HasPhysics        bool
	Families          []string
}

// generateEntities emits the supported base components of each entity.
func generateEntities(dir string) (map[string][]byte, int, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return nil, 0, err
	}
	if len(paths) == 0 {
		return nil, 0, fmt.Errorf("no entity files found in %s", dir)
	}
	values := make([]generatedEntity, 0, len(paths))
	for _, path := range paths {
		var raw rawEntity
		if err := readJSON(path, &raw, true); err != nil {
			return nil, 0, err
		}
		if raw.Entity.Description.Identifier == "" {
			return nil, 0, fmt.Errorf("%s has no entity identifier", path)
		}
		components := raw.Entity.Components
		value := generatedEntity{
			Name:          raw.Entity.Description.Identifier,
			SpawnCategory: raw.Entity.Description.Category,
			Experimental:  raw.Entity.Description.Experimental,
			Summonable:    raw.Entity.Description.Summonable,
			Spawnable:     raw.Entity.Description.Spawnable,
		}
		if message, ok := components["minecraft:collision_box"]; ok {
			var component struct {
				Width  float32 `json:"width"`
				Height float32 `json:"height"`
			}
			if err := json.Unmarshal(message, &component); err != nil {
				return nil, 0, fmt.Errorf("%s collision box: %w", value.Name, err)
			}
			value.CollisionWidth, value.CollisionHeight, value.HasCollision =
				component.Width, component.Height, true
		}
		if message, ok := components["minecraft:health"]; ok {
			var component struct {
				Value json.RawMessage `json:"value"`
				Max   json.RawMessage `json:"max"`
			}
			if err := json.Unmarshal(message, &component); err != nil {
				return nil, 0, fmt.Errorf("%s health: %w", value.Name, err)
			}
			value.HealthInitial, err = rawNumberOrRange(component.Value)
			if err != nil {
				return nil, 0, fmt.Errorf("%s health value: %w", value.Name, err)
			}
			if len(component.Max) != 0 {
				maximum, err := rawNumber(component.Max)
				if err != nil {
					return nil, 0, fmt.Errorf("%s maximum health: %w", value.Name, err)
				}
				value.HealthMaximum = optionalFloat{Value: maximum, Present: true}
			}
			value.HasHealth = true
		}
		value.Movement, err = componentNumber(components, "minecraft:movement", "value")
		if err != nil {
			return nil, 0, fmt.Errorf("%s movement: %w", value.Name, err)
		}
		value.Scale, err = componentNumber(components, "minecraft:scale", "value")
		if err != nil {
			return nil, 0, fmt.Errorf("%s scale: %w", value.Name, err)
		}
		if message, ok := components["minecraft:projectile"]; ok {
			var component struct {
				Gravity      *float32 `json:"gravity"`
				Power        *float32 `json:"power"`
				ShouldBounce *bool    `json:"should_bounce"`
			}
			if err := json.Unmarshal(message, &component); err != nil {
				return nil, 0, fmt.Errorf("%s projectile: %w", value.Name, err)
			}
			if component.Gravity != nil {
				value.ProjectileGravity = optionalFloat{Value: *component.Gravity, Present: true}
			}
			if component.Power != nil {
				value.ProjectilePower = optionalFloat{Value: *component.Power, Present: true}
			}
			if component.ShouldBounce != nil {
				value.ProjectileBounce = optionalBool{Value: *component.ShouldBounce, Present: true}
			}
		}
		if message, ok := components["minecraft:pushable"]; ok {
			var component struct {
				Pushable         *bool `json:"is_pushable"`
				PushableByPiston *bool `json:"is_pushable_by_piston"`
			}
			if err := json.Unmarshal(message, &component); err != nil {
				return nil, 0, fmt.Errorf("%s pushable: %w", value.Name, err)
			}
			if component.Pushable != nil {
				value.Pushable = optionalBool{Value: *component.Pushable, Present: true}
			}
			if component.PushableByPiston != nil {
				value.PushableByPiston = optionalBool{Value: *component.PushableByPiston, Present: true}
			}
		}
		_, value.HasPhysics = components["minecraft:physics"]
		if message, ok := components["minecraft:type_family"]; ok {
			var component struct {
				Families []string `json:"family"`
			}
			if err := json.Unmarshal(message, &component); err != nil {
				return nil, 0, fmt.Errorf("%s families: %w", value.Name, err)
			}
			value.Families = component.Families
			sort.Strings(value.Families)
		}
		values = append(values, value)
	}
	sort.Slice(values, func(i, j int) bool { return values[i].Name < values[j].Name })
	for index := 1; index < len(values); index++ {
		if values[index-1].Name == values[index].Name {
			return nil, 0, fmt.Errorf("duplicate entity %s", values[index].Name)
		}
	}
	names := make([]string, len(values))
	for index, value := range values {
		names[index] = value.Name
	}
	identifiers, err := exportedIdentifiers(names)
	if err != nil {
		return nil, 0, err
	}
	fileNames, err := generatedFileNames(names)
	if err != nil {
		return nil, 0, err
	}

	files := make(map[string][]byte, len(values)+1)
	for _, value := range values {
		var output bytes.Buffer
		fmt.Fprintf(&output, `// %s is the generated definition for %s.
var %s = Entity{
	Name: %q,
	SpawnCategory: %q,
	Experimental: %t,
	Summonable: %t,
	Spawnable: %t,
	CollisionBox: CollisionBox{Width: %s, Height: %s, Present: %t},
	Health: Health{
		Initial: Number{Value: %s, Min: %s, Max: %s, Ranged: %t, Present: %t},
		Maximum: Float{Value: %s, Present: %t},
		Present: %t,
	},
	Movement: Number{Value: %s, Min: %s, Max: %s, Ranged: %t, Present: %t},
	Scale: Number{Value: %s, Min: %s, Max: %s, Ranged: %t, Present: %t},
	ProjectileGravity: Float{Value: %s, Present: %t},
	ProjectilePower: Float{Value: %s, Present: %t},
	ProjectileBounce: Bool{Value: %t, Present: %t},
	Pushable: Bool{Value: %t, Present: %t},
	PushableByPiston: Bool{Value: %t, Present: %t},
	HasPhysics: %t,
	Families: %s,
}
`, identifiers[value.Name], value.Name, identifiers[value.Name], value.Name, value.SpawnCategory, value.Experimental, value.Summonable, value.Spawnable,
			goFloat(value.CollisionWidth), goFloat(value.CollisionHeight), value.HasCollision,
			goFloat(value.HealthInitial.Value), goFloat(value.HealthInitial.Min), goFloat(value.HealthInitial.Max),
			value.HealthInitial.Ranged, value.HealthInitial.Present,
			goFloat(value.HealthMaximum.Value), value.HealthMaximum.Present, value.HasHealth,
			goFloat(value.Movement.Value), goFloat(value.Movement.Min), goFloat(value.Movement.Max),
			value.Movement.Ranged, value.Movement.Present,
			goFloat(value.Scale.Value), goFloat(value.Scale.Min), goFloat(value.Scale.Max),
			value.Scale.Ranged, value.Scale.Present,
			goFloat(value.ProjectileGravity.Value), value.ProjectileGravity.Present,
			goFloat(value.ProjectilePower.Value), value.ProjectilePower.Present,
			value.ProjectileBounce.Value, value.ProjectileBounce.Present,
			value.Pushable.Value, value.Pushable.Present,
			value.PushableByPiston.Value, value.PushableByPiston.Present,
			value.HasPhysics, goStrings(value.Families))
		fileName := "entity/" + fileNames[value.Name]
		formatted, err := formattedGo(fileName, generatedSource("entity", output.String()))
		if err != nil {
			return nil, 0, err
		}
		files[fileName] = formatted
	}
	var output bytes.Buffer
	output.WriteString("var all = []Entity{\n")
	for _, value := range values {
		fmt.Fprintf(&output, "%s,\n", identifiers[value.Name])
	}
	output.WriteString("}\n")
	const indexName = "entity/index_generated.go"
	formatted, err := formattedGo(indexName, generatedSource("entity", output.String()))
	if err != nil {
		return nil, 0, err
	}
	files[indexName] = formatted
	return files, len(values), nil
}

type rawItem struct {
	Item struct {
		Description struct {
			Identifier string `json:"identifier"`
		} `json:"description"`
		Components map[string]json.RawMessage `json:"components"`
	} `json:"minecraft:item"`
}

type generatedEffect struct {
	Name      string  `json:"name"`
	Chance    float32 `json:"chance"`
	Duration  float32 `json:"duration"`
	Amplifier int32   `json:"amplifier"`
}

type rawFood struct {
	Nutrition          int32             `json:"nutrition"`
	SaturationModifier string            `json:"saturation_modifier"`
	CanAlwaysEat       bool              `json:"can_always_eat"`
	UsingConvertsTo    json.RawMessage   `json:"using_converts_to"`
	Effects            []generatedEffect `json:"effects"`
}

type generatedFood struct {
	Name               string
	Nutrition          int32
	SaturationModifier string
	UseDuration        float32
	CanAlwaysEat       bool
	UsingConvertsTo    string
	Effects            []generatedEffect
}

// generateFoods emits food properties while skipping non-food item definitions.
func generateFoods(dir string) (map[string][]byte, int, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return nil, 0, err
	}
	if len(paths) == 0 {
		return nil, 0, fmt.Errorf("no item files found in %s", dir)
	}
	values := make([]generatedFood, 0, len(paths))
	for _, path := range paths {
		var raw rawItem
		if err := readJSON(path, &raw, true); err != nil {
			return nil, 0, err
		}
		foodMessage, ok := raw.Item.Components["minecraft:food"]
		if !ok {
			continue
		}
		var food rawFood
		if err := json.Unmarshal(foodMessage, &food); err != nil {
			return nil, 0, fmt.Errorf("%s food: %w", path, err)
		}
		if raw.Item.Description.Identifier == "" {
			return nil, 0, fmt.Errorf("%s has no item identifier", path)
		}
		useDuration, err := rawNumber(raw.Item.Components["minecraft:use_duration"])
		if err != nil {
			return nil, 0, fmt.Errorf("%s use duration: %w", raw.Item.Description.Identifier, err)
		}
		convertsTo, err := rawString(food.UsingConvertsTo)
		if err != nil {
			return nil, 0, fmt.Errorf("%s using_converts_to: %w", raw.Item.Description.Identifier, err)
		}
		values = append(values, generatedFood{
			Name:               raw.Item.Description.Identifier,
			Nutrition:          food.Nutrition,
			SaturationModifier: food.SaturationModifier,
			UseDuration:        useDuration,
			CanAlwaysEat:       food.CanAlwaysEat,
			UsingConvertsTo:    convertsTo,
			Effects:            food.Effects,
		})
	}
	sort.Slice(values, func(i, j int) bool { return values[i].Name < values[j].Name })
	for index := 1; index < len(values); index++ {
		if values[index-1].Name == values[index].Name {
			return nil, 0, fmt.Errorf("duplicate food %s", values[index].Name)
		}
	}
	names := make([]string, len(values))
	for index, value := range values {
		names[index] = value.Name
	}
	identifiers, err := exportedIdentifiers(names)
	if err != nil {
		return nil, 0, err
	}
	fileNames, err := generatedFileNames(names)
	if err != nil {
		return nil, 0, err
	}

	files := make(map[string][]byte, len(values)+1)
	for _, value := range values {
		var output bytes.Buffer
		fmt.Fprintf(&output, `// %s is the generated definition for %s.
var %s = Food{
	Name: %q,
	Nutrition: %d,
	SaturationModifier: %q,
	UseDuration: %s,
	CanAlwaysEat: %t,
	UsingConvertsTo: %q,
	Effects: []Effect{
`, identifiers[value.Name], value.Name, identifiers[value.Name], value.Name, value.Nutrition, value.SaturationModifier, goFloat(value.UseDuration),
			value.CanAlwaysEat, value.UsingConvertsTo)
		for _, effect := range value.Effects {
			fmt.Fprintf(&output, "{Name: %q, Chance: %s, Duration: %s, Amplifier: %d},\n",
				effect.Name, goFloat(effect.Chance), goFloat(effect.Duration), effect.Amplifier)
		}
		output.WriteString("},\n}\n")
		fileName := "item/" + fileNames[value.Name]
		formatted, err := formattedGo(fileName, generatedSource("item", output.String()))
		if err != nil {
			return nil, 0, err
		}
		files[fileName] = formatted
	}
	var output bytes.Buffer
	output.WriteString("var all = []Food{\n")
	for _, value := range values {
		fmt.Fprintf(&output, "%s,\n", identifiers[value.Name])
	}
	output.WriteString("}\n")
	const indexName = "item/index_generated.go"
	formatted, err := formattedGo(indexName, generatedSource("item", output.String()))
	if err != nil {
		return nil, 0, err
	}
	files[indexName] = formatted
	return files, len(values), nil
}

// componentNumber reads an optional scalar or range from a component field.
func componentNumber(components map[string]json.RawMessage, componentName, fieldName string) (optionalNumber, error) {
	message, ok := components[componentName]
	if !ok {
		return optionalNumber{}, nil
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(message, &fields); err != nil {
		return optionalNumber{}, err
	}
	value, ok := fields[fieldName]
	if !ok {
		return optionalNumber{}, nil
	}
	return rawNumberOrRange(value)
}

// rawNumberOrRange decodes an optional fixed value or random range.
// rawNumber decodes a scalar, treating an absent field as zero.
func rawNumberOrRange(message json.RawMessage) (optionalNumber, error) {
	if len(message) == 0 || bytes.Equal(bytes.TrimSpace(message), []byte("null")) {
		return optionalNumber{}, nil
	}
	var scalar float32
	if err := json.Unmarshal(message, &scalar); err == nil {
		return optionalNumber{Value: scalar, Present: true}, nil
	}
	var ranged struct {
		Min float32 `json:"range_min"`
		Max float32 `json:"range_max"`
	}
	if err := json.Unmarshal(message, &ranged); err != nil {
		return optionalNumber{}, err
	}
	return optionalNumber{Min: ranged.Min, Max: ranged.Max, Ranged: true, Present: true}, nil
}

func rawNumber(message json.RawMessage) (float32, error) {
	if len(message) == 0 || bytes.Equal(bytes.TrimSpace(message), []byte("null")) {
		return 0, nil
	}
	var value float32
	if err := json.Unmarshal(message, &value); err != nil {
		return 0, err
	}
	return value, nil
}

// rawString accepts either a string or a named string component.
func rawString(message json.RawMessage) (string, error) {
	if len(message) == 0 || bytes.Equal(bytes.TrimSpace(message), []byte("null")) {
		return "", nil
	}
	var value string
	if err := json.Unmarshal(message, &value); err == nil {
		return value, nil
	}
	var object struct {
		Value string `json:"value"`
		Name  string `json:"name"`
	}
	if err := json.Unmarshal(message, &object); err != nil {
		return "", err
	}
	if object.Value != "" {
		return object.Value, nil
	}
	return object.Name, nil
}

// decodeShape distinguishes unavailable shapes from available empty shapes.
func decodeShape(message json.RawMessage) ([]generatedBox, bool, error) {
	trimmed := bytes.TrimSpace(message)
	if len(trimmed) == 0 || bytes.Equal(trimmed, []byte("null")) {
		return nil, false, nil
	}
	var value any
	decoder := json.NewDecoder(bytes.NewReader(trimmed))
	decoder.UseNumber()
	if err := decoder.Decode(&value); err != nil {
		return nil, false, err
	}
	array, ok := value.([]any)
	if !ok {
		return nil, false, fmt.Errorf("expected array, got %T", value)
	}
	if len(array) == 0 {
		return []generatedBox{}, true, nil
	}
	if len(array) == 6 {
		if box, ok := anyBox(array); ok {
			if err := validateBox(box); err != nil {
				return nil, false, err
			}
			return []generatedBox{box}, true, nil
		}
	}
	boxes := make([]generatedBox, 0, len(array))
	for _, entry := range array {
		values, ok := entry.([]any)
		if !ok {
			return nil, false, fmt.Errorf("expected box array, got %T", entry)
		}
		box, ok := anyBox(values)
		if !ok {
			return nil, false, fmt.Errorf("expected six numeric box coordinates")
		}
		if err := validateBox(box); err != nil {
			return nil, false, err
		}
		boxes = append(boxes, box)
	}
	return boxes, true, nil
}

// anyBox decodes six numeric coordinates into a block-local box.
func anyBox(values []any) (generatedBox, bool) {
	if len(values) != 6 {
		return generatedBox{}, false
	}
	var box generatedBox
	for index, value := range values {
		number, ok := value.(json.Number)
		if !ok {
			return generatedBox{}, false
		}
		parsed, err := strconv.ParseFloat(string(number), 32)
		if err != nil {
			return generatedBox{}, false
		}
		box[index] = float32(parsed)
	}
	return box, true
}

// validateBox rejects non-finite coordinates and reversed bounds.
func validateBox(box generatedBox) error {
	for _, value := range box {
		if math.IsNaN(float64(value)) || math.IsInf(float64(value), 0) {
			return errors.New("box contains a non-finite coordinate")
		}
	}
	if box[0] > box[3] || box[1] > box[4] || box[2] > box[5] {
		return fmt.Errorf("box minimum exceeds maximum: %v", box)
	}
	return nil
}

// shapeKey identifies a box sequence without rounding its coordinates.
func shapeKey(boxes []generatedBox) string {
	var output strings.Builder
	for _, box := range boxes {
		for _, value := range box {
			fmt.Fprintf(&output, "%08x", math.Float32bits(value))
		}
	}
	return output.String()
}

// parseRGBA decodes a hexadecimal RGBA color, or zero when absent.
func parseRGBA(value string) (uint32, error) {
	if value == "" {
		return 0, nil
	}
	if len(value) != 9 || value[0] != '#' {
		return 0, fmt.Errorf("expected #RRGGBBAA, got %q", value)
	}
	parsed, err := strconv.ParseUint(value[1:], 16, 32)
	return uint32(parsed), err
}

// readJSON loads a source document and optionally removes JSON comments.
func readJSON(path string, destination any, allowComments bool) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	content = bytes.TrimPrefix(content, []byte{0xef, 0xbb, 0xbf})
	if allowComments {
		content, err = stripJSONComments(content)
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
	}
	if err := json.Unmarshal(content, destination); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	return nil
}

// stripJSONComments removes comments without changing quoted strings.
func stripJSONComments(input []byte) ([]byte, error) {
	output := make([]byte, 0, len(input))
	inString, escaped := false, false
	for index := 0; index < len(input); {
		current := input[index]
		if inString {
			output = append(output, current)
			index++
			if escaped {
				escaped = false
				continue
			}
			if current == '\\' {
				escaped = true
			} else if current == '"' {
				inString = false
			}
			continue
		}
		if current == '"' {
			inString = true
			output = append(output, current)
			index++
			continue
		}
		if current != '/' || index+1 == len(input) {
			output = append(output, current)
			index++
			continue
		}
		next := input[index+1]
		switch next {
		case '/':
			output = append(output, ' ', ' ')
			index += 2
			for index < len(input) && input[index] != '\n' {
				output = append(output, ' ')
				index++
			}
		case '*':
			output = append(output, ' ', ' ')
			index += 2
			closed := false
			for index < len(input) {
				if index+1 < len(input) && input[index] == '*' && input[index+1] == '/' {
					output = append(output, ' ', ' ')
					index += 2
					closed = true
					break
				}
				if input[index] == '\n' {
					output = append(output, '\n')
				} else {
					output = append(output, ' ')
				}
				index++
			}
			if !closed {
				return nil, errors.New("unterminated block comment")
			}
		default:
			output = append(output, current)
			index++
		}
	}
	if inString {
		return nil, errors.New("unterminated string")
	}
	return output, nil
}

// Write replaces generated files as one rollback-protected batch, then removes
// stale files owned by this generator in the output packages. Handwritten files
// and files owned by other generators are never removed.
func Write(outputDir string, files map[string][]byte) error {
	return writeWithRename(outputDir, files, os.Rename)
}

// writeWithRename stages a batch and restores replaced files if installation fails.
func writeWithRename(outputDir string, files map[string][]byte, rename func(string, string) error) error {
	expected := make(map[string]struct{}, len(files))
	names := make([]string, 0, len(files))
	for name := range files {
		clean := filepath.Clean(filepath.FromSlash(name))
		if filepath.IsAbs(clean) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
			return fmt.Errorf("generated path escapes output directory: %q", name)
		}
		expected[filepath.Join(outputDir, clean)] = struct{}{}
		names = append(names, name)
	}

	sort.Strings(names)
	type stagedFile struct {
		temporary string
		final     string
	}
	staged := make([]stagedFile, 0, len(names))
	cleanupStaged := func() {
		for _, file := range staged {
			_ = os.Remove(file.temporary)
		}
	}
	for _, name := range names {
		path := filepath.Join(outputDir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			cleanupStaged()
			return err
		}
		temporary, err := os.CreateTemp(filepath.Dir(path), ".generate-*")
		if err != nil {
			cleanupStaged()
			return err
		}
		temporaryPath := temporary.Name()
		if _, err = temporary.Write(files[name]); err == nil {
			err = temporary.Chmod(0o644)
		}
		if closeErr := temporary.Close(); err == nil {
			err = closeErr
		}
		if err != nil {
			_ = os.Remove(temporaryPath)
			cleanupStaged()
			return err
		}
		staged = append(staged, stagedFile{temporary: temporaryPath, final: path})
	}
	type committedFile struct {
		final  string
		backup string
	}
	committed := make([]committedFile, 0, len(staged))
	rollback := func() error {
		var rollbackErrors []error
		for index := len(committed) - 1; index >= 0; index-- {
			file := committed[index]
			if err := os.Remove(file.final); err != nil && !os.IsNotExist(err) {
				rollbackErrors = append(rollbackErrors, fmt.Errorf("remove replacement %s: %w", file.final, err))
				continue
			}
			if file.backup != "" {
				if err := rename(file.backup, file.final); err != nil {
					rollbackErrors = append(rollbackErrors, fmt.Errorf("restore %s: %w", file.final, err))
				}
			}
		}
		return errors.Join(rollbackErrors...)
	}
	for index, file := range staged {
		backup := ""
		info, err := os.Lstat(file.final)
		if err == nil {
			if !info.Mode().IsRegular() {
				for _, remaining := range staged[index:] {
					_ = os.Remove(remaining.temporary)
				}
				return errors.Join(
					fmt.Errorf("generated target is not a regular file: %s", file.final),
					rollback(),
				)
			}
			backupFile, createErr := os.CreateTemp(filepath.Dir(file.final), ".generate-backup-*")
			if createErr != nil {
				for _, remaining := range staged[index:] {
					_ = os.Remove(remaining.temporary)
				}
				return errors.Join(createErr, rollback())
			}
			backup = backupFile.Name()
			if closeErr := backupFile.Close(); closeErr != nil {
				_ = os.Remove(backup)
				for _, remaining := range staged[index:] {
					_ = os.Remove(remaining.temporary)
				}
				return errors.Join(closeErr, rollback())
			}
			if removeErr := os.Remove(backup); removeErr != nil {
				for _, remaining := range staged[index:] {
					_ = os.Remove(remaining.temporary)
				}
				return errors.Join(removeErr, rollback())
			}
			if err = rename(file.final, backup); err != nil {
				for _, remaining := range staged[index:] {
					_ = os.Remove(remaining.temporary)
				}
				return errors.Join(err, rollback())
			}
		} else if !os.IsNotExist(err) {
			for _, remaining := range staged[index:] {
				_ = os.Remove(remaining.temporary)
			}
			return errors.Join(err, rollback())
		}
		committed = append(committed, committedFile{final: file.final, backup: backup})
		if err = rename(file.temporary, file.final); err != nil {
			for _, remaining := range staged[index:] {
				_ = os.Remove(remaining.temporary)
			}
			return errors.Join(err, rollback())
		}
	}
	for _, file := range committed {
		if file.backup != "" {
			_ = os.Remove(file.backup)
		}
	}

	// Derive package directories from this run's outputs, then remove only files
	// bearing this generator's marker. Other generators may share a package.
	directories := make(map[string]struct{})
	for _, name := range names {
		directories[filepath.Dir(filepath.Join(outputDir, filepath.FromSlash(name)))] = struct{}{}
	}
	for _, dir := range sortedKeys(directories) {
		entries, err := os.ReadDir(dir)
		if err != nil {
			return err
		}
		for _, entry := range entries {
			if !entry.Type().IsRegular() || !strings.HasSuffix(entry.Name(), "_generated.go") {
				continue
			}
			path := filepath.Join(dir, entry.Name())
			if _, ok := expected[path]; ok {
				continue
			}
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if !bytes.HasPrefix(content, []byte(generatedMarker+"\n")) {
				continue
			}
			if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
				return fmt.Errorf("remove stale generated file %s: %w", path, err)
			}
		}
	}
	return nil
}

// mergeFiles combines output sets and rejects duplicate paths.
func mergeFiles(destination, source map[string][]byte) error {
	for name, content := range source {
		if _, exists := destination[name]; exists {
			return fmt.Errorf("duplicate generated path %s", name)
		}
		destination[name] = content
	}
	return nil
}

// generatedSource wraps declarations with this generator's ownership marker.
func generatedSource(packageName, body string) string {
	return generatedMarker + "\n\npackage " + packageName + "\n\n" + body
}

// exportedIdentifiers derives valid, unique Go names from source identifiers.
func exportedIdentifiers(names []string) (map[string]string, error) {
	identifiers := make(map[string]string, len(names))
	seen := make(map[string]string, len(names))
	for _, name := range names {
		local := localName(name)
		parts := strings.FieldsFunc(local, func(value rune) bool {
			return !unicode.IsLetter(value) && !unicode.IsDigit(value)
		})
		var identifier strings.Builder
		for _, part := range parts {
			runes := []rune(part)
			if len(runes) == 0 {
				continue
			}
			identifier.WriteRune(unicode.ToUpper(runes[0]))
			identifier.WriteString(string(runes[1:]))
		}
		value := identifier.String()
		if value == "" {
			return nil, fmt.Errorf("cannot derive Go identifier from %q", name)
		}
		if first := []rune(value)[0]; unicode.IsDigit(first) {
			value = "X" + value
		}
		if previous, ok := seen[value]; ok {
			return nil, fmt.Errorf("Go identifier %s collides for %q and %q", value, previous, name)
		}
		seen[value] = name
		identifiers[name] = value
	}
	return identifiers, nil
}

// generatedFileNames derives unique output filenames from source identifiers.
func generatedFileNames(names []string) (map[string]string, error) {
	fileNames := make(map[string]string, len(names))
	seen := make(map[string]string, len(names))
	for _, name := range names {
		var base strings.Builder
		var previousLetterOrDigit bool
		for _, value := range localName(name) {
			if !unicode.IsLetter(value) && !unicode.IsDigit(value) {
				if base.Len() != 0 && !strings.HasSuffix(base.String(), "_") {
					base.WriteByte('_')
				}
				previousLetterOrDigit = false
				continue
			}
			if unicode.IsUpper(value) && previousLetterOrDigit {
				base.WriteByte('_')
			}
			base.WriteRune(unicode.ToLower(value))
			previousLetterOrDigit = true
		}
		value := strings.Trim(base.String(), "_") + "_generated.go"
		if value == "_generated.go" {
			return nil, fmt.Errorf("cannot derive generated filename from %q", name)
		}
		if previous, ok := seen[value]; ok {
			return nil, fmt.Errorf("generated filename %s collides for %q and %q", value, previous, name)
		}
		seen[value] = name
		fileNames[name] = value
	}
	return fileNames, nil
}

// localName removes the namespace from a source identifier.
func localName(name string) string {
	if index := strings.LastIndexByte(name, ':'); index >= 0 {
		return name[index+1:]
	}
	return name
}

// unexportedIdentifier lowers the first letter of a generated Go name.
func unexportedIdentifier(identifier string) string {
	runes := []rune(identifier)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

// formattedGo formats an emitted source file and labels syntax errors.
func formattedGo(name, source string) ([]byte, error) {
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format %s: %w", name, err)
	}
	return formatted, nil
}

// goFloat renders a float32 without losing its represented value.
func goFloat(value float32) string {
	return strconv.FormatFloat(float64(value), 'g', -1, 32)
}

// goStrings renders a string slice as a Go expression.
func goStrings(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	var output strings.Builder
	output.WriteString("[]string{")
	for _, value := range values {
		fmt.Fprintf(&output, "%q,", value)
	}
	output.WriteByte('}')
	return output.String()
}

// sortedKeys returns map keys in lexical order for deterministic output.
func sortedKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
