package generator

import (
	"bytes"
	"errors"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestGenerateProducesDeterministicImportableGo(t *testing.T) {
	cfg := Config{
		CloudburstDir: filepath.Join("testdata", "cloudburst"),
		BDSDir:        filepath.Join("testdata", "bds"),
		CloudburstRef: "fixture-cloudburst",
		BDSVersion:    "fixture-bds",
		BiomeIDs:      map[string]int32{"minecraft:plains": 1},
	}

	first, firstStats, err := Generate(cfg)
	if err != nil {
		t.Fatal(err)
	}
	second, secondStats, err := Generate(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(firstStats, secondStats) {
		t.Fatalf("non-deterministic stats: first=%+v second=%+v", firstStats, secondStats)
	}
	if firstStats.BlockStates != 2 || firstStats.Biomes != 1 || firstStats.VoxelShapes != 1 ||
		firstStats.Entities != 2 || firstStats.Foods != 1 {
		t.Fatalf("unexpected stats: %+v", firstStats)
	}

	if len(first) != len(second) {
		t.Fatalf("non-deterministic file count: first=%d second=%d", len(first), len(second))
	}
	for name, content := range first {
		if !bytes.Equal(content, second[name]) {
			t.Errorf("%s differs between runs", name)
		}
		if filepath.Ext(name) == ".go" {
			if _, err := parser.ParseFile(token.NewFileSet(), name, content, parser.AllErrors); err != nil {
				t.Errorf("%s is not valid Go: %v", name, err)
			}
		}
	}

	assertContains(t, first, "block/stone_generated.go", "var Stone = Block{")
	assertContains(t, first, "block/stone_generated.go", `"minecraft:stone"`)
	assertContains(t, first, "block/stone_generated.go", "Hash: 100")
	assertContains(t, first, "block/air_generated.go", "var Air = Block{")
	assertContains(t, first, "block/air_generated.go", "Hash: 50")
	assertContains(t, first, "block/index_generated.go", "Stone,")
	assertContains(t, first, "block/index_generated.go", "stoneStates[0],")
	assertContains(t, first, "block/index_generated.go", "airStates[0],")
	assertContains(t, first, "biome/plains_generated.go", "var Plains = Biome{")
	assertContains(t, first, "biome/plains_generated.go", `"minecraft:plains"`)
	assertContains(t, first, "biome/plains_generated.go", "ID:                1,")
	assertContains(t, first, "biome/plains_generated.go", "HasID:             true,")
	assertContains(t, first, "biome/index_generated.go", "Plains,")
	assertContains(t, first, "voxelshape/anvil_generated.go", "var Anvil = Shape{")
	assertContains(t, first, "voxelshape/anvil_generated.go", "0.125")
	assertContains(t, first, "entity/arrow_generated.go", "var Arrow = Entity{")
	assertContains(t, first, "entity/arrow_generated.go", `"minecraft:arrow"`)
	assertContains(t, first, "entity/arrow_generated.go", "Value: 0.05")
	assertContains(t, first, "entity/donkey_generated.go", "Min: 15")
	assertContains(t, first, "entity/donkey_generated.go", "Max: 30")
	assertContains(t, first, "item/apple_generated.go", "var Apple = Food{")
	assertContains(t, first, "item/apple_generated.go", `"minecraft:apple"`)
	assertContains(t, first, "item/apple_generated.go", `Name: "regeneration"`)
	assertContains(t, first, "item/index_generated.go", "Apple,")
	for name := range first {
		if filepath.Ext(name) != ".go" && name != "semantic_sources.json" {
			t.Fatalf("semantic generation copied a source asset: %s", name)
		}
		if strings.HasPrefix(name, "vanilla/") || strings.HasPrefix(name, "generated/") {
			t.Fatalf("semantic generation emitted an obsolete package: %s", name)
		}
	}
	assertNotContains(t, first, "biome/index_generated.go", "var specs =")
	assertNotContains(t, first, "entity/index_generated.go", "var specs =")
	assertNotContains(t, first, "voxelshape/index_generated.go", "var specs =")
	assertNotContains(t, first, "item/index_generated.go", "var foods =")
	assertContains(t, first, "version_generated.go", `BDSVersion`)
	assertContains(t, first, "version_generated.go", `"fixture-bds"`)
}

func TestWriteRemovesOnlyOwnedStaleGeneratedFiles(t *testing.T) {
	output := t.TempDir()
	packageDir := filepath.Join(output, "item")
	if err := os.MkdirAll(packageDir, 0o755); err != nil {
		t.Fatal(err)
	}
	fixtures := map[string]string{
		"stale_generated.go":   GeneratedMarker + "\npackage item\n",
		"runtime_generated.go": "// Code generated by data/cmd/runtimegen; DO NOT EDIT.\npackage item\n",
		"item.go":              "package item\n",
	}
	for name, content := range fixtures {
		if err := os.WriteFile(filepath.Join(packageDir, name), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	files := map[string][]byte{"item/index_generated.go": []byte(generatedSource("item", ""))}
	if err := Write(output, GeneratedMarker, files); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(packageDir, "stale_generated.go")); !os.IsNotExist(err) {
		t.Fatalf("stale owned file was not removed: %v", err)
	}
	for _, name := range []string{"item.go", "runtime_generated.go", "index_generated.go"} {
		if _, err := os.Stat(filepath.Join(packageDir, name)); err != nil {
			t.Fatalf("expected file %s is missing: %v", name, err)
		}
	}
}

func TestWriteFailurePreservesPreviousGeneration(t *testing.T) {
	output := t.TempDir()
	packageDir := filepath.Join(output, "biome")
	if err := os.MkdirAll(packageDir, 0o755); err != nil {
		t.Fatal(err)
	}
	stale := filepath.Join(packageDir, "stale_generated.go")
	if err := os.WriteFile(stale, []byte("package biome\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	blocker := filepath.Join(output, "blocked")
	if err := os.WriteFile(blocker, []byte("not a directory"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := Write(output, GeneratedMarker, map[string][]byte{
		"blocked/new_generated.go": []byte("package blocked\n"),
	})
	if err == nil {
		t.Fatal("Write succeeded with a file blocking the output directory")
	}
	if _, statErr := os.Stat(stale); statErr != nil {
		t.Fatalf("previous generated file was removed after failed write: %v", statErr)
	}
}

func TestWritePreservesOtherGeneratorInSharedPackages(t *testing.T) {
	output := t.TempDir()
	runtimeMarker := "// Code generated by data/cmd/runtimegen; DO NOT EDIT."
	semantic := map[string][]byte{
		"version_generated.go":    []byte(generatedSource("data", "")),
		"item/apple_generated.go": []byte(generatedSource("item", "")),
	}
	runtime := map[string][]byte{
		"release_generated.go":      []byte(runtimeMarker + "\npackage data\n"),
		"release.json":              []byte("{}\n"),
		"item/runtime_generated.go": []byte(runtimeMarker + "\npackage item\n"),
	}
	for range 2 {
		if err := Write(output, GeneratedMarker, semantic); err != nil {
			t.Fatal(err)
		}
		if err := Write(output, runtimeMarker, runtime); err != nil {
			t.Fatal(err)
		}
	}
	for _, files := range []map[string][]byte{semantic, runtime} {
		for name, want := range files {
			got, err := os.ReadFile(filepath.Join(output, name))
			if err != nil || !bytes.Equal(got, want) {
				t.Errorf("shared output %s changed: %q, %v", name, got, err)
			}
		}
	}
}

func TestWriteRenameFailureRollsBackReplacedFiles(t *testing.T) {
	output := t.TempDir()
	first := filepath.Join(output, "biome", "a_generated.go")
	second := filepath.Join(output, "biome", "z_generated.go")
	if err := os.MkdirAll(filepath.Dir(first), 0o755); err != nil {
		t.Fatal(err)
	}
	original := []byte("package biome\n// old\n")
	if err := os.WriteFile(first, original, 0o644); err != nil {
		t.Fatal(err)
	}

	injected := errors.New("injected second rename failure")
	err := writeWithRename(output, GeneratedMarker, map[string][]byte{
		"biome/a_generated.go": []byte("package biome\n// new\n"),
		"biome/z_generated.go": []byte("package biome\n"),
	}, func(oldPath, newPath string) error {
		if newPath == second {
			return injected
		}
		return os.Rename(oldPath, newPath)
	})
	if !errors.Is(err, injected) {
		t.Fatalf("Write error = %v, want injected rename failure", err)
	}
	got, readErr := os.ReadFile(first)
	if readErr != nil {
		t.Fatalf("read restored first file: %v", readErr)
	}
	if !bytes.Equal(got, original) {
		t.Fatalf("first file was not rolled back: got %q, want %q", got, original)
	}
	if _, statErr := os.Stat(second); !os.IsNotExist(statErr) {
		t.Fatalf("second file exists after rollback: %v", statErr)
	}
}

// assertContains checks that a generated file includes an expected declaration.
func assertContains(t *testing.T, files map[string][]byte, name, want string) {
	t.Helper()
	content, ok := files[name]
	if !ok {
		t.Fatalf("missing generated file %s", name)
	}
	if !strings.Contains(string(content), want) {
		t.Errorf("%s does not contain %q", name, want)
	}
}

// assertNotContains checks that a generated file omits an obsolete declaration.
func assertNotContains(t *testing.T, files map[string][]byte, name, unwanted string) {
	t.Helper()
	content, ok := files[name]
	if !ok {
		t.Fatalf("missing generated file %s", name)
	}
	if strings.Contains(string(content), unwanted) {
		t.Errorf("%s unexpectedly contains %q", name, unwanted)
	}
}
