// Code generated by data/cmd/generate; DO NOT EDIT.

package item

// AppleEnchanted is the generated definition for minecraft:appleEnchanted.
var AppleEnchanted = Food{
	Name:               "minecraft:appleEnchanted",
	Nutrition:          4,
	SaturationModifier: "supernatural",
	UseDuration:        32,
	CanAlwaysEat:       true,
	UsingConvertsTo:    "",
	Effects: []Effect{
		{Name: "regeneration", Chance: 1, Duration: 30, Amplifier: 4},
		{Name: "absorption", Chance: 1, Duration: 120, Amplifier: 3},
		{Name: "resistance", Chance: 1, Duration: 300, Amplifier: 0},
		{Name: "fire_resistance", Chance: 1, Duration: 300, Amplifier: 0},
	},
}
