// Code generated by data/cmd/generate; DO NOT EDIT.

package item

// Bread is the generated definition for minecraft:bread.
var Bread = Food{
	Name:               "minecraft:bread",
	Nutrition:          5,
	SaturationModifier: "normal",
	UseDuration:        32,
	CanAlwaysEat:       false,
	UsingConvertsTo:    "",
	Effects:            []Effect{},
}
