// Code generated by data/cmd/generate; DO NOT EDIT.

package item

// ChorusFruit is the generated definition for minecraft:chorus_fruit.
var ChorusFruit = Food{
	Name:               "minecraft:chorus_fruit",
	Nutrition:          4,
	SaturationModifier: "low",
	UseDuration:        32,
	CanAlwaysEat:       true,
	UsingConvertsTo:    "",
	Effects:            []Effect{},
}
