// Code generated by data/cmd/generate; DO NOT EDIT.

package item

// CookedBeef is the generated definition for minecraft:cooked_beef.
var CookedBeef = Food{
	Name:               "minecraft:cooked_beef",
	Nutrition:          8,
	SaturationModifier: "good",
	UseDuration:        32,
	CanAlwaysEat:       false,
	UsingConvertsTo:    "",
	Effects:            []Effect{},
}
