// Code generated by data/cmd/generate; DO NOT EDIT.

package item

// CookedPorkchop is the generated definition for minecraft:cooked_porkchop.
var CookedPorkchop = Food{
	Name:               "minecraft:cooked_porkchop",
	Nutrition:          8,
	SaturationModifier: "good",
	UseDuration:        32,
	CanAlwaysEat:       false,
	UsingConvertsTo:    "",
	Effects:            []Effect{},
}
