// Code generated by data/cmd/generate; DO NOT EDIT.

package item

// GoldenApple is the generated definition for minecraft:golden_apple.
var GoldenApple = Food{
	Name:               "minecraft:golden_apple",
	Nutrition:          4,
	SaturationModifier: "supernatural",
	UseDuration:        32,
	CanAlwaysEat:       true,
	UsingConvertsTo:    "",
	Effects: []Effect{
		{Name: "regeneration", Chance: 1, Duration: 5, Amplifier: 1},
		{Name: "absorption", Chance: 1, Duration: 120, Amplifier: 0},
	},
}
