// Code generated by data/cmd/generate; DO NOT EDIT.

package item

// GoldenCarrot is the generated definition for minecraft:golden_carrot.
var GoldenCarrot = Food{
	Name:               "minecraft:golden_carrot",
	Nutrition:          6,
	SaturationModifier: "supernatural",
	UseDuration:        32,
	CanAlwaysEat:       false,
	UsingConvertsTo:    "",
	Effects:            []Effect{},
}
