// Code generated by data/cmd/generate; DO NOT EDIT.

package item

// MushroomStew is the generated definition for minecraft:mushroom_stew.
var MushroomStew = Food{
	Name:               "minecraft:mushroom_stew",
	Nutrition:          6,
	SaturationModifier: "normal",
	UseDuration:        32,
	CanAlwaysEat:       false,
	UsingConvertsTo:    "bowl",
	Effects:            []Effect{},
}
