// Code generated by data/cmd/generate; DO NOT EDIT.

package item

// SpiderEye is the generated definition for minecraft:spider_eye.
var SpiderEye = Food{
	Name:               "minecraft:spider_eye",
	Nutrition:          2,
	SaturationModifier: "good",
	UseDuration:        32,
	CanAlwaysEat:       false,
	UsingConvertsTo:    "",
	Effects: []Effect{
		{Name: "poison", Chance: 1, Duration: 5, Amplifier: 0},
	},
}
