// Code generated by data/cmd/generate; DO NOT EDIT.

package item

// SweetBerries is the generated definition for minecraft:sweet_berries.
var SweetBerries = Food{
	Name:               "minecraft:sweet_berries",
	Nutrition:          2,
	SaturationModifier: "low",
	UseDuration:        32,
	CanAlwaysEat:       false,
	UsingConvertsTo:    "",
	Effects:            []Effect{},
}
