// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// Cod is the generated definition for minecraft:cod.
var Cod = Entity{
	Name:          "minecraft:cod",
	SpawnCategory: "water_ambient",
	Experimental:  false,
	Summonable:    true,
	Spawnable:     true,
	CollisionBox:  CollisionBox{Width: 0.6, Height: 0.3, Present: true},
	Health: Health{
		Initial: Number{Value: 6, Min: 0, Max: 0, Ranged: false, Present: true},
		Maximum: Float{Value: 6, Present: true},
		Present: true,
	},
	Movement:          Number{Value: 0.1, Min: 0, Max: 0, Ranged: false, Present: true},
	Scale:             Number{Value: 1, Min: 0, Max: 0, Ranged: false, Present: true},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: true, Present: true},
	PushableByPiston:  Bool{Value: true, Present: true},
	HasPhysics:        true,
	Families:          []string{"cod", "fish"},
}
