// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// Donkey is the generated definition for minecraft:donkey.
var Donkey = Entity{
	Name:          "minecraft:donkey",
	SpawnCategory: "creature",
	Experimental:  false,
	Summonable:    true,
	Spawnable:     true,
	CollisionBox:  CollisionBox{Width: 1.4, Height: 1.6, Present: true},
	Health: Health{
		Initial: Number{Value: 0, Min: 15, Max: 30, Ranged: true, Present: true},
		Maximum: Float{Value: 0, Present: false},
		Present: true,
	},
	Movement:          Number{Value: 0.175, Min: 0, Max: 0, Ranged: false, Present: true},
	Scale:             Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: true, Present: true},
	PushableByPiston:  Bool{Value: true, Present: true},
	HasPhysics:        true,
	Families:          []string{"donkey", "mob"},
}
