// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// EnderCrystal is the generated definition for minecraft:ender_crystal.
var EnderCrystal = Entity{
	Name:          "minecraft:ender_crystal",
	SpawnCategory: "misc",
	Experimental:  false,
	Summonable:    true,
	Spawnable:     false,
	CollisionBox:  CollisionBox{Width: 0.98, Height: 0.98, Present: true},
	Health: Health{
		Initial: Number{Value: 1, Min: 0, Max: 0, Ranged: false, Present: true},
		Maximum: Float{Value: 1, Present: true},
		Present: true,
	},
	Movement:          Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	Scale:             Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: true, Present: true},
	PushableByPiston:  Bool{Value: true, Present: true},
	HasPhysics:        true,
	Families:          nil,
}
