// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// Ghast is the generated definition for minecraft:ghast.
var Ghast = Entity{
	Name:          "minecraft:ghast",
	SpawnCategory: "monster",
	Experimental:  false,
	Summonable:    true,
	Spawnable:     true,
	CollisionBox:  CollisionBox{Width: 4, Height: 4, Present: true},
	Health: Health{
		Initial: Number{Value: 10, Min: 0, Max: 0, Ranged: false, Present: true},
		Maximum: Float{Value: 10, Present: true},
		Present: true,
	},
	Movement:          Number{Value: 0.03, Min: 0, Max: 0, Ranged: false, Present: true},
	Scale:             Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: true, Present: true},
	PushableByPiston:  Bool{Value: true, Present: true},
	HasPhysics:        true,
	Families:          []string{"ghast", "mob", "monster"},
}
