// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// LightningBolt is the generated definition for minecraft:lightning_bolt.
var LightningBolt = Entity{
	Name:          "minecraft:lightning_bolt",
	SpawnCategory: "misc",
	Experimental:  false,
	Summonable:    true,
	Spawnable:     false,
	CollisionBox:  CollisionBox{Width: 0, Height: 0, Present: false},
	Health: Health{
		Initial: Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
		Maximum: Float{Value: 0, Present: false},
		Present: false,
	},
	Movement:          Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	Scale:             Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: false, Present: false},
	PushableByPiston:  Bool{Value: false, Present: false},
	HasPhysics:        false,
	Families:          []string{"lightning"},
}
