// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// Panda is the generated definition for minecraft:panda.
var Panda = Entity{
	Name:          "minecraft:panda",
	SpawnCategory: "creature",
	Experimental:  false,
	Summonable:    true,
	Spawnable:     true,
	CollisionBox:  CollisionBox{Width: 1.7, Height: 1.5, Present: true},
	Health: Health{
		Initial: Number{Value: 20, Min: 0, Max: 0, Ranged: false, Present: true},
		Maximum: Float{Value: 20, Present: true},
		Present: true,
	},
	Movement:          Number{Value: 0.15, Min: 0, Max: 0, Ranged: false, Present: true},
	Scale:             Number{Value: 1, Min: 0, Max: 0, Ranged: false, Present: true},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: true, Present: true},
	PushableByPiston:  Bool{Value: true, Present: true},
	HasPhysics:        true,
	Families:          []string{"panda"},
}
