// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// Sheep is the generated definition for minecraft:sheep.
var Sheep = Entity{
	Name:          "minecraft:sheep",
	SpawnCategory: "creature",
	Experimental:  false,
	Summonable:    true,
	Spawnable:     true,
	CollisionBox:  CollisionBox{Width: 0.9, Height: 1.3, Present: true},
	Health: Health{
		Initial: Number{Value: 8, Min: 0, Max: 0, Ranged: false, Present: true},
		Maximum: Float{Value: 8, Present: true},
		Present: true,
	},
	Movement:          Number{Value: 0.25, Min: 0, Max: 0, Ranged: false, Present: true},
	Scale:             Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: true, Present: true},
	PushableByPiston:  Bool{Value: true, Present: true},
	HasPhysics:        true,
	Families:          []string{"mob", "sheep"},
}
