// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// TripodCamera is the generated definition for minecraft:tripod_camera.
var TripodCamera = Entity{
	Name:          "minecraft:tripod_camera",
	SpawnCategory: "misc",
	Experimental:  false,
	Summonable:    false,
	Spawnable:     false,
	CollisionBox:  CollisionBox{Width: 0.75, Height: 1.8, Present: true},
	Health: Health{
		Initial: Number{Value: 4, Min: 0, Max: 0, Ranged: false, Present: true},
		Maximum: Float{Value: 4, Present: true},
		Present: true,
	},
	Movement:          Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	Scale:             Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: false, Present: false},
	PushableByPiston:  Bool{Value: false, Present: false},
	HasPhysics:        true,
	Families:          []string{"inanimate", "mob", "tripodcamera"},
}
