// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// Vex is the generated definition for minecraft:vex.
var Vex = Entity{
	Name:          "minecraft:vex",
	SpawnCategory: "monster",
	Experimental:  false,
	Summonable:    true,
	Spawnable:     true,
	CollisionBox:  CollisionBox{Width: 0.4, Height: 0.8, Present: true},
	Health: Health{
		Initial: Number{Value: 14, Min: 0, Max: 0, Ranged: false, Present: true},
		Maximum: Float{Value: 14, Present: true},
		Present: true,
	},
	Movement:          Number{Value: 1, Min: 0, Max: 0, Ranged: false, Present: true},
	Scale:             Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: false, Present: false},
	PushableByPiston:  Bool{Value: false, Present: false},
	HasPhysics:        true,
	Families:          []string{"mob", "monster", "vex"},
}
