// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// WitherSkeleton is the generated definition for minecraft:wither_skeleton.
var WitherSkeleton = Entity{
	Name:          "minecraft:wither_skeleton",
	SpawnCategory: "monster",
	Experimental:  false,
	Summonable:    true,
	Spawnable:     true,
	CollisionBox:  CollisionBox{Width: 0.72, Height: 2.01, Present: true},
	Health: Health{
		Initial: Number{Value: 20, Min: 0, Max: 0, Ranged: false, Present: true},
		Maximum: Float{Value: 20, Present: true},
		Present: true,
	},
	Movement:          Number{Value: 0.25, Min: 0, Max: 0, Ranged: false, Present: true},
	Scale:             Number{Value: 1.2, Min: 0, Max: 0, Ranged: false, Present: true},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: true, Present: true},
	PushableByPiston:  Bool{Value: true, Present: true},
	HasPhysics:        true,
	Families:          []string{"mob", "monster", "skeleton", "undead", "wither"},
}
