// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// WitherSkullDangerous is the generated definition for minecraft:wither_skull_dangerous.
var WitherSkullDangerous = Entity{
	Name:          "minecraft:wither_skull_dangerous",
	SpawnCategory: "misc",
	Experimental:  false,
	Summonable:    false,
	Spawnable:     false,
	CollisionBox:  CollisionBox{Width: 0.15, Height: 0.15, Present: true},
	Health: Health{
		Initial: Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
		Maximum: Float{Value: 0, Present: false},
		Present: false,
	},
	Movement:          Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	Scale:             Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	ProjectileGravity: Float{Value: 0, Present: true},
	ProjectilePower:   Float{Value: 0.6, Present: true},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: true, Present: true},
	PushableByPiston:  Bool{Value: true, Present: true},
	HasPhysics:        true,
	Families:          nil,
}
