// Code generated by data/cmd/generate; DO NOT EDIT.

package entity

// Wither is the generated definition for minecraft:wither.
var Wither = Entity{
	Name:          "minecraft:wither",
	SpawnCategory: "monster",
	Experimental:  false,
	Summonable:    true,
	Spawnable:     false,
	CollisionBox:  CollisionBox{Width: 1, Height: 3, Present: true},
	Health: Health{
		Initial: Number{Value: 600, Min: 0, Max: 0, Ranged: false, Present: true},
		Maximum: Float{Value: 600, Present: true},
		Present: true,
	},
	Movement:          Number{Value: 0.25, Min: 0, Max: 0, Ranged: false, Present: true},
	Scale:             Number{Value: 0, Min: 0, Max: 0, Ranged: false, Present: false},
	ProjectileGravity: Float{Value: 0, Present: false},
	ProjectilePower:   Float{Value: 0, Present: false},
	ProjectileBounce:  Bool{Value: false, Present: false},
	Pushable:          Bool{Value: true, Present: true},
	PushableByPiston:  Bool{Value: true, Present: true},
	HasPhysics:        true,
	Families:          []string{"mob", "monster", "skeleton", "undead", "wither"},
}
