// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// AcaciaStairs is the generated definition for minecraft:acacia_stairs.
var AcaciaStairs = Block{
	Name:           "minecraft:acacia_stairs",
	TranslationKey: "tile.acacia_stairs.name",
}

var acaciaStairsStates = [...]State{
	{Hash: 4195100603, Block: 843, Properties: 1465},
	{Hash: 4256575426, Block: 843, Properties: 1466},
	{Hash: 23082953, Block: 843, Properties: 1467},
	{Hash: 84557776, Block: 843, Properties: 1468},
	{Hash: 391845278, Block: 843, Properties: 1469},
	{Hash: 330370455, Block: 843, Properties: 1470},
	{Hash: 514794924, Block: 843, Properties: 1471},
	{Hash: 453320101, Block: 843, Properties: 1472},
}
