// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// AcaciaLog is the generated definition for minecraft:acacia_log.
var AcaciaLog = Block{
	Name:           "minecraft:acacia_log",
	TranslationKey: "tile.log.acacia.name",
}

var acaciaLogStates = [...]State{
	{Hash: 3030848113, Block: 477, Properties: 891},
	{Hash: 1975541542, Block: 477, Properties: 892},
	{Hash: 4159895696, Block: 477, Properties: 892},
}
