// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// AcaciaFence is the generated definition for minecraft:acacia_fence.
var AcaciaFence = Block{
	Name:           "minecraft:acacia_fence",
	TranslationKey: "tile.acaciaFence.name",
}

var acaciaFenceStates = [...]State{
	{Hash: 3166258901, Block: 1324, Properties: 1956},
}
