// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// AcaciaButton is the generated definition for minecraft:acacia_button.
var AcaciaButton = Block{
	Name:           "minecraft:acacia_button",
	TranslationKey: "tile.acacia_button.name",
}

var acaciaButtonStates = [...]State{
	{Hash: 152215376, Block: 1050, Properties: 59},
	{Hash: 90740553, Block: 1050, Properties: 60},
	{Hash: 29265730, Block: 1050, Properties: 61},
	{Hash: 4262758203, Block: 1050, Properties: 62},
	{Hash: 4201283380, Block: 1050, Properties: 63},
	{Hash: 4139808557, Block: 1050, Properties: 64},
	{Hash: 4116236941, Block: 1050, Properties: 65},
	{Hash: 4177711764, Block: 1050, Properties: 66},
	{Hash: 3993287295, Block: 1050, Properties: 67},
	{Hash: 4054762118, Block: 1050, Properties: 68},
	{Hash: 67168937, Block: 1050, Properties: 69},
	{Hash: 128643760, Block: 1050, Properties: 70},
}
