// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Allow is the generated definition for minecraft:allow.
var Allow = Block{
	Name:           "minecraft:allow",
	TranslationKey: "tile.allow.name",
}

var allowStates = [...]State{
	{Hash: 846081725, Block: 1024, Properties: 1720},
}
