// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// AmethystCluster is the generated definition for minecraft:amethyst_cluster.
var AmethystCluster = Block{
	Name:           "minecraft:amethyst_cluster",
	TranslationKey: "tile.amethyst_cluster.name",
}

var amethystClusterStates = [...]State{
	{Hash: 326255689, Block: 1292, Properties: 1913},
	{Hash: 3334683778, Block: 1292, Properties: 1914},
	{Hash: 839180963, Block: 1292, Properties: 1915},
	{Hash: 3430070289, Block: 1292, Properties: 1916},
	{Hash: 2581329506, Block: 1292, Properties: 1917},
	{Hash: 429109880, Block: 1292, Properties: 1918},
}
