// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// AndesiteStairs is the generated definition for minecraft:andesite_stairs.
var AndesiteStairs = Block{
	Name:           "minecraft:andesite_stairs",
	TranslationKey: "tile.andesite_stairs.name",
}

var andesiteStairsStates = [...]State{
	{Hash: 85088168, Block: 641, Properties: 427},
	{Hash: 23613345, Block: 641, Properties: 428},
	{Hash: 4257105818, Block: 641, Properties: 429},
	{Hash: 4195630995, Block: 641, Properties: 430},
	{Hash: 1958661413, Block: 641, Properties: 431},
	{Hash: 2020136236, Block: 641, Properties: 432},
	{Hash: 1835711767, Block: 641, Properties: 433},
	{Hash: 1897186590, Block: 641, Properties: 434},
}
