// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Anvil is the generated definition for minecraft:anvil.
var Anvil = Block{
	Name:           "minecraft:anvil",
	TranslationKey: "tile.anvil.intact.name",
}

var anvilStates = [...]State{
	{Hash: 2412608681, Block: 938, Properties: 1043},
	{Hash: 2047166698, Block: 938, Properties: 1044},
	{Hash: 1509232843, Block: 938, Properties: 1043},
	{Hash: 484875168, Block: 938, Properties: 1044},
}
