// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BambooPressurePlate is the generated definition for minecraft:bamboo_pressure_plate.
var BambooPressurePlate = Block{
	Name:           "minecraft:bamboo_pressure_plate",
	TranslationKey: "tile.bamboo_pressure_plate.name",
}

var bambooPressurePlateStates = [...]State{
	{Hash: 1985903750, Block: 822, Properties: 1429},
	{Hash: 1924428927, Block: 822, Properties: 1430},
	{Hash: 2108853396, Block: 822, Properties: 1430},
	{Hash: 2047378573, Block: 822, Properties: 1430},
	{Hash: 2231803042, Block: 822, Properties: 1430},
	{Hash: 2170328219, Block: 822, Properties: 1430},
	{Hash: 2354752688, Block: 822, Properties: 1430},
	{Hash: 2293277865, Block: 822, Properties: 1430},
	{Hash: 1494105166, Block: 822, Properties: 1430},
	{Hash: 1432630343, Block: 822, Properties: 1430},
	{Hash: 1617054812, Block: 822, Properties: 1430},
	{Hash: 1555579989, Block: 822, Properties: 1430},
	{Hash: 1740004458, Block: 822, Properties: 1430},
	{Hash: 1678529635, Block: 822, Properties: 1430},
	{Hash: 1862954104, Block: 822, Properties: 1430},
	{Hash: 1801479281, Block: 822, Properties: 1430},
}
