// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BambooWallSign is the generated definition for minecraft:bamboo_wall_sign.
var BambooWallSign = Block{
	Name:           "minecraft:bamboo_wall_sign",
	TranslationKey: "tile.bamboo_wall_sign.name",
}

var bambooWallSignStates = [...]State{
	{Hash: 4288896805, Block: 976, Properties: 1629},
	{Hash: 55404332, Block: 976, Properties: 1629},
	{Hash: 4165947159, Block: 976, Properties: 1630},
	{Hash: 4227421982, Block: 976, Properties: 1631},
	{Hash: 239828801, Block: 976, Properties: 1632},
	{Hash: 301303624, Block: 976, Properties: 1633},
}
