// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Barrel is the generated definition for minecraft:barrel.
var Barrel = Block{
	Name:           "minecraft:barrel",
	TranslationKey: "tile.barrel.name",
}

var barrelStates = [...]State{
	{Hash: 198111737, Block: 519, Properties: 759},
	{Hash: 501043176, Block: 519, Properties: 759},
	{Hash: 1071581843, Block: 519, Properties: 759},
	{Hash: 4094588762, Block: 519, Properties: 759},
	{Hash: 4152884613, Block: 519, Properties: 759},
	{Hash: 1814814452, Block: 519, Properties: 759},
	{Hash: 3437772462, Block: 519, Properties: 759},
	{Hash: 1556349747, Block: 519, Properties: 759},
	{Hash: 16275272, Block: 519, Properties: 759},
	{Hash: 854928037, Block: 519, Properties: 759},
	{Hash: 3097578042, Block: 519, Properties: 759},
	{Hash: 2870121023, Block: 519, Properties: 759},
}
