// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Beacon is the generated definition for minecraft:beacon.
var Beacon = Block{
	Name:           "minecraft:beacon",
	TranslationKey: "tile.beacon.name",
}

var beaconStates = [...]State{
	{Hash: 561914719, Block: 46, Properties: 122},
}
