// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Bell is the generated definition for minecraft:bell.
var Bell = Block{
	Name:           "minecraft:bell",
	TranslationKey: "tile.bell.name",
}

var bellStates = [...]State{
	{Hash: 2819870459, Block: 982, Properties: 1640},
	{Hash: 3102573530, Block: 982, Properties: 1641},
	{Hash: 3607455933, Block: 982, Properties: 1640},
	{Hash: 2309174740, Block: 982, Properties: 1641},
	{Hash: 3873952, Block: 982, Properties: 1642},
	{Hash: 1894050217, Block: 982, Properties: 1642},
	{Hash: 1085647542, Block: 982, Properties: 1642},
	{Hash: 1389854615, Block: 982, Properties: 1642},
	{Hash: 622340948, Block: 982, Properties: 1643},
	{Hash: 1920622141, Block: 982, Properties: 1644},
	{Hash: 1415739738, Block: 982, Properties: 1645},
	{Hash: 1133036667, Block: 982, Properties: 1646},
	{Hash: 1374847711, Block: 982, Properties: 1647},
	{Hash: 1250317502, Block: 982, Properties: 1648},
	{Hash: 3637079505, Block: 982, Properties: 1647},
	{Hash: 2095122600, Block: 982, Properties: 1648},
	{Hash: 1764563888, Block: 982, Properties: 1640},
	{Hash: 4157880101, Block: 982, Properties: 1641},
	{Hash: 2552149362, Block: 982, Properties: 1640},
	{Hash: 3364481311, Block: 982, Properties: 1641},
	{Hash: 1059180523, Block: 982, Properties: 1642},
	{Hash: 838743646, Block: 982, Properties: 1642},
	{Hash: 2140954113, Block: 982, Properties: 1642},
	{Hash: 334548044, Block: 982, Properties: 1642},
	{Hash: 1677647519, Block: 982, Properties: 1643},
	{Hash: 865315570, Block: 982, Properties: 1644},
	{Hash: 2471046309, Block: 982, Properties: 1645},
	{Hash: 77730096, Block: 982, Properties: 1646},
	{Hash: 319541140, Block: 982, Properties: 1647},
	{Hash: 2305624073, Block: 982, Properties: 1648},
	{Hash: 2581772934, Block: 982, Properties: 1647},
	{Hash: 3150429171, Block: 982, Properties: 1648},
}
