// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BirchStandingSign is the generated definition for minecraft:birch_standing_sign.
var BirchStandingSign = Block{
	Name:           "minecraft:birch_standing_sign",
	TranslationKey: "tile.birch_standing_sign.name",
}

var birchStandingSignStates = [...]State{
	{Hash: 1222845996, Block: 4, Properties: 11},
	{Hash: 1161371173, Block: 4, Properties: 11},
	{Hash: 1099896350, Block: 4, Properties: 11},
	{Hash: 1038421527, Block: 4, Properties: 11},
	{Hash: 1468745288, Block: 4, Properties: 11},
	{Hash: 1407270465, Block: 4, Properties: 11},
	{Hash: 1345795642, Block: 4, Properties: 11},
	{Hash: 1284320819, Block: 4, Properties: 11},
	{Hash: 1714644580, Block: 4, Properties: 11},
	{Hash: 1653169757, Block: 4, Properties: 11},
	{Hash: 1591694934, Block: 4, Properties: 11},
	{Hash: 1530220111, Block: 4, Properties: 11},
	{Hash: 1960543872, Block: 4, Properties: 11},
	{Hash: 1899069049, Block: 4, Properties: 11},
	{Hash: 1837594226, Block: 4, Properties: 11},
	{Hash: 1776119403, Block: 4, Properties: 11},
}
