// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BirchWallSign is the generated definition for minecraft:birch_wall_sign.
var BirchWallSign = Block{
	Name:           "minecraft:birch_wall_sign",
	TranslationKey: "tile.birch_wall_sign.name",
}

var birchWallSignStates = [...]State{
	{Hash: 1314747092, Block: 975, Properties: 1624},
	{Hash: 1253272269, Block: 975, Properties: 1624},
	{Hash: 1191797446, Block: 975, Properties: 1625},
	{Hash: 1130322623, Block: 975, Properties: 1626},
	{Hash: 1560646384, Block: 975, Properties: 1627},
	{Hash: 1499171561, Block: 975, Properties: 1628},
}
