// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BirchShelf is the generated definition for minecraft:birch_shelf.
var BirchShelf = Block{
	Name:           "minecraft:birch_shelf",
	TranslationKey: "tile.birch_shelf.name",
}

var birchShelfStates = [...]State{
	{Hash: 4269500173, Block: 21, Properties: 54},
	{Hash: 36007700, Block: 21, Properties: 54},
	{Hash: 4146550527, Block: 21, Properties: 54},
	{Hash: 4208025350, Block: 21, Properties: 54},
	{Hash: 3221065588, Block: 21, Properties: 54},
	{Hash: 3159590765, Block: 21, Properties: 54},
	{Hash: 3098115942, Block: 21, Properties: 54},
	{Hash: 3036641119, Block: 21, Properties: 54},
	{Hash: 780872348, Block: 21, Properties: 55},
	{Hash: 719397525, Block: 21, Properties: 55},
	{Hash: 657922702, Block: 21, Properties: 55},
	{Hash: 596447879, Block: 21, Properties: 55},
	{Hash: 1492466837, Block: 21, Properties: 55},
	{Hash: 1553941660, Block: 21, Properties: 55},
	{Hash: 1369517191, Block: 21, Properties: 55},
	{Hash: 1430992014, Block: 21, Properties: 55},
	{Hash: 2986848587, Block: 21, Properties: 56},
	{Hash: 3048323410, Block: 21, Properties: 56},
	{Hash: 3109798233, Block: 21, Properties: 56},
	{Hash: 3171273056, Block: 21, Properties: 56},
	{Hash: 3438284730, Block: 21, Properties: 56},
	{Hash: 3376809907, Block: 21, Properties: 56},
	{Hash: 3561234376, Block: 21, Properties: 56},
	{Hash: 3499759553, Block: 21, Properties: 56},
	{Hash: 624887486, Block: 21, Properties: 57},
	{Hash: 563412663, Block: 21, Properties: 57},
	{Hash: 747837132, Block: 21, Properties: 57},
	{Hash: 686362309, Block: 21, Properties: 57},
	{Hash: 4232716799, Block: 21, Properties: 57},
	{Hash: 4294191622, Block: 21, Properties: 57},
	{Hash: 60699149, Block: 21, Properties: 57},
	{Hash: 122173972, Block: 21, Properties: 57},
}
