// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BlackCarpet is the generated definition for minecraft:black_carpet.
var BlackCarpet = Block{
	Name:           "minecraft:black_carpet",
	TranslationKey: "tile.carpet.black.name",
}

var blackCarpetStates = [...]State{
	{Hash: 3529434712, Block: 805, Properties: 1408},
}
