// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BlastFurnace is the generated definition for minecraft:blast_furnace.
var BlastFurnace = Block{
	Name:           "minecraft:blast_furnace",
	TranslationKey: "tile.blast_furnace.name",
}

var blastFurnaceStates = [...]State{
	{Hash: 2142573020, Block: 1146, Properties: 456},
	{Hash: 3066600017, Block: 1146, Properties: 456},
	{Hash: 184718330, Block: 1146, Properties: 456},
	{Hash: 793504035, Block: 1146, Properties: 456},
}
