// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BlueCandleCake is the generated definition for minecraft:blue_candle_cake.
var BlueCandleCake = Block{
	Name:           "minecraft:blue_candle_cake",
	TranslationKey: "tile.blue_candle_cake.name",
}

var blueCandleCakeStates = [...]State{
	{Hash: 703377613, Block: 795, Properties: 103},
	{Hash: 3943038338, Block: 795, Properties: 104},
}
