// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BlueStainedGlassPane is the generated definition for minecraft:blue_stained_glass_pane.
var BlueStainedGlassPane = Block{
	Name:           "minecraft:blue_stained_glass_pane",
	TranslationKey: "tile.stained_glass_pane.blue.name",
}

var blueStainedGlassPaneStates = [...]State{
	{Hash: 1347150037, Block: 19, Properties: 49},
}
