// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BlueCandle is the generated definition for minecraft:blue_candle.
var BlueCandle = Block{
	Name:           "minecraft:blue_candle",
	TranslationKey: "tile.blue_candle.name",
}

var blueCandleStates = [...]State{
	{Hash: 1088625327, Block: 2, Properties: 2},
	{Hash: 529200828, Block: 2, Properties: 3},
	{Hash: 4220034033, Block: 2, Properties: 4},
	{Hash: 3849244326, Block: 2, Properties: 5},
	{Hash: 33318756, Block: 2, Properties: 6},
	{Hash: 1584507399, Block: 2, Properties: 7},
	{Hash: 3164727462, Block: 2, Properties: 8},
	{Hash: 609583601, Block: 2, Properties: 9},
}
