// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BrewingStand is the generated definition for minecraft:brewing_stand.
var BrewingStand = Block{
	Name:           "minecraft:brewing_stand",
	TranslationKey: "item.brewing_stand.name",
}

var brewingStandStates = [...]State{
	{Hash: 1742101107, Block: 1142, Properties: 1854},
	{Hash: 2192686908, Block: 1142, Properties: 1854},
	{Hash: 289017916, Block: 1142, Properties: 1854},
	{Hash: 3645770099, Block: 1142, Properties: 1854},
	{Hash: 686794536, Block: 1142, Properties: 1854},
	{Hash: 3247993479, Block: 1142, Properties: 1854},
	{Hash: 1344324487, Block: 1142, Properties: 1854},
	{Hash: 2590463528, Block: 1142, Properties: 1854},
}
