// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BrickSlab is the generated definition for minecraft:brick_slab.
var BrickSlab = Block{
	Name:           "minecraft:brick_slab",
	TranslationKey: "tile.stone_slab.brick.name",
}

var brickSlabStates = [...]State{
	{Hash: 1638596166, Block: 1135, Properties: 1851},
	{Hash: 3396552143, Block: 1135, Properties: 1852},
}
