// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BrownWool is the generated definition for minecraft:brown_wool.
var BrownWool = Block{
	Name:           "minecraft:brown_wool",
	TranslationKey: "tile.wool.brown.name",
}

var brownWoolStates = [...]State{
	{Hash: 4242034531, Block: 91, Properties: 242},
}
