// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BrownCandle is the generated definition for minecraft:brown_candle.
var BrownCandle = Block{
	Name:           "minecraft:brown_candle",
	TranslationKey: "tile.brown_candle.name",
}

var brownCandleStates = [...]State{
	{Hash: 1980081316, Block: 764, Properties: 1342},
	{Hash: 3607002295, Block: 764, Properties: 1343},
	{Hash: 2345758254, Block: 764, Properties: 1344},
	{Hash: 3370269017, Block: 764, Properties: 1345},
	{Hash: 3035387887, Block: 764, Properties: 1346},
	{Hash: 2551695724, Block: 764, Properties: 1347},
	{Hash: 3401064825, Block: 764, Properties: 1348},
	{Hash: 2314962446, Block: 764, Properties: 1349},
}
