// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BrownCandleCake is the generated definition for minecraft:brown_candle_cake.
var BrownCandleCake = Block{
	Name:           "minecraft:brown_candle_cake",
	TranslationKey: "tile.brown_candle_cake.name",
}

var brownCandleCakeStates = [...]State{
	{Hash: 1275226884, Block: 332, Properties: 103},
	{Hash: 2330533455, Block: 332, Properties: 104},
}
