// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BubbleCoralWallFan is the generated definition for minecraft:bubble_coral_wall_fan.
var BubbleCoralWallFan = Block{
	Name:           "minecraft:bubble_coral_wall_fan",
	TranslationKey: "tile.bubble_coral_wall_fan.name",
}

var bubbleCoralWallFanStates = [...]State{
	{Hash: 213479178, Block: 970, Properties: 297},
	{Hash: 152004355, Block: 970, Properties: 298},
	{Hash: 336428824, Block: 970, Properties: 299},
	{Hash: 274954001, Block: 970, Properties: 300},
}
