// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// BubbleCoralBlock is the generated definition for minecraft:bubble_coral_block.
var BubbleCoralBlock = Block{
	Name:           "minecraft:bubble_coral_block",
	TranslationKey: "tile.coral_block.purple.name",
}

var bubbleCoralBlockStates = [...]State{
	{Hash: 2730779673, Block: 453, Properties: 860},
}
