// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Bush is the generated definition for minecraft:bush.
var Bush = Block{
	Name:           "minecraft:bush",
	TranslationKey: "tile.bush.name",
}

var bushStates = [...]State{
	{Hash: 2961272235, Block: 984, Properties: 1650},
}
