// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CartographyTable is the generated definition for minecraft:cartography_table.
var CartographyTable = Block{
	Name:           "minecraft:cartography_table",
	TranslationKey: "tile.cartography_table.name",
}

var cartographyTableStates = [...]State{
	{Hash: 863215907, Block: 1352, Properties: 759},
}
