// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Chalkboard is the generated definition for minecraft:chalkboard.
var Chalkboard = Block{
	Name:           "minecraft:chalkboard",
	TranslationKey: "tile.chalkboard.name",
}

var chalkboardStates = [...]State{
	{Hash: 74718425, Block: 329, Properties: 725},
	{Hash: 136193248, Block: 329, Properties: 725},
	{Hash: 4246736075, Block: 329, Properties: 725},
	{Hash: 13243602, Block: 329, Properties: 725},
	{Hash: 4123786429, Block: 329, Properties: 725},
	{Hash: 4185261252, Block: 329, Properties: 725},
	{Hash: 4000836783, Block: 329, Properties: 725},
	{Hash: 4062311606, Block: 329, Properties: 725},
	{Hash: 3877887137, Block: 329, Properties: 725},
	{Hash: 3939361960, Block: 329, Properties: 725},
	{Hash: 3754937491, Block: 329, Properties: 725},
	{Hash: 3816412314, Block: 329, Properties: 725},
	{Hash: 3631987845, Block: 329, Properties: 725},
	{Hash: 3693462668, Block: 329, Properties: 725},
	{Hash: 3509038199, Block: 329, Properties: 725},
	{Hash: 3570513022, Block: 329, Properties: 725},
}
