// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CherryButton is the generated definition for minecraft:cherry_button.
var CherryButton = Block{
	Name:           "minecraft:cherry_button",
	TranslationKey: "tile.cherry_button.name",
}

var cherryButtonStates = [...]State{
	{Hash: 3492468297, Block: 557, Properties: 59},
	{Hash: 3553943120, Block: 557, Properties: 60},
	{Hash: 3369518651, Block: 557, Properties: 61},
	{Hash: 3430993474, Block: 557, Properties: 62},
	{Hash: 3246569005, Block: 557, Properties: 63},
	{Hash: 3308043828, Block: 557, Properties: 64},
	{Hash: 2586072892, Block: 557, Properties: 65},
	{Hash: 2524598069, Block: 557, Properties: 66},
	{Hash: 2463123246, Block: 557, Properties: 67},
	{Hash: 2401648423, Block: 557, Properties: 68},
	{Hash: 2831972184, Block: 557, Properties: 69},
	{Hash: 2770497361, Block: 557, Properties: 70},
}
