// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// ChiseledNetherBricks is the generated definition for minecraft:chiseled_nether_bricks.
var ChiseledNetherBricks = Block{
	Name:           "minecraft:chiseled_nether_bricks",
	TranslationKey: "tile.chiseled_nether_bricks.name",
}

var chiseledNetherBricksStates = [...]State{
	{Hash: 2476690620, Block: 1053, Properties: 123},
}
