// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// ChiseledCinnabar is the generated definition for minecraft:chiseled_cinnabar.
var ChiseledCinnabar = Block{
	Name:           "minecraft:chiseled_cinnabar",
	TranslationKey: "tile.chiseled_cinnabar.name",
}

var chiseledCinnabarStates = [...]State{
	{Hash: 3779517914, Block: 870, Properties: 853},
}
