// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CinnabarDoubleSlab is the generated definition for minecraft:cinnabar_double_slab.
var CinnabarDoubleSlab = Block{
	Name:           "minecraft:cinnabar_double_slab",
	TranslationKey: "tile.cinnabar_double_slab.name",
}

var cinnabarDoubleSlabStates = [...]State{
	{Hash: 1186461769, Block: 443, Properties: 853},
	{Hash: 3242838894, Block: 443, Properties: 853},
}
