// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// ClientRequestPlaceholderBlock is the generated definition for minecraft:client_request_placeholder_block.
var ClientRequestPlaceholderBlock = Block{
	Name:           "minecraft:client_request_placeholder_block",
	TranslationKey: "tile.client_request_placeholder_block.name",
}

var clientRequestPlaceholderBlockStates = [...]State{
	{Hash: 2337069118, Block: 446, Properties: 854},
}
