// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CobbledDeepslateSlab is the generated definition for minecraft:cobbled_deepslate_slab.
var CobbledDeepslateSlab = Block{
	Name:           "minecraft:cobbled_deepslate_slab",
	TranslationKey: "tile.cobbled_deepslate_slab.name",
}

var cobbledDeepslateSlabStates = [...]State{
	{Hash: 4186243800, Block: 1088, Properties: 293},
	{Hash: 3790166597, Block: 1088, Properties: 294},
}
