// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// ColoredTorchBlue is the generated definition for minecraft:colored_torch_blue.
var ColoredTorchBlue = Block{
	Name:           "minecraft:colored_torch_blue",
	TranslationKey: "tile.colored_torch.blue.name",
}

var coloredTorchBlueStates = [...]State{
	{Hash: 2557377635, Block: 468, Properties: 519},
	{Hash: 1340294207, Block: 468, Properties: 520},
	{Hash: 3545849861, Block: 468, Properties: 521},
	{Hash: 1578666424, Block: 468, Properties: 522},
	{Hash: 683867630, Block: 468, Properties: 523},
	{Hash: 140798654, Block: 468, Properties: 519},
}
