// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CopperGrate is the generated definition for minecraft:copper_grate.
var CopperGrate = Block{
	Name:           "minecraft:copper_grate",
	TranslationKey: "tile.copper_grate.name",
}

var copperGrateStates = [...]State{
	{Hash: 596285486, Block: 143, Properties: 352},
}
