// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CopperTrapdoor is the generated definition for minecraft:copper_trapdoor.
var CopperTrapdoor = Block{
	Name:           "minecraft:copper_trapdoor",
	TranslationKey: "tile.copper_trapdoor.name",
}

var copperTrapdoorStates = [...]State{
	{Hash: 826714304, Block: 751, Properties: 683},
	{Hash: 1055812991, Block: 751, Properties: 683},
	{Hash: 4048632786, Block: 751, Properties: 683},
	{Hash: 3336427249, Block: 751, Properties: 683},
	{Hash: 1882020875, Block: 751, Properties: 684},
	{Hash: 506420, Block: 751, Properties: 684},
	{Hash: 808972061, Block: 751, Properties: 684},
	{Hash: 2281120678, Block: 751, Properties: 684},
	{Hash: 1216220817, Block: 751, Properties: 685},
	{Hash: 1450759870, Block: 751, Properties: 686},
	{Hash: 2135485571, Block: 751, Properties: 687},
	{Hash: 28562080, Block: 751, Properties: 688},
	{Hash: 160914246, Block: 751, Properties: 685},
	{Hash: 2506066441, Block: 751, Properties: 686},
	{Hash: 1080179000, Block: 751, Properties: 687},
	{Hash: 1083868651, Block: 751, Properties: 688},
}
