// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CopperChain is the generated definition for minecraft:copper_chain.
var CopperChain = Block{
	Name:           "minecraft:copper_chain",
	TranslationKey: "tile.copper_chain.name",
}

var copperChainStates = [...]State{
	{Hash: 1502169779, Block: 354, Properties: 19},
	{Hash: 446863208, Block: 354, Properties: 20},
	{Hash: 2557476350, Block: 354, Properties: 21},
}
