// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CopperLantern is the generated definition for minecraft:copper_lantern.
var CopperLantern = Block{
	Name:           "minecraft:copper_lantern",
	TranslationKey: "tile.copper_lantern.name",
}

var copperLanternStates = [...]State{
	{Hash: 639828303, Block: 1350, Properties: 1880},
	{Hash: 3879489028, Block: 1350, Properties: 1881},
}
