// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CrimsonHyphae is the generated definition for minecraft:crimson_hyphae.
var CrimsonHyphae = Block{
	Name:           "minecraft:crimson_hyphae",
	TranslationKey: "tile.crimson_hyphae.name",
}

var crimsonHyphaeStates = [...]State{
	{Hash: 2914597369, Block: 469, Properties: 872},
	{Hash: 1859290798, Block: 469, Properties: 872},
	{Hash: 4043644952, Block: 469, Properties: 872},
}
