// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CrimsonSlab is the generated definition for minecraft:crimson_slab.
var CrimsonSlab = Block{
	Name:           "minecraft:crimson_slab",
	TranslationKey: "tile.crimson_slab.name",
}

var crimsonSlabStates = [...]State{
	{Hash: 1615941900, Block: 770, Properties: 1355},
	{Hash: 908746065, Block: 770, Properties: 1356},
}
