// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CrimsonStandingSign is the generated definition for minecraft:crimson_standing_sign.
var CrimsonStandingSign = Block{
	Name:           "minecraft:crimson_standing_sign",
	TranslationKey: "tile.crimson_standing_sign.name",
}

var crimsonStandingSignStates = [...]State{
	{Hash: 4226681447, Block: 1094, Properties: 1797},
	{Hash: 4288156270, Block: 1094, Properties: 1797},
	{Hash: 54663797, Block: 1094, Properties: 1797},
	{Hash: 116138620, Block: 1094, Properties: 1797},
	{Hash: 177613443, Block: 1094, Properties: 1797},
	{Hash: 239088266, Block: 1094, Properties: 1797},
	{Hash: 300563089, Block: 1094, Properties: 1797},
	{Hash: 362037912, Block: 1094, Properties: 1797},
	{Hash: 423512735, Block: 1094, Properties: 1797},
	{Hash: 484987558, Block: 1094, Properties: 1797},
	{Hash: 546462381, Block: 1094, Properties: 1797},
	{Hash: 607937204, Block: 1094, Properties: 1797},
	{Hash: 669412027, Block: 1094, Properties: 1797},
	{Hash: 730886850, Block: 1094, Properties: 1797},
	{Hash: 792361673, Block: 1094, Properties: 1797},
	{Hash: 853836496, Block: 1094, Properties: 1797},
}
