// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CutSandstone is the generated definition for minecraft:cut_sandstone.
var CutSandstone = Block{
	Name:           "minecraft:cut_sandstone",
	TranslationKey: "tile.sandstone.cut.name",
}

var cutSandstoneStates = [...]State{
	{Hash: 297338022, Block: 792, Properties: 727},
}
