// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CutSandstoneSlab is the generated definition for minecraft:cut_sandstone_slab.
var CutSandstoneSlab = Block{
	Name:           "minecraft:cut_sandstone_slab",
	TranslationKey: "tile.stone_slab4.cut_sandstone.name",
}

var cutSandstoneSlabStates = [...]State{
	{Hash: 2263821947, Block: 663, Properties: 346},
	{Hash: 696144548, Block: 663, Properties: 347},
}
