// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// CyanStainedGlassPane is the generated definition for minecraft:cyan_stained_glass_pane.
var CyanStainedGlassPane = Block{
	Name:           "minecraft:cyan_stained_glass_pane",
	TranslationKey: "tile.stained_glass_pane.cyan.name",
}

var cyanStainedGlassPaneStates = [...]State{
	{Hash: 2035589458, Block: 898, Properties: 49},
}
