// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DamagedAnvil is the generated definition for minecraft:damaged_anvil.
var DamagedAnvil = Block{
	Name:           "minecraft:damaged_anvil",
	TranslationKey: "tile.anvil.veryDamaged.name",
}

var damagedAnvilStates = [...]State{
	{Hash: 3827426657, Block: 1319, Properties: 1043},
	{Hash: 6657298, Block: 1319, Properties: 1044},
	{Hash: 2712994899, Block: 1319, Properties: 1043},
	{Hash: 2261764680, Block: 1319, Properties: 1044},
}
