// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DarkOakSapling is the generated definition for minecraft:dark_oak_sapling.
var DarkOakSapling = Block{
	Name:           "minecraft:dark_oak_sapling",
	TranslationKey: "tile.sapling.big_oak.name",
}

var darkOakSaplingStates = [...]State{
	{Hash: 2265506499, Block: 151, Properties: 370},
	{Hash: 1210199928, Block: 151, Properties: 370},
}
