// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DarkOakTrapdoor is the generated definition for minecraft:dark_oak_trapdoor.
var DarkOakTrapdoor = Block{
	Name:           "minecraft:dark_oak_trapdoor",
	TranslationKey: "tile.dark_oak_trapdoor.name",
}

var darkOakTrapdoorStates = [...]State{
	{Hash: 1330091683, Block: 1132, Properties: 1844},
	{Hash: 4165669460, Block: 1132, Properties: 1844},
	{Hash: 4044756037, Block: 1132, Properties: 1844},
	{Hash: 927336022, Block: 1132, Properties: 1844},
	{Hash: 274785112, Block: 1132, Properties: 1845},
	{Hash: 926008735, Block: 1132, Properties: 1845},
	{Hash: 2989449466, Block: 1132, Properties: 1845},
	{Hash: 1982642593, Block: 1132, Properties: 1845},
	{Hash: 182247794, Block: 1132, Properties: 1846},
	{Hash: 3352149797, Block: 1132, Properties: 1847},
	{Hash: 825271540, Block: 1132, Properties: 1848},
	{Hash: 3588521495, Block: 1132, Properties: 1849},
	{Hash: 1237554365, Block: 1132, Properties: 1846},
	{Hash: 2296843226, Block: 1132, Properties: 1847},
	{Hash: 1880578111, Block: 1132, Properties: 1848},
	{Hash: 2533214924, Block: 1132, Properties: 1849},
}
