// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DarkOakFence is the generated definition for minecraft:dark_oak_fence.
var DarkOakFence = Block{
	Name:           "minecraft:dark_oak_fence",
	TranslationKey: "tile.darkOakFence.name",
}

var darkOakFenceStates = [...]State{
	{Hash: 329256923, Block: 1025, Properties: 1721},
}
