// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DarkOakPlanks is the generated definition for minecraft:dark_oak_planks.
var DarkOakPlanks = Block{
	Name:           "minecraft:dark_oak_planks",
	TranslationKey: "tile.planks.big_oak.name",
}

var darkOakPlanksStates = [...]State{
	{Hash: 494521430, Block: 308, Properties: 694},
}
