// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DarkOakLeaves is the generated definition for minecraft:dark_oak_leaves.
var DarkOakLeaves = Block{
	Name:           "minecraft:dark_oak_leaves",
	TranslationKey: "tile.leaves.big_oak.name",
}

var darkOakLeavesStates = [...]State{
	{Hash: 3062988957, Block: 811, Properties: 503},
	{Hash: 2007682386, Block: 811, Properties: 503},
	{Hash: 2409944514, Block: 811, Properties: 503},
	{Hash: 3465251085, Block: 811, Properties: 503},
}
