// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeadHornCoralBlock is the generated definition for minecraft:dead_horn_coral_block.
var DeadHornCoralBlock = Block{
	Name:           "minecraft:dead_horn_coral_block",
	TranslationKey: "tile.coral_block.yellow_dead.name",
}

var deadHornCoralBlockStates = [...]State{
	{Hash: 3125021504, Block: 899, Properties: 566},
}
