// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeadBrainCoralFan is the generated definition for minecraft:dead_brain_coral_fan.
var DeadBrainCoralFan = Block{
	Name:           "minecraft:dead_brain_coral_fan",
	TranslationKey: "tile.coral_fan_dead.pink_fan.name",
}

var deadBrainCoralFanStates = [...]State{
	{Hash: 1659995561, Block: 81, Properties: 214},
	{Hash: 1721470384, Block: 81, Properties: 214},
}
