// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeadFireCoralFan is the generated definition for minecraft:dead_fire_coral_fan.
var DeadFireCoralFan = Block{
	Name:           "minecraft:dead_fire_coral_fan",
	TranslationKey: "tile.coral_fan_dead.red_fan.name",
}

var deadFireCoralFanStates = [...]State{
	{Hash: 194525402, Block: 964, Properties: 214},
	{Hash: 133050579, Block: 964, Properties: 214},
}
