// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeadFireCoralBlock is the generated definition for minecraft:dead_fire_coral_block.
var DeadFireCoralBlock = Block{
	Name:           "minecraft:dead_fire_coral_block",
	TranslationKey: "tile.coral_block.red_dead.name",
}

var deadFireCoralBlockStates = [...]State{
	{Hash: 3474974555, Block: 261, Properties: 566},
}
