// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeadBrainCoralBlock is the generated definition for minecraft:dead_brain_coral_block.
var DeadBrainCoralBlock = Block{
	Name:           "minecraft:dead_brain_coral_block",
	TranslationKey: "tile.coral_block.pink_dead.name",
}

var deadBrainCoralBlockStates = [...]State{
	{Hash: 2585849648, Block: 935, Properties: 566},
}
