// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeadBubbleCoralWallFan is the generated definition for minecraft:dead_bubble_coral_wall_fan.
var DeadBubbleCoralWallFan = Block{
	Name:           "minecraft:dead_bubble_coral_wall_fan",
	TranslationKey: "tile.dead_bubble_coral_wall_fan.name",
}

var deadBubbleCoralWallFanStates = [...]State{
	{Hash: 1393945284, Block: 116, Properties: 297},
	{Hash: 1332470461, Block: 116, Properties: 298},
	{Hash: 1270995638, Block: 116, Properties: 299},
	{Hash: 1209520815, Block: 116, Properties: 300},
}
