// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeepslateTiles is the generated definition for minecraft:deepslate_tiles.
var DeepslateTiles = Block{
	Name:           "minecraft:deepslate_tiles",
	TranslationKey: "tile.deepslate_tiles.name",
}

var deepslateTilesStates = [...]State{
	{Hash: 385861263, Block: 536, Properties: 345},
}
