// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeepslateTileSlab is the generated definition for minecraft:deepslate_tile_slab.
var DeepslateTileSlab = Block{
	Name:           "minecraft:deepslate_tile_slab",
	TranslationKey: "tile.deepslate_tile_slab.name",
}

var deepslateTileSlabStates = [...]State{
	{Hash: 1118934320, Block: 460, Properties: 293},
	{Hash: 4044441869, Block: 460, Properties: 294},
}
