// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeepslateBrickSlab is the generated definition for minecraft:deepslate_brick_slab.
var DeepslateBrickSlab = Block{
	Name:           "minecraft:deepslate_brick_slab",
	TranslationKey: "tile.deepslate_brick_slab.name",
}

var deepslateBrickSlabStates = [...]State{
	{Hash: 1781254744, Block: 346, Properties: 293},
	{Hash: 1073316037, Block: 346, Properties: 294},
}
