// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeepslateCopperOre is the generated definition for minecraft:deepslate_copper_ore.
var DeepslateCopperOre = Block{
	Name:           "minecraft:deepslate_copper_ore",
	TranslationKey: "tile.deepslate_copper_ore.name",
}

var deepslateCopperOreStates = [...]State{
	{Hash: 2179689791, Block: 24, Properties: 71},
}
