// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeepslateTileStairs is the generated definition for minecraft:deepslate_tile_stairs.
var DeepslateTileStairs = Block{
	Name:           "minecraft:deepslate_tile_stairs",
	TranslationKey: "tile.deepslate_tile_stairs.name",
}

var deepslateTileStairsStates = [...]State{
	{Hash: 2340425361, Block: 568, Properties: 143},
	{Hash: 2401900184, Block: 568, Properties: 144},
	{Hash: 2217475715, Block: 568, Properties: 145},
	{Hash: 2278950538, Block: 568, Properties: 146},
	{Hash: 2548031412, Block: 568, Properties: 147},
	{Hash: 2486556589, Block: 568, Properties: 148},
	{Hash: 2425081766, Block: 568, Properties: 149},
	{Hash: 2363606943, Block: 568, Properties: 150},
}
