// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DeprecatedAnvil is the generated definition for minecraft:deprecated_anvil.
var DeprecatedAnvil = Block{
	Name:           "minecraft:deprecated_anvil",
	TranslationKey: "tile.anvil.intact.name",
}

var deprecatedAnvilStates = [...]State{
	{Hash: 2526434488, Block: 646, Properties: 1043},
	{Hash: 1525764421, Block: 646, Properties: 1044},
	{Hash: 609415606, Block: 646, Properties: 1043},
	{Hash: 3502816351, Block: 646, Properties: 1044},
}
