// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Dirt is the generated definition for minecraft:dirt.
var Dirt = Block{
	Name:           "minecraft:dirt",
	TranslationKey: "tile.dirt.default.name",
}

var dirtStates = [...]State{
	{Hash: 2186211206, Block: 727, Properties: 959},
}
