// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// DoubleCutCopperSlab is the generated definition for minecraft:double_cut_copper_slab.
var DoubleCutCopperSlab = Block{
	Name:           "minecraft:double_cut_copper_slab",
	TranslationKey: "tile.double_cut_copper_slab.name",
}

var doubleCutCopperSlabStates = [...]State{
	{Hash: 1447908841, Block: 328, Properties: 424},
	{Hash: 273099918, Block: 328, Properties: 424},
}
