// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Dropper is the generated definition for minecraft:dropper.
var Dropper = Block{
	Name:           "minecraft:dropper",
	TranslationKey: "tile.dropper.name",
}

var dropperStates = [...]State{
	{Hash: 894753366, Block: 1107, Properties: 456},
	{Hash: 9946113, Block: 1107, Properties: 456},
	{Hash: 3700894404, Block: 1107, Properties: 456},
	{Hash: 3017687071, Block: 1107, Properties: 456},
	{Hash: 2995873834, Block: 1107, Properties: 456},
	{Hash: 1843022821, Block: 1107, Properties: 456},
	{Hash: 1950059937, Block: 1107, Properties: 456},
	{Hash: 3249606838, Block: 1107, Properties: 456},
	{Hash: 461233679, Block: 1107, Properties: 456},
	{Hash: 1962380500, Block: 1107, Properties: 456},
	{Hash: 4051180405, Block: 1107, Properties: 456},
	{Hash: 787716250, Block: 1107, Properties: 456},
}
