// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element96 is the generated definition for minecraft:element_96.
var Element96 = Block{
	Name:           "minecraft:element_96",
	TranslationKey: "tile.element.cm.name",
}

var element96States = [...]State{
	{Hash: 36289153, Block: 1244, Properties: 1253},
}
