// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element113 is the generated definition for minecraft:element_113.
var Element113 = Block{
	Name:           "minecraft:element_113",
	TranslationKey: "tile.element.nh.name",
}

var element113States = [...]State{
	{Hash: 4183164104, Block: 697, Properties: 1255},
}
