// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element39 is the generated definition for minecraft:element_39.
var Element39 = Block{
	Name:           "minecraft:element_39",
	TranslationKey: "tile.element.y.name",
}

var element39States = [...]State{
	{Hash: 2437376016, Block: 1185, Properties: 1254},
}
