// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element51 is the generated definition for minecraft:element_51.
var Element51 = Block{
	Name:           "minecraft:element_51",
	TranslationKey: "tile.element.sb.name",
}

var element51States = [...]State{
	{Hash: 2020599154, Block: 1203, Properties: 1776},
}
