// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element85 is the generated definition for minecraft:element_85.
var Element85 = Block{
	Name:           "minecraft:element_85",
	TranslationKey: "tile.element.at.name",
}

var element85States = [...]State{
	{Hash: 2424704037, Block: 1254, Properties: 1256},
}
