// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element79 is the generated definition for minecraft:element_79.
var Element79 = Block{
	Name:           "minecraft:element_79",
	TranslationKey: "tile.element.au.name",
}

var element79States = [...]State{
	{Hash: 579128196, Block: 1225, Properties: 1254},
}
