// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element2 is the generated definition for minecraft:element_2.
var Element2 = Block{
	Name:           "minecraft:element_2",
	TranslationKey: "tile.element.he.name",
}

var element2States = [...]State{
	{Hash: 3637608557, Block: 1073, Properties: 1257},
}
