// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element94 is the generated definition for minecraft:element_94.
var Element94 = Block{
	Name:           "minecraft:element_94",
	TranslationKey: "tile.element.pu.name",
}

var element94States = [...]State{
	{Hash: 1336665487, Block: 1242, Properties: 1253},
}
