// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element86 is the generated definition for minecraft:element_86.
var Element86 = Block{
	Name:           "minecraft:element_86",
	TranslationKey: "tile.element.rn.name",
}

var element86States = [...]State{
	{Hash: 3362137542, Block: 1253, Properties: 1257},
}
