// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element29 is the generated definition for minecraft:element_29.
var Element29 = Block{
	Name:           "minecraft:element_29",
	TranslationKey: "tile.element.cu.name",
}

var element29States = [...]State{
	{Hash: 434209963, Block: 1186, Properties: 1254},
}
