// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element28 is the generated definition for minecraft:element_28.
var Element28 = Block{
	Name:           "minecraft:element_28",
	TranslationKey: "tile.element.ni.name",
}

var element28States = [...]State{
	{Hash: 124081998, Block: 1187, Properties: 1254},
}
