// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element34 is the generated definition for minecraft:element_34.
var Element34 = Block{
	Name:           "minecraft:element_34",
	TranslationKey: "tile.element.se.name",
}

var element34States = [...]State{
	{Hash: 868665793, Block: 1178, Properties: 1773},
}
