// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Element68 is the generated definition for minecraft:element_68.
var Element68 = Block{
	Name:           "minecraft:element_68",
	TranslationKey: "tile.element.er.name",
}

var element68States = [...]State{
	{Hash: 1727855394, Block: 1235, Properties: 1869},
}
