// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// EmeraldOre is the generated definition for minecraft:emerald_ore.
var EmeraldOre = Block{
	Name:           "minecraft:emerald_ore",
	TranslationKey: "tile.emerald_ore.name",
}

var emeraldOreStates = [...]State{
	{Hash: 170572189, Block: 1098, Properties: 560},
}
