// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// EmeraldBlock is the generated definition for minecraft:emerald_block.
var EmeraldBlock = Block{
	Name:           "minecraft:emerald_block",
	TranslationKey: "tile.emerald_block.name",
}

var emeraldBlockStates = [...]State{
	{Hash: 770369380, Block: 275, Properties: 622},
}
