// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// EnchantingTable is the generated definition for minecraft:enchanting_table.
var EnchantingTable = Block{
	Name:           "minecraft:enchanting_table",
	TranslationKey: "tile.enchanting_table.name",
}

var enchantingTableStates = [...]State{
	{Hash: 1230080101, Block: 967, Properties: 1604},
}
