// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// EndGateway is the generated definition for minecraft:end_gateway.
var EndGateway = Block{
	Name:           "minecraft:end_gateway",
	TranslationKey: "tile.end_gateway.name",
}

var endGatewayStates = [...]State{
	{Hash: 1001207856, Block: 44, Properties: 120},
}
