// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// EndBricks is the generated definition for minecraft:end_bricks.
var EndBricks = Block{
	Name:           "minecraft:end_bricks",
	TranslationKey: "tile.end_bricks.name",
}

var endBricksStates = [...]State{
	{Hash: 2704849983, Block: 105, Properties: 284},
}
