// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// ExposedLightningRod is the generated definition for minecraft:exposed_lightning_rod.
var ExposedLightningRod = Block{
	Name:           "minecraft:exposed_lightning_rod",
	TranslationKey: "tile.exposed_lightning_rod.name",
}

var exposedLightningRodStates = [...]State{
	{Hash: 2804163564, Block: 338, Properties: 290},
	{Hash: 860623807, Block: 338, Properties: 290},
	{Hash: 4254025570, Block: 338, Properties: 291},
	{Hash: 623514653, Block: 338, Properties: 291},
	{Hash: 4205694920, Block: 338, Properties: 292},
	{Hash: 3689328299, Block: 338, Properties: 292},
	{Hash: 3859470135, Block: 338, Properties: 290},
	{Hash: 4100284532, Block: 338, Properties: 290},
	{Hash: 1014364845, Block: 338, Properties: 291},
	{Hash: 3863175378, Block: 338, Properties: 291},
	{Hash: 966034195, Block: 338, Properties: 292},
	{Hash: 2634021728, Block: 338, Properties: 292},
}
