// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// ExposedCopperBulb is the generated definition for minecraft:exposed_copper_bulb.
var ExposedCopperBulb = Block{
	Name:           "minecraft:exposed_copper_bulb",
	TranslationKey: "tile.exposed_copper_bulb.name",
}

var exposedCopperBulbStates = [...]State{
	{Hash: 2261349451, Block: 858, Properties: 243},
	{Hash: 4283054986, Block: 858, Properties: 835},
	{Hash: 1206042880, Block: 858, Properties: 243},
	{Hash: 1043394261, Block: 858, Properties: 835},
}
