// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Farmland is the generated definition for minecraft:farmland.
var Farmland = Block{
	Name:           "minecraft:farmland",
	TranslationKey: "tile.farmland.name",
}

var farmlandStates = [...]State{
	{Hash: 360492383, Block: 391, Properties: 815},
	{Hash: 421967206, Block: 391, Properties: 815},
	{Hash: 483442029, Block: 391, Properties: 815},
	{Hash: 544916852, Block: 391, Properties: 815},
	{Hash: 606391675, Block: 391, Properties: 815},
	{Hash: 667866498, Block: 391, Properties: 815},
	{Hash: 729341321, Block: 391, Properties: 815},
	{Hash: 790816144, Block: 391, Properties: 815},
}
