// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// FireCoralFan is the generated definition for minecraft:fire_coral_fan.
var FireCoralFan = Block{
	Name:           "minecraft:fire_coral_fan",
	TranslationKey: "tile.coral_fan.red_fan.name",
}

var fireCoralFanStates = [...]State{
	{Hash: 307997716, Block: 923, Properties: 214},
	{Hash: 246522893, Block: 923, Properties: 214},
}
