// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Furnace is the generated definition for minecraft:furnace.
var Furnace = Block{
	Name:           "minecraft:furnace",
	TranslationKey: "tile.furnace.name",
}

var furnaceStates = [...]State{
	{Hash: 3463497305, Block: 1290, Properties: 456},
	{Hash: 2478237434, Block: 1290, Properties: 456},
	{Hash: 1875646683, Block: 1290, Properties: 456},
	{Hash: 4038254352, Block: 1290, Properties: 456},
}
