// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// GlassPane is the generated definition for minecraft:glass_pane.
var GlassPane = Block{
	Name:           "minecraft:glass_pane",
	TranslationKey: "tile.glass_pane.name",
}

var glassPaneStates = [...]State{
	{Hash: 1848427078, Block: 621, Properties: 49},
}
