// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// GlowFrame is the generated definition for minecraft:glow_frame.
var GlowFrame = Block{
	Name:           "minecraft:glow_frame",
	TranslationKey: "tile.glow_frame.name",
}

var glowFrameStates = [...]State{
	{Hash: 209894407, Block: 56, Properties: 170},
	{Hash: 1926062766, Block: 56, Properties: 171},
	{Hash: 3439125297, Block: 56, Properties: 172},
	{Hash: 3607057840, Block: 56, Properties: 173},
	{Hash: 350970419, Block: 56, Properties: 174},
	{Hash: 2063999914, Block: 56, Properties: 175},
	{Hash: 1409158516, Block: 56, Properties: 176},
	{Hash: 594507737, Block: 56, Properties: 177},
	{Hash: 2715025990, Block: 56, Properties: 178},
	{Hash: 1050399555, Block: 56, Properties: 179},
	{Hash: 3167387360, Block: 56, Properties: 180},
	{Hash: 3182707925, Block: 56, Properties: 181},
	{Hash: 3449555132, Block: 56, Properties: 176},
	{Hash: 2981369337, Block: 56, Properties: 177},
	{Hash: 2383818726, Block: 56, Properties: 178},
	{Hash: 367397115, Block: 56, Properties: 179},
	{Hash: 3590631144, Block: 56, Properties: 180},
	{Hash: 3119306485, Block: 56, Properties: 181},
	{Hash: 2464465087, Block: 56, Properties: 176},
	{Hash: 3834168462, Block: 56, Properties: 177},
	{Hash: 3770332561, Block: 56, Properties: 178},
	{Hash: 4290060280, Block: 56, Properties: 179},
	{Hash: 4222693931, Block: 56, Properties: 180},
	{Hash: 2127401354, Block: 56, Properties: 181},
}
