// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// GraniteStairs is the generated definition for minecraft:granite_stairs.
var GraniteStairs = Block{
	Name:           "minecraft:granite_stairs",
	TranslationKey: "tile.granite_stairs.name",
}

var graniteStairsStates = [...]State{
	{Hash: 3590407998, Block: 295, Properties: 665},
	{Hash: 3528933175, Block: 295, Properties: 666},
	{Hash: 3713357644, Block: 295, Properties: 667},
	{Hash: 3651882821, Block: 295, Properties: 668},
	{Hash: 1493356251, Block: 295, Properties: 669},
	{Hash: 1554831074, Block: 295, Properties: 670},
	{Hash: 1616305897, Block: 295, Properties: 671},
	{Hash: 1677780720, Block: 295, Properties: 672},
}
