// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// GrassPath is the generated definition for minecraft:grass_path.
var GrassPath = Block{
	Name:           "minecraft:grass_path",
	TranslationKey: "tile.grass_path.name",
}

var grassPathStates = [...]State{
	{Hash: 1942424059, Block: 1325, Properties: 1957},
}
