// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// GrayStainedGlassPane is the generated definition for minecraft:gray_stained_glass_pane.
var GrayStainedGlassPane = Block{
	Name:           "minecraft:gray_stained_glass_pane",
	TranslationKey: "tile.stained_glass_pane.gray.name",
}

var grayStainedGlassPaneStates = [...]State{
	{Hash: 3884888474, Block: 979, Properties: 49},
}
