// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// GreenGlazedTerracotta is the generated definition for minecraft:green_glazed_terracotta.
var GreenGlazedTerracotta = Block{
	Name:           "minecraft:green_glazed_terracotta",
	TranslationKey: "tile.glazedTerracotta.green.name",
}

var greenGlazedTerracottaStates = [...]State{
	{Hash: 2457165216, Block: 932, Properties: 1578},
	{Hash: 2395690393, Block: 932, Properties: 1578},
	{Hash: 2334215570, Block: 932, Properties: 1578},
	{Hash: 2272740747, Block: 932, Properties: 1578},
	{Hash: 2211265924, Block: 932, Properties: 1578},
	{Hash: 2149791101, Block: 932, Properties: 1578},
}
