// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Grindstone is the generated definition for minecraft:grindstone.
var Grindstone = Block{
	Name:           "minecraft:grindstone",
	TranslationKey: "tile.grindstone.name",
}

var grindstoneStates = [...]State{
	{Hash: 1003295416, Block: 1309, Properties: 1926},
	{Hash: 941820593, Block: 1309, Properties: 1926},
	{Hash: 880345770, Block: 1309, Properties: 1926},
	{Hash: 818870947, Block: 1309, Properties: 1926},
	{Hash: 3460113463, Block: 1309, Properties: 1926},
	{Hash: 3521588286, Block: 1309, Properties: 1926},
	{Hash: 3583063109, Block: 1309, Properties: 1926},
	{Hash: 3644537932, Block: 1309, Properties: 1926},
	{Hash: 3246561459, Block: 1309, Properties: 1927},
	{Hash: 3308036282, Block: 1309, Properties: 1928},
	{Hash: 3369511105, Block: 1309, Properties: 1927},
	{Hash: 3430985928, Block: 1309, Properties: 1928},
	{Hash: 3808190484, Block: 1309, Properties: 1926},
	{Hash: 3746715661, Block: 1309, Properties: 1926},
	{Hash: 3685240838, Block: 1309, Properties: 1926},
	{Hash: 3623766015, Block: 1309, Properties: 1926},
}
