// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HardPinkStainedGlassPane is the generated definition for minecraft:hard_pink_stained_glass_pane.
var HardPinkStainedGlassPane = Block{
	Name:           "minecraft:hard_pink_stained_glass_pane",
	TranslationKey: "tile.hard_stained_glass_pane.pink.name",
}

var hardPinkStainedGlassPaneStates = [...]State{
	{Hash: 3626192550, Block: 1133, Properties: 93},
}
