// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HardPurpleStainedGlassPane is the generated definition for minecraft:hard_purple_stained_glass_pane.
var HardPurpleStainedGlassPane = Block{
	Name:           "minecraft:hard_purple_stained_glass_pane",
	TranslationKey: "tile.hard_stained_glass_pane.purple.name",
}

var hardPurpleStainedGlassPaneStates = [...]State{
	{Hash: 1382147006, Block: 1008, Properties: 93},
}
