// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HardYellowStainedGlassPane is the generated definition for minecraft:hard_yellow_stained_glass_pane.
var HardYellowStainedGlassPane = Block{
	Name:           "minecraft:hard_yellow_stained_glass_pane",
	TranslationKey: "tile.hard_stained_glass_pane.yellow.name",
}

var hardYellowStainedGlassPaneStates = [...]State{
	{Hash: 2050640488, Block: 427, Properties: 93},
}
