// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HardLimeStainedGlassPane is the generated definition for minecraft:hard_lime_stained_glass_pane.
var HardLimeStainedGlassPane = Block{
	Name:           "minecraft:hard_lime_stained_glass_pane",
	TranslationKey: "tile.hard_stained_glass_pane.lime.name",
}

var hardLimeStainedGlassPaneStates = [...]State{
	{Hash: 4051970779, Block: 533, Properties: 93},
}
