// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HardMagentaStainedGlassPane is the generated definition for minecraft:hard_magenta_stained_glass_pane.
var HardMagentaStainedGlassPane = Block{
	Name:           "minecraft:hard_magenta_stained_glass_pane",
	TranslationKey: "tile.hard_stained_glass_pane.magenta.name",
}

var hardMagentaStainedGlassPaneStates = [...]State{
	{Hash: 3421365584, Block: 868, Properties: 93},
}
