// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HardBlueStainedGlassPane is the generated definition for minecraft:hard_blue_stained_glass_pane.
var HardBlueStainedGlassPane = Block{
	Name:           "minecraft:hard_blue_stained_glass_pane",
	TranslationKey: "tile.hard_stained_glass_pane.blue.name",
}

var hardBlueStainedGlassPaneStates = [...]State{
	{Hash: 2086232422, Block: 1342, Properties: 93},
}
