// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HardenedClay is the generated definition for minecraft:hardened_clay.
var HardenedClay = Block{
	Name:           "minecraft:hardened_clay",
	TranslationKey: "tile.hardened_clay.name",
}

var hardenedClayStates = [...]State{
	{Hash: 3957983297, Block: 184, Properties: 437},
}
