// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HardPurpleStainedGlass is the generated definition for minecraft:hard_purple_stained_glass.
var HardPurpleStainedGlass = Block{
	Name:           "minecraft:hard_purple_stained_glass",
	TranslationKey: "tile.hard_stained_glass.purple.name",
}

var hardPurpleStainedGlassStates = [...]State{
	{Hash: 3172656462, Block: 487, Properties: 904},
}
