// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HardLightBlueStainedGlassPane is the generated definition for minecraft:hard_light_blue_stained_glass_pane.
var HardLightBlueStainedGlassPane = Block{
	Name:           "minecraft:hard_light_blue_stained_glass_pane",
	TranslationKey: "tile.hard_stained_glass_pane.light_blue.name",
}

var hardLightBlueStainedGlassPaneStates = [...]State{
	{Hash: 3130768529, Block: 657, Properties: 93},
}
