// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HeavyWeightedPressurePlate is the generated definition for minecraft:heavy_weighted_pressure_plate.
var HeavyWeightedPressurePlate = Block{
	Name:           "minecraft:heavy_weighted_pressure_plate",
	TranslationKey: "tile.heavy_weighted_pressure_plate.name",
}

var heavyWeightedPressurePlateStates = [...]State{
	{Hash: 3108640023, Block: 278, Properties: 642},
	{Hash: 3170114846, Block: 278, Properties: 643},
	{Hash: 3231589669, Block: 278, Properties: 643},
	{Hash: 3293064492, Block: 278, Properties: 643},
	{Hash: 3354539315, Block: 278, Properties: 643},
	{Hash: 3416014138, Block: 278, Properties: 643},
	{Hash: 3477488961, Block: 278, Properties: 643},
	{Hash: 3538963784, Block: 278, Properties: 643},
	{Hash: 3600438607, Block: 278, Properties: 643},
	{Hash: 3661913430, Block: 278, Properties: 643},
	{Hash: 3723388253, Block: 278, Properties: 643},
	{Hash: 3784863076, Block: 278, Properties: 643},
	{Hash: 3846337899, Block: 278, Properties: 643},
	{Hash: 3907812722, Block: 278, Properties: 643},
	{Hash: 3969287545, Block: 278, Properties: 643},
	{Hash: 4030762368, Block: 278, Properties: 643},
}
