// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HoneyBlock is the generated definition for minecraft:honey_block.
var HoneyBlock = Block{
	Name:           "minecraft:honey_block",
	TranslationKey: "tile.honey_block.name",
}

var honeyBlockStates = [...]State{
	{Hash: 1517479843, Block: 239, Properties: 542},
}
