// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// HornCoralWallFan is the generated definition for minecraft:horn_coral_wall_fan.
var HornCoralWallFan = Block{
	Name:           "minecraft:horn_coral_wall_fan",
	TranslationKey: "tile.horn_coral_wall_fan.name",
}

var hornCoralWallFanStates = [...]State{
	{Hash: 3279013159, Block: 602, Properties: 297},
	{Hash: 3340487982, Block: 602, Properties: 298},
	{Hash: 3401962805, Block: 602, Properties: 299},
	{Hash: 3463437628, Block: 602, Properties: 300},
}
