// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// InfestedChiseledStoneBricks is the generated definition for minecraft:infested_chiseled_stone_bricks.
var InfestedChiseledStoneBricks = Block{
	Name:           "minecraft:infested_chiseled_stone_bricks",
	TranslationKey: "tile.monster_egg.chiseledbrick.name",
}

var infestedChiseledStoneBricksStates = [...]State{
	{Hash: 656057126, Block: 454, Properties: 500},
}
