// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// IronTrapdoor is the generated definition for minecraft:iron_trapdoor.
var IronTrapdoor = Block{
	Name:           "minecraft:iron_trapdoor",
	TranslationKey: "tile.iron_trapdoor.name",
}

var ironTrapdoorStates = [...]State{
	{Hash: 2136558063, Block: 126, Properties: 314},
	{Hash: 1573670384, Block: 126, Properties: 314},
	{Hash: 3599968353, Block: 126, Properties: 314},
	{Hash: 361879682, Block: 126, Properties: 314},
	{Hash: 1081251492, Block: 126, Properties: 315},
	{Hash: 2628976955, Block: 126, Properties: 315},
	{Hash: 2544661782, Block: 126, Properties: 315},
	{Hash: 1417186253, Block: 126, Properties: 315},
	{Hash: 819124398, Block: 126, Properties: 316},
	{Hash: 909549633, Block: 126, Properties: 317},
	{Hash: 359295504, Block: 126, Properties: 318},
	{Hash: 4219749171, Block: 126, Properties: 319},
	{Hash: 1874430969, Block: 126, Properties: 316},
	{Hash: 4149210358, Block: 126, Properties: 317},
	{Hash: 1414602075, Block: 126, Properties: 318},
	{Hash: 3164442600, Block: 126, Properties: 319},
}
