// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// IronBlock is the generated definition for minecraft:iron_block.
var IronBlock = Block{
	Name:           "minecraft:iron_block",
	TranslationKey: "tile.iron_block.name",
}

var ironBlockStates = [...]State{
	{Hash: 3355896927, Block: 1346, Properties: 1991},
}
