// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Jukebox is the generated definition for minecraft:jukebox.
var Jukebox = Block{
	Name:           "minecraft:jukebox",
	TranslationKey: "tile.jukebox.name",
}

var jukeboxStates = [...]State{
	{Hash: 1605519270, Block: 607, Properties: 1098},
}
