// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// JungleFenceGate is the generated definition for minecraft:jungle_fence_gate.
var JungleFenceGate = Block{
	Name:           "minecraft:jungle_fence_gate",
	TranslationKey: "tile.jungle_fence_gate.name",
}

var jungleFenceGateStates = [...]State{
	{Hash: 513477517, Block: 654, Properties: 1182},
	{Hash: 2093527152, Block: 654, Properties: 1183},
	{Hash: 1494279307, Block: 654, Properties: 1182},
	{Hash: 1796038978, Block: 654, Properties: 1183},
	{Hash: 3753138242, Block: 654, Properties: 1184},
	{Hash: 3148833723, Block: 654, Properties: 1185},
	{Hash: 438972736, Block: 654, Properties: 1184},
	{Hash: 2851345549, Block: 654, Properties: 1185},
	{Hash: 4005144606, Block: 654, Properties: 1182},
	{Hash: 1477274213, Block: 654, Properties: 1183},
	{Hash: 3096310084, Block: 654, Properties: 1182},
	{Hash: 3322675159, Block: 654, Properties: 1183},
	{Hash: 765483881, Block: 654, Properties: 1184},
	{Hash: 421967642, Block: 654, Properties: 1185},
	{Hash: 4151616655, Block: 654, Properties: 1184},
	{Hash: 2267368588, Block: 654, Properties: 1185},
}
