// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// JungleSlab is the generated definition for minecraft:jungle_slab.
var JungleSlab = Block{
	Name:           "minecraft:jungle_slab",
	TranslationKey: "tile.wooden_slab.jungle.name",
}

var jungleSlabStates = [...]State{
	{Hash: 2206898405, Block: 382, Properties: 798},
	{Hash: 2626457906, Block: 382, Properties: 799},
}
