// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// JungleTrapdoor is the generated definition for minecraft:jungle_trapdoor.
var JungleTrapdoor = Block{
	Name:           "minecraft:jungle_trapdoor",
	TranslationKey: "tile.jungle_trapdoor.name",
}

var jungleTrapdoorStates = [...]State{
	{Hash: 2591864396, Block: 658, Properties: 1186},
	{Hash: 3539439003, Block: 658, Properties: 1186},
	{Hash: 3402897166, Block: 658, Properties: 1186},
	{Hash: 4026236765, Block: 658, Properties: 1186},
	{Hash: 3647170967, Block: 658, Properties: 1187},
	{Hash: 2484132432, Block: 658, Properties: 1187},
	{Hash: 163236441, Block: 658, Properties: 1187},
	{Hash: 2970930194, Block: 658, Properties: 1187},
	{Hash: 2933591837, Block: 658, Properties: 1188},
	{Hash: 565720362, Block: 658, Properties: 1189},
	{Hash: 115276623, Block: 658, Properties: 1190},
	{Hash: 3675471244, Block: 658, Properties: 1191},
	{Hash: 1878285266, Block: 658, Properties: 1188},
	{Hash: 1621026933, Block: 658, Properties: 1189},
	{Hash: 3354937348, Block: 658, Properties: 1190},
	{Hash: 435810519, Block: 658, Properties: 1191},
}
