// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// JungleWallSign is the generated definition for minecraft:jungle_wall_sign.
var JungleWallSign = Block{
	Name:           "minecraft:jungle_wall_sign",
	TranslationKey: "tile.jungle_wall_sign.name",
}

var jungleWallSignStates = [...]State{
	{Hash: 270529816, Block: 497, Properties: 916},
	{Hash: 209054993, Block: 497, Properties: 916},
	{Hash: 147580170, Block: 497, Properties: 917},
	{Hash: 86105347, Block: 497, Properties: 918},
	{Hash: 24630524, Block: 497, Properties: 919},
	{Hash: 4258122997, Block: 497, Properties: 920},
}
