// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// JungleWood is the generated definition for minecraft:jungle_wood.
var JungleWood = Block{
	Name:           "minecraft:jungle_wood",
	TranslationKey: "tile.wood.jungle.name",
}

var jungleWoodStates = [...]State{
	{Hash: 764042440, Block: 225, Properties: 215},
	{Hash: 1819349011, Block: 225, Properties: 215},
	{Hash: 3929962153, Block: 225, Properties: 215},
}
