// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LargeFern is the generated definition for minecraft:large_fern.
var LargeFern = Block{
	Name:           "minecraft:large_fern",
	TranslationKey: "tile.double_plant.fern.name",
}

var largeFernStates = [...]State{
	{Hash: 3088185042, Block: 907, Properties: 1522},
	{Hash: 4143491613, Block: 907, Properties: 1523},
}
