// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightBlueCarpet is the generated definition for minecraft:light_blue_carpet.
var LightBlueCarpet = Block{
	Name:           "minecraft:light_blue_carpet",
	TranslationKey: "tile.carpet.lightBlue.name",
}

var lightBlueCarpetStates = [...]State{
	{Hash: 2341263245, Block: 594, Properties: 1071},
}
