// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightBlock10 is the generated definition for minecraft:light_block_10.
var LightBlock10 = Block{
	Name:           "minecraft:light_block_10",
	TranslationKey: "tile.light_block.name",
}

var lightBlock10States = [...]State{
	{Hash: 3545910889, Block: 893, Properties: 1526},
}
