// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightBlueShulkerBox is the generated definition for minecraft:light_blue_shulker_box.
var LightBlueShulkerBox = Block{
	Name:           "minecraft:light_blue_shulker_box",
	TranslationKey: "tile.shulkerBoxLightBlue.name",
}

var lightBlueShulkerBoxStates = [...]State{
	{Hash: 885329687, Block: 987, Properties: 1651},
}
