// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightBlueStainedGlassPane is the generated definition for minecraft:light_blue_stained_glass_pane.
var LightBlueStainedGlassPane = Block{
	Name:           "minecraft:light_blue_stained_glass_pane",
	TranslationKey: "tile.stained_glass_pane.light_blue.name",
}

var lightBlueStainedGlassPaneStates = [...]State{
	{Hash: 834202646, Block: 383, Properties: 49},
}
