// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightBlock1 is the generated definition for minecraft:light_block_1.
var LightBlock1 = Block{
	Name:           "minecraft:light_block_1",
	TranslationKey: "tile.light_block.name",
}

var lightBlock1States = [...]State{
	{Hash: 3853027624, Block: 196, Properties: 452},
}
