// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightBlueConcretePowder is the generated definition for minecraft:light_blue_concrete_powder.
var LightBlueConcretePowder = Block{
	Name:           "minecraft:light_blue_concrete_powder",
	TranslationKey: "tile.concretePowder.lightBlue.name",
}

var lightBlueConcretePowderStates = [...]State{
	{Hash: 1850893626, Block: 12, Properties: 25},
}
