// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightBlueCandle is the generated definition for minecraft:light_blue_candle.
var LightBlueCandle = Block{
	Name:           "minecraft:light_blue_candle",
	TranslationKey: "tile.light_blue_candle.name",
}

var lightBlueCandleStates = [...]State{
	{Hash: 4067585498, Block: 532, Properties: 980},
	{Hash: 3306699029, Block: 532, Properties: 981},
	{Hash: 539768128, Block: 532, Properties: 982},
	{Hash: 2216341267, Block: 532, Properties: 983},
	{Hash: 827924773, Block: 532, Properties: 984},
	{Hash: 2251392458, Block: 532, Properties: 985},
	{Hash: 1595074699, Block: 532, Properties: 986},
	{Hash: 1161034696, Block: 532, Properties: 987},
}
