// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightBlock3 is the generated definition for minecraft:light_block_3.
var LightBlock3 = Block{
	Name:           "minecraft:light_block_3",
	TranslationKey: "tile.light_block.name",
}

var lightBlock3States = [...]State{
	{Hash: 459990998, Block: 194, Properties: 450},
}
