// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightBlock2 is the generated definition for minecraft:light_block_2.
var LightBlock2 = Block{
	Name:           "minecraft:light_block_2",
	TranslationKey: "tile.light_block.name",
}

var lightBlock2States = [...]State{
	{Hash: 922521491, Block: 195, Properties: 451},
}
