// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightGrayWool is the generated definition for minecraft:light_gray_wool.
var LightGrayWool = Block{
	Name:           "minecraft:light_gray_wool",
	TranslationKey: "tile.wool.silver.name",
}

var lightGrayWoolStates = [...]State{
	{Hash: 2164889994, Block: 1311, Properties: 1929},
}
