// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LightGrayStainedGlassPane is the generated definition for minecraft:light_gray_stained_glass_pane.
var LightGrayStainedGlassPane = Block{
	Name:           "minecraft:light_gray_stained_glass_pane",
	TranslationKey: "tile.stained_glass_pane.silver.name",
}

var lightGrayStainedGlassPaneStates = [...]State{
	{Hash: 1450826485, Block: 167, Properties: 49},
}
