// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LilyOfTheValley is the generated definition for minecraft:lily_of_the_valley.
var LilyOfTheValley = Block{
	Name:           "minecraft:lily_of_the_valley",
	TranslationKey: "tile.red_flower.lilyOfTheValley.name",
}

var lilyOfTheValleyStates = [...]State{
	{Hash: 2096774481, Block: 77, Properties: 121},
}
