// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LimeConcretePowder is the generated definition for minecraft:lime_concrete_powder.
var LimeConcretePowder = Block{
	Name:           "minecraft:lime_concrete_powder",
	TranslationKey: "tile.concretePowder.lime.name",
}

var limeConcretePowderStates = [...]State{
	{Hash: 3491229656, Block: 1302, Properties: 1922},
}
