// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LitPumpkin is the generated definition for minecraft:lit_pumpkin.
var LitPumpkin = Block{
	Name:           "minecraft:lit_pumpkin",
	TranslationKey: "tile.lit_pumpkin.name",
}

var litPumpkinStates = [...]State{
	{Hash: 3759459211, Block: 946, Properties: 1592},
	{Hash: 2460675104, Block: 946, Properties: 1592},
	{Hash: 909155985, Block: 946, Properties: 1592},
	{Hash: 107637426, Block: 946, Properties: 1592},
}
