// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// LitSmoker is the generated definition for minecraft:lit_smoker.
var LitSmoker = Block{
	Name:           "minecraft:lit_smoker",
	TranslationKey: "tile.lit_smoker.name",
}

var litSmokerStates = [...]State{
	{Hash: 2080399355, Block: 1256, Properties: 1718},
	{Hash: 859357296, Block: 1256, Properties: 1718},
	{Hash: 4033512929, Block: 1256, Properties: 1718},
	{Hash: 3231615138, Block: 1256, Properties: 1718},
}
