// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Lodestone is the generated definition for minecraft:lodestone.
var Lodestone = Block{
	Name:           "minecraft:lodestone",
	TranslationKey: "tile.lodestone.name",
}

var lodestoneStates = [...]State{
	{Hash: 2349326407, Block: 1340, Properties: 1987},
}
