// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// MagentaConcretePowder is the generated definition for minecraft:magenta_concrete_powder.
var MagentaConcretePowder = Block{
	Name:           "minecraft:magenta_concrete_powder",
	TranslationKey: "tile.concretePowder.magenta.name",
}

var magentaConcretePowderStates = [...]State{
	{Hash: 1135729023, Block: 512, Properties: 942},
}
