// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// MagentaGlazedTerracotta is the generated definition for minecraft:magenta_glazed_terracotta.
var MagentaGlazedTerracotta = Block{
	Name:           "minecraft:magenta_glazed_terracotta",
	TranslationKey: "tile.glazedTerracotta.magenta.name",
}

var magentaGlazedTerracottaStates = [...]State{
	{Hash: 802520842, Block: 265, Properties: 598},
	{Hash: 741046019, Block: 265, Properties: 598},
	{Hash: 925470488, Block: 265, Properties: 598},
	{Hash: 863995665, Block: 265, Properties: 598},
	{Hash: 556621550, Block: 265, Properties: 598},
	{Hash: 495146727, Block: 265, Properties: 598},
}
