// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// MagentaStainedGlassPane is the generated definition for minecraft:magenta_stained_glass_pane.
var MagentaStainedGlassPane = Block{
	Name:           "minecraft:magenta_stained_glass_pane",
	TranslationKey: "tile.stained_glass_pane.magenta.name",
}

var magentaStainedGlassPaneStates = [...]State{
	{Hash: 3968971605, Block: 590, Properties: 49},
}
