// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// MagentaShulkerBox is the generated definition for minecraft:magenta_shulker_box.
var MagentaShulkerBox = Block{
	Name:           "minecraft:magenta_shulker_box",
	TranslationKey: "tile.shulkerBoxMagenta.name",
}

var magentaShulkerBoxStates = [...]State{
	{Hash: 1407699698, Block: 106, Properties: 285},
}
