// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// MangroveTrapdoor is the generated definition for minecraft:mangrove_trapdoor.
var MangroveTrapdoor = Block{
	Name:           "minecraft:mangrove_trapdoor",
	TranslationKey: "tile.mangrove_trapdoor.name",
}

var mangroveTrapdoorStates = [...]State{
	{Hash: 3303432080, Block: 516, Properties: 953},
	{Hash: 44569359, Block: 516, Properties: 953},
	{Hash: 1803047842, Block: 516, Properties: 953},
	{Hash: 3984864385, Block: 516, Properties: 953},
	{Hash: 63771355, Block: 516, Properties: 954},
	{Hash: 3284230084, Block: 516, Properties: 954},
	{Hash: 2858354413, Block: 516, Properties: 954},
	{Hash: 2929557814, Block: 516, Properties: 954},
	{Hash: 2249137633, Block: 516, Properties: 955},
	{Hash: 3261997774, Block: 516, Properties: 956},
	{Hash: 3643543635, Block: 516, Properties: 957},
	{Hash: 1582284336, Block: 516, Properties: 958},
	{Hash: 1193831062, Block: 516, Properties: 955},
	{Hash: 22337049, Block: 516, Properties: 956},
	{Hash: 2588237064, Block: 516, Properties: 957},
	{Hash: 2637590907, Block: 516, Properties: 958},
}
