// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// MangroveWallSign is the generated definition for minecraft:mangrove_wall_sign.
var MangroveWallSign = Block{
	Name:           "minecraft:mangrove_wall_sign",
	TranslationKey: "tile.mangrove_wall_sign.name",
}

var mangroveWallSignStates = [...]State{
	{Hash: 1356487180, Block: 632, Properties: 1145},
	{Hash: 1295012357, Block: 632, Properties: 1145},
	{Hash: 1233537534, Block: 632, Properties: 1146},
	{Hash: 1172062711, Block: 632, Properties: 1147},
	{Hash: 1602386472, Block: 632, Properties: 1148},
	{Hash: 1540911649, Block: 632, Properties: 1149},
}
