// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// MangrovePressurePlate is the generated definition for minecraft:mangrove_pressure_plate.
var MangrovePressurePlate = Block{
	Name:           "minecraft:mangrove_pressure_plate",
	TranslationKey: "tile.mangrove_pressure_plate.name",
}

var mangrovePressurePlateStates = [...]State{
	{Hash: 3380807099, Block: 380, Properties: 792},
	{Hash: 3442281922, Block: 380, Properties: 793},
	{Hash: 3503756745, Block: 380, Properties: 793},
	{Hash: 3565231568, Block: 380, Properties: 793},
	{Hash: 3134907807, Block: 380, Properties: 793},
	{Hash: 3196382630, Block: 380, Properties: 793},
	{Hash: 3257857453, Block: 380, Properties: 793},
	{Hash: 3319332276, Block: 380, Properties: 793},
	{Hash: 2889008515, Block: 380, Properties: 793},
	{Hash: 2950483338, Block: 380, Properties: 793},
	{Hash: 3011958161, Block: 380, Properties: 793},
	{Hash: 3073432984, Block: 380, Properties: 793},
	{Hash: 2643109223, Block: 380, Properties: 793},
	{Hash: 2704584046, Block: 380, Properties: 793},
	{Hash: 2766058869, Block: 380, Properties: 793},
	{Hash: 2827533692, Block: 380, Properties: 793},
}
