// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// MossyStoneBrickDoubleSlab is the generated definition for minecraft:mossy_stone_brick_double_slab.
var MossyStoneBrickDoubleSlab = Block{
	Name:           "minecraft:mossy_stone_brick_double_slab",
	TranslationKey: "tile.double_stone_slab4.mossy_stone_brick.name",
}

var mossyStoneBrickDoubleSlabStates = [...]State{
	{Hash: 2568995581, Block: 444, Properties: 72},
	{Hash: 500378010, Block: 444, Properties: 72},
}
