// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// MushroomStem is the generated definition for minecraft:mushroom_stem.
var MushroomStem = Block{
	Name:           "minecraft:mushroom_stem",
	TranslationKey: "tile.brown_mushroom_block.stem.name",
}

var mushroomStemStates = [...]State{
	{Hash: 410422532, Block: 826, Properties: 1431},
	{Hash: 348947709, Block: 826, Properties: 1431},
	{Hash: 287472886, Block: 826, Properties: 1431},
	{Hash: 225998063, Block: 826, Properties: 1431},
	{Hash: 656321824, Block: 826, Properties: 1431},
	{Hash: 594847001, Block: 826, Properties: 1431},
	{Hash: 533372178, Block: 826, Properties: 1431},
	{Hash: 471897355, Block: 826, Properties: 1431},
	{Hash: 4213591244, Block: 826, Properties: 1431},
	{Hash: 4152116421, Block: 826, Properties: 1431},
	{Hash: 4090641598, Block: 826, Properties: 1431},
	{Hash: 4029166775, Block: 826, Properties: 1431},
	{Hash: 164523240, Block: 826, Properties: 1431},
	{Hash: 103048417, Block: 826, Properties: 1431},
	{Hash: 41573594, Block: 826, Properties: 1431},
	{Hash: 4275066067, Block: 826, Properties: 1431},
}
