// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// NetherWartBlock is the generated definition for minecraft:nether_wart_block.
var NetherWartBlock = Block{
	Name:           "minecraft:nether_wart_block",
	TranslationKey: "tile.nether_wart_block.name",
}

var netherWartBlockStates = [...]State{
	{Hash: 581531271, Block: 464, Properties: 867},
}
