// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// NetherBrick is the generated definition for minecraft:nether_brick.
var NetherBrick = Block{
	Name:           "minecraft:nether_brick",
	TranslationKey: "tile.nether_brick.name",
}

var netherBrickStates = [...]State{
	{Hash: 1523459785, Block: 1068, Properties: 123},
}
