// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// NetherBrickDoubleSlab is the generated definition for minecraft:nether_brick_double_slab.
var NetherBrickDoubleSlab = Block{
	Name:           "minecraft:nether_brick_double_slab",
	TranslationKey: "tile.double_stone_slab.nether_brick.name",
}

var netherBrickDoubleSlabStates = [...]State{
	{Hash: 445450925, Block: 838, Properties: 123},
	{Hash: 2931172714, Block: 838, Properties: 123},
}
