// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// NetherGoldOre is the generated definition for minecraft:nether_gold_ore.
var NetherGoldOre = Block{
	Name:           "minecraft:nether_gold_ore",
	TranslationKey: "tile.nether_gold_ore.name",
}

var netherGoldOreStates = [...]State{
	{Hash: 950287826, Block: 6, Properties: 13},
}
