// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// OakShelf is the generated definition for minecraft:oak_shelf.
var OakShelf = Block{
	Name:           "minecraft:oak_shelf",
	TranslationKey: "tile.oak_shelf.name",
}

var oakShelfStates = [...]State{
	{Hash: 3881061342, Block: 501, Properties: 923},
	{Hash: 3819586519, Block: 501, Properties: 923},
	{Hash: 4004010988, Block: 501, Properties: 923},
	{Hash: 3942536165, Block: 501, Properties: 923},
	{Hash: 3744103071, Block: 501, Properties: 923},
	{Hash: 3805577894, Block: 501, Properties: 923},
	{Hash: 3867052717, Block: 501, Properties: 923},
	{Hash: 3928527540, Block: 501, Properties: 923},
	{Hash: 659925133, Block: 501, Properties: 924},
	{Hash: 721399956, Block: 501, Properties: 924},
	{Hash: 536975487, Block: 501, Properties: 924},
	{Hash: 598450310, Block: 501, Properties: 924},
	{Hash: 3906457844, Block: 501, Properties: 924},
	{Hash: 3844983021, Block: 501, Properties: 924},
	{Hash: 3783508198, Block: 501, Properties: 924},
	{Hash: 3722033375, Block: 501, Properties: 924},
	{Hash: 4134778980, Block: 501, Properties: 925},
	{Hash: 4073304157, Block: 501, Properties: 925},
	{Hash: 4011829334, Block: 501, Properties: 925},
	{Hash: 3950354511, Block: 501, Properties: 925},
	{Hash: 3288533949, Block: 501, Properties: 925},
	{Hash: 3350008772, Block: 501, Properties: 925},
	{Hash: 3165584303, Block: 501, Properties: 925},
	{Hash: 3227059126, Block: 501, Properties: 925},
	{Hash: 698991879, Block: 501, Properties: 926},
	{Hash: 760466702, Block: 501, Properties: 926},
	{Hash: 821941525, Block: 501, Properties: 926},
	{Hash: 883416348, Block: 501, Properties: 926},
	{Hash: 752155366, Block: 501, Properties: 926},
	{Hash: 690680543, Block: 501, Properties: 926},
	{Hash: 875105012, Block: 501, Properties: 926},
	{Hash: 813630189, Block: 501, Properties: 926},
}
