// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// OakStairs is the generated definition for minecraft:oak_stairs.
var OakStairs = Block{
	Name:           "minecraft:oak_stairs",
	TranslationKey: "tile.oak_stairs.name",
}

var oakStairsStates = [...]State{
	{Hash: 3240922889, Block: 100, Properties: 268},
	{Hash: 3302397712, Block: 100, Properties: 269},
	{Hash: 3117973243, Block: 100, Properties: 270},
	{Hash: 3179448066, Block: 100, Properties: 271},
	{Hash: 1903002988, Block: 100, Properties: 272},
	{Hash: 1841528165, Block: 100, Properties: 273},
	{Hash: 1780053342, Block: 100, Properties: 274},
	{Hash: 1718578519, Block: 100, Properties: 275},
}
