// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// OxidizedDoubleCutCopperSlab is the generated definition for minecraft:oxidized_double_cut_copper_slab.
var OxidizedDoubleCutCopperSlab = Block{
	Name:           "minecraft:oxidized_double_cut_copper_slab",
	TranslationKey: "tile.oxidized_double_cut_copper_slab.name",
}

var oxidizedDoubleCutCopperSlabStates = [...]State{
	{Hash: 3502188017, Block: 171, Properties: 28},
	{Hash: 1893234246, Block: 171, Properties: 28},
}
