// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// OxidizedCutCopperStairs is the generated definition for minecraft:oxidized_cut_copper_stairs.
var OxidizedCutCopperStairs = Block{
	Name:           "minecraft:oxidized_cut_copper_stairs",
	TranslationKey: "tile.oxidized_cut_copper_stairs.name",
}

var oxidizedCutCopperStairsStates = [...]State{
	{Hash: 2646808729, Block: 134, Properties: 335},
	{Hash: 2708283552, Block: 134, Properties: 336},
	{Hash: 2523859083, Block: 134, Properties: 337},
	{Hash: 2585333906, Block: 134, Properties: 338},
	{Hash: 1380005180, Block: 134, Properties: 339},
	{Hash: 1318530357, Block: 134, Properties: 340},
	{Hash: 1257055534, Block: 134, Properties: 341},
	{Hash: 1195580711, Block: 134, Properties: 342},
}
