// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// OxidizedCopperChest is the generated definition for minecraft:oxidized_copper_chest.
var OxidizedCopperChest = Block{
	Name:           "minecraft:oxidized_copper_chest",
	TranslationKey: "tile.oxidized_copper_chest.name",
}

var oxidizedCopperChestStates = [...]State{
	{Hash: 1456752037, Block: 955, Properties: 824},
	{Hash: 4213074030, Block: 955, Properties: 824},
	{Hash: 2756911751, Block: 955, Properties: 824},
	{Hash: 3228715852, Block: 955, Properties: 824},
}
