// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// OxidizedCopperTrapdoor is the generated definition for minecraft:oxidized_copper_trapdoor.
var OxidizedCopperTrapdoor = Block{
	Name:           "minecraft:oxidized_copper_trapdoor",
	TranslationKey: "tile.oxidized_copper_trapdoor.name",
}

var oxidizedCopperTrapdoorStates = [...]State{
	{Hash: 2664456952, Block: 540, Properties: 683},
	{Hash: 1825356247, Block: 540, Properties: 683},
	{Hash: 3697047434, Block: 540, Properties: 683},
	{Hash: 3841547849, Block: 540, Properties: 683},
	{Hash: 3719763523, Block: 540, Properties: 684},
	{Hash: 770049676, Block: 540, Properties: 684},
	{Hash: 457386709, Block: 540, Properties: 684},
	{Hash: 2786241278, Block: 540, Properties: 684},
	{Hash: 1163398537, Block: 540, Properties: 685},
	{Hash: 1918532374, Block: 540, Properties: 686},
	{Hash: 3530871163, Block: 540, Properties: 687},
	{Hash: 4046042040, Block: 540, Properties: 688},
	{Hash: 108091966, Block: 540, Properties: 685},
	{Hash: 2973838945, Block: 540, Properties: 686},
	{Hash: 2475564592, Block: 540, Properties: 687},
	{Hash: 806381315, Block: 540, Properties: 688},
}
