// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PaleOakFence is the generated definition for minecraft:pale_oak_fence.
var PaleOakFence = Block{
	Name:           "minecraft:pale_oak_fence",
	TranslationKey: "tile.pale_oak_fence.name",
}

var paleOakFenceStates = [...]State{
	{Hash: 60668747, Block: 135, Properties: 343},
}
