// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PaleOakLeaves is the generated definition for minecraft:pale_oak_leaves.
var PaleOakLeaves = Block{
	Name:           "minecraft:pale_oak_leaves",
	TranslationKey: "tile.pale_oak_leaves.name",
}

var paleOakLeavesStates = [...]State{
	{Hash: 129912273, Block: 136, Properties: 344},
	{Hash: 3369572998, Block: 136, Properties: 344},
	{Hash: 1844557014, Block: 136, Properties: 344},
	{Hash: 2899863585, Block: 136, Properties: 344},
}
