// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PearlescentFroglight is the generated definition for minecraft:pearlescent_froglight.
var PearlescentFroglight = Block{
	Name:           "minecraft:pearlescent_froglight",
	TranslationKey: "tile.pearlescent_froglight.name",
}

var pearlescentFroglightStates = [...]State{
	{Hash: 1080727706, Block: 887, Properties: 1521},
	{Hash: 2136034277, Block: 887, Properties: 1521},
	{Hash: 25421135, Block: 887, Properties: 1521},
}
