// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Peony is the generated definition for minecraft:peony.
var Peony = Block{
	Name:           "minecraft:peony",
	TranslationKey: "tile.double_plant.paeonia.name",
}

var peonyStates = [...]State{
	{Hash: 1203451821, Block: 1284, Properties: 769},
	{Hash: 148145250, Block: 1284, Properties: 770},
}
