// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PetrifiedOakSlab is the generated definition for minecraft:petrified_oak_slab.
var PetrifiedOakSlab = Block{
	Name:           "minecraft:petrified_oak_slab",
	TranslationKey: "tile.stone_slab.wood.name",
}

var petrifiedOakSlabStates = [...]State{
	{Hash: 3479117989, Block: 1101, Properties: 1809},
	{Hash: 4532210, Block: 1101, Properties: 1810},
}
