// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PetrifiedOakDoubleSlab is the generated definition for minecraft:petrified_oak_double_slab.
var PetrifiedOakDoubleSlab = Block{
	Name:           "minecraft:petrified_oak_double_slab",
	TranslationKey: "tile.double_stone_slab.wood.name",
}

var petrifiedOakDoubleSlabStates = [...]State{
	{Hash: 456082508, Block: 645, Properties: 1166},
	{Hash: 2827107985, Block: 645, Properties: 1166},
}
