// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PinkWool is the generated definition for minecraft:pink_wool.
var PinkWool = Block{
	Name:           "minecraft:pink_wool",
	TranslationKey: "tile.wool.pink.name",
}

var pinkWoolStates = [...]State{
	{Hash: 2856014310, Block: 365, Properties: 774},
}
