// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PinkStainedGlassPane is the generated definition for minecraft:pink_stained_glass_pane.
var PinkStainedGlassPane = Block{
	Name:           "minecraft:pink_stained_glass_pane",
	TranslationKey: "tile.stained_glass_pane.pink.name",
}

var pinkStainedGlassPaneStates = [...]State{
	{Hash: 3346407201, Block: 1022, Properties: 49},
}
