// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PinkPetals is the generated definition for minecraft:pink_petals.
var PinkPetals = Block{
	Name:           "minecraft:pink_petals",
	TranslationKey: "tile.pink_petals.name",
}

var pinkPetalsStates = [...]State{
	{Hash: 450783541, Block: 561, Properties: 1013},
	{Hash: 1415956828, Block: 561, Properties: 1013},
	{Hash: 699455107, Block: 561, Properties: 1013},
	{Hash: 818376754, Block: 561, Properties: 1013},
	{Hash: 1491865641, Block: 561, Properties: 1013},
	{Hash: 1726044816, Block: 561, Properties: 1013},
	{Hash: 3818568743, Block: 561, Properties: 1013},
	{Hash: 869247990, Block: 561, Properties: 1013},
	{Hash: 18700638, Block: 561, Properties: 1013},
	{Hash: 3229988049, Block: 561, Properties: 1013},
	{Hash: 2939920904, Block: 561, Properties: 1013},
	{Hash: 3758277467, Block: 561, Properties: 1013},
	{Hash: 3233191786, Block: 561, Properties: 1013},
	{Hash: 1032255021, Block: 561, Properties: 1013},
	{Hash: 3436000356, Block: 561, Properties: 1013},
	{Hash: 2818614903, Block: 561, Properties: 1013},
	{Hash: 2435418039, Block: 561, Properties: 1013},
	{Hash: 3753069434, Block: 561, Properties: 1013},
	{Hash: 2851797881, Block: 561, Properties: 1013},
	{Hash: 4041134780, Block: 561, Properties: 1013},
	{Hash: 588489803, Block: 561, Properties: 1013},
	{Hash: 3900062686, Block: 561, Properties: 1013},
	{Hash: 842185773, Block: 561, Properties: 1013},
	{Hash: 517320816, Block: 561, Properties: 1013},
	{Hash: 3323439004, Block: 561, Properties: 1013},
	{Hash: 956892067, Block: 561, Properties: 1013},
	{Hash: 1106518074, Block: 561, Properties: 1013},
	{Hash: 173557257, Block: 561, Properties: 1013},
	{Hash: 1670900256, Block: 561, Properties: 1013},
	{Hash: 3319620359, Block: 561, Properties: 1013},
	{Hash: 998288638, Block: 561, Properties: 1013},
	{Hash: 15701117, Block: 561, Properties: 1013},
}
