// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PinkTulip is the generated definition for minecraft:pink_tulip.
var PinkTulip = Block{
	Name:           "minecraft:pink_tulip",
	TranslationKey: "tile.red_flower.tulipPink.name",
}

var pinkTulipStates = [...]State{
	{Hash: 2503948770, Block: 457, Properties: 121},
}
