// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PinkShulkerBox is the generated definition for minecraft:pink_shulker_box.
var PinkShulkerBox = Block{
	Name:           "minecraft:pink_shulker_box",
	TranslationKey: "tile.shulkerBoxPink.name",
}

var pinkShulkerBoxStates = [...]State{
	{Hash: 3815051278, Block: 495, Properties: 914},
}
