// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Podzol is the generated definition for minecraft:podzol.
var Podzol = Block{
	Name:           "minecraft:podzol",
	TranslationKey: "tile.podzol.name",
}

var podzolStates = [...]State{
	{Hash: 1711067891, Block: 565, Properties: 1025},
}
