// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PointedDripstone is the generated definition for minecraft:pointed_dripstone.
var PointedDripstone = Block{
	Name:           "minecraft:pointed_dripstone",
	TranslationKey: "tile.pointed_dripstone.name",
}

var pointedDripstoneStates = [...]State{
	{Hash: 604419874, Block: 1112, Properties: 278},
	{Hash: 3995324587, Block: 1112, Properties: 279},
	{Hash: 575507503, Block: 1112, Properties: 280},
	{Hash: 3693325889, Block: 1112, Properties: 281},
	{Hash: 3023418371, Block: 1112, Properties: 282},
	{Hash: 1659726445, Block: 1112, Properties: 283},
	{Hash: 2940018016, Block: 1112, Properties: 279},
	{Hash: 3815168228, Block: 1112, Properties: 280},
	{Hash: 2638019318, Block: 1112, Properties: 281},
	{Hash: 1968111800, Block: 1112, Properties: 282},
}
