// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PolishedDiorite is the generated definition for minecraft:polished_diorite.
var PolishedDiorite = Block{
	Name:           "minecraft:polished_diorite",
	TranslationKey: "tile.stone.dioriteSmooth.name",
}

var polishedDioriteStates = [...]State{
	{Hash: 1362605798, Block: 739, Properties: 98},
}
