// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PolishedDeepslateDoubleSlab is the generated definition for minecraft:polished_deepslate_double_slab.
var PolishedDeepslateDoubleSlab = Block{
	Name:           "minecraft:polished_deepslate_double_slab",
	TranslationKey: "tile.polished_deepslate_double_slab.name",
}

var polishedDeepslateDoubleSlabStates = [...]State{
	{Hash: 69762363, Block: 173, Properties: 345},
	{Hash: 3453460580, Block: 173, Properties: 345},
}
