// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PolishedGraniteStairs is the generated definition for minecraft:polished_granite_stairs.
var PolishedGraniteStairs = Block{
	Name:           "minecraft:polished_granite_stairs",
	TranslationKey: "tile.polished_granite_stairs.name",
}

var polishedGraniteStairsStates = [...]State{
	{Hash: 3693502770, Block: 402, Properties: 665},
	{Hash: 3632027947, Block: 402, Properties: 666},
	{Hash: 3816452416, Block: 402, Properties: 667},
	{Hash: 3754977593, Block: 402, Properties: 668},
	{Hash: 52142335, Block: 402, Properties: 669},
	{Hash: 113617158, Block: 402, Properties: 670},
	{Hash: 175091981, Block: 402, Properties: 671},
	{Hash: 236566804, Block: 402, Properties: 672},
}
