// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PolishedCinnabarDoubleSlab is the generated definition for minecraft:polished_cinnabar_double_slab.
var PolishedCinnabarDoubleSlab = Block{
	Name:           "minecraft:polished_cinnabar_double_slab",
	TranslationKey: "tile.polished_cinnabar_double_slab.name",
}

var polishedCinnabarDoubleSlabStates = [...]State{
	{Hash: 2192647885, Block: 526, Properties: 853},
	{Hash: 2676125450, Block: 526, Properties: 853},
}
