// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PolishedBlackstonePressurePlate is the generated definition for minecraft:polished_blackstone_pressure_plate.
var PolishedBlackstonePressurePlate = Block{
	Name:           "minecraft:polished_blackstone_pressure_plate",
	TranslationKey: "tile.polished_blackstone_pressure_plate.name",
}

var polishedBlackstonePressurePlateStates = [...]State{
	{Hash: 1903053274, Block: 851, Properties: 1485},
	{Hash: 1841578451, Block: 851, Properties: 1486},
	{Hash: 2026002920, Block: 851, Properties: 1486},
	{Hash: 1964528097, Block: 851, Properties: 1486},
	{Hash: 1657153982, Block: 851, Properties: 1486},
	{Hash: 1595679159, Block: 851, Properties: 1486},
	{Hash: 1780103628, Block: 851, Properties: 1486},
	{Hash: 1718628805, Block: 851, Properties: 1486},
	{Hash: 2394851858, Block: 851, Properties: 1486},
	{Hash: 2333377035, Block: 851, Properties: 1486},
	{Hash: 2517801504, Block: 851, Properties: 1486},
	{Hash: 2456326681, Block: 851, Properties: 1486},
	{Hash: 2148952566, Block: 851, Properties: 1486},
	{Hash: 2087477743, Block: 851, Properties: 1486},
	{Hash: 2271902212, Block: 851, Properties: 1486},
	{Hash: 2210427389, Block: 851, Properties: 1486},
}
