// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PolishedSulfurDoubleSlab is the generated definition for minecraft:polished_sulfur_double_slab.
var PolishedSulfurDoubleSlab = Block{
	Name:           "minecraft:polished_sulfur_double_slab",
	TranslationKey: "tile.polished_sulfur_double_slab.name",
}

var polishedSulfurDoubleSlabStates = [...]State{
	{Hash: 457464140, Block: 624, Properties: 142},
	{Hash: 2134859153, Block: 624, Properties: 142},
}
