// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PolishedCinnabarSlab is the generated definition for minecraft:polished_cinnabar_slab.
var PolishedCinnabarSlab = Block{
	Name:           "minecraft:polished_cinnabar_slab",
	TranslationKey: "tile.polished_cinnabar_slab.name",
}

var polishedCinnabarSlabStates = [...]State{
	{Hash: 2299791994, Block: 612, Properties: 1100},
	{Hash: 277188011, Block: 612, Properties: 1101},
}
