// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PolishedCinnabar is the generated definition for minecraft:polished_cinnabar.
var PolishedCinnabar = Block{
	Name:           "minecraft:polished_cinnabar",
	TranslationKey: "tile.polished_cinnabar.name",
}

var polishedCinnabarStates = [...]State{
	{Hash: 2854807857, Block: 1042, Properties: 853},
}
