// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PolishedDioriteStairs is the generated definition for minecraft:polished_diorite_stairs.
var PolishedDioriteStairs = Block{
	Name:           "minecraft:polished_diorite_stairs",
	TranslationKey: "tile.polished_diorite_stairs.name",
}

var polishedDioriteStairsStates = [...]State{
	{Hash: 2695028078, Block: 958, Properties: 927},
	{Hash: 2633553255, Block: 958, Properties: 928},
	{Hash: 2817977724, Block: 958, Properties: 929},
	{Hash: 2756502901, Block: 958, Properties: 930},
	{Hash: 982328139, Block: 958, Properties: 931},
	{Hash: 1043802962, Block: 958, Properties: 932},
	{Hash: 1105277785, Block: 958, Properties: 933},
	{Hash: 1166752608, Block: 958, Properties: 934},
}
