// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PrismarineDoubleSlab is the generated definition for minecraft:prismarine_double_slab.
var PrismarineDoubleSlab = Block{
	Name:           "minecraft:prismarine_double_slab",
	TranslationKey: "tile.double_stone_slab2.prismarine.rough.name",
}

var prismarineDoubleSlabStates = [...]State{
	{Hash: 1557979639, Block: 466, Properties: 870},
	{Hash: 1811717960, Block: 466, Properties: 870},
}
