// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// PurpurSlab is the generated definition for minecraft:purpur_slab.
var PurpurSlab = Block{
	Name:           "minecraft:purpur_slab",
	TranslationKey: "tile.stone_slab2.purpur.name",
}

var purpurSlabStates = [...]State{
	{Hash: 3860482118, Block: 211, Properties: 479},
	{Hash: 2355684303, Block: 211, Properties: 480},
}
