// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// QuartzStairs is the generated definition for minecraft:quartz_stairs.
var QuartzStairs = Block{
	Name:           "minecraft:quartz_stairs",
	TranslationKey: "tile.quartz_stairs.name",
}

var quartzStairsStates = [...]State{
	{Hash: 2067288422, Block: 588, Properties: 1061},
	{Hash: 2005813599, Block: 588, Properties: 1062},
	{Hash: 2190238068, Block: 588, Properties: 1063},
	{Hash: 2128763245, Block: 588, Properties: 1064},
	{Hash: 227322691, Block: 588, Properties: 1065},
	{Hash: 288797514, Block: 588, Properties: 1066},
	{Hash: 350272337, Block: 588, Properties: 1067},
	{Hash: 411747160, Block: 588, Properties: 1068},
}
