// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// RawIronBlock is the generated definition for minecraft:raw_iron_block.
var RawIronBlock = Block{
	Name:           "minecraft:raw_iron_block",
	TranslationKey: "tile.raw_iron_block.name",
}

var rawIronBlockStates = [...]State{
	{Hash: 1077242782, Block: 1343, Properties: 1988},
}
