// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// RedNetherBrickSlab is the generated definition for minecraft:red_nether_brick_slab.
var RedNetherBrickSlab = Block{
	Name:           "minecraft:red_nether_brick_slab",
	TranslationKey: "tile.stone_slab2.red_nether_brick.name",
}

var redNetherBrickSlabStates = [...]State{
	{Hash: 1891256390, Block: 927, Properties: 1413},
	{Hash: 3897091023, Block: 927, Properties: 1414},
}
