// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// RedCandleCake is the generated definition for minecraft:red_candle_cake.
var RedCandleCake = Block{
	Name:           "minecraft:red_candle_cake",
	TranslationKey: "tile.red_candle_cake.name",
}

var redCandleCakeStates = [...]State{
	{Hash: 2252729289, Block: 1261, Properties: 103},
	{Hash: 1197422718, Block: 1261, Properties: 104},
}
