// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// RedMushroomBlock is the generated definition for minecraft:red_mushroom_block.
var RedMushroomBlock = Block{
	Name:           "minecraft:red_mushroom_block",
	TranslationKey: "tile.red_mushroom_block.name",
}

var redMushroomBlockStates = [...]State{
	{Hash: 3010818241, Block: 315, Properties: 706},
	{Hash: 3072293064, Block: 315, Properties: 706},
	{Hash: 2887868595, Block: 315, Properties: 706},
	{Hash: 2949343418, Block: 315, Properties: 706},
	{Hash: 2764918949, Block: 315, Properties: 706},
	{Hash: 2826393772, Block: 315, Properties: 706},
	{Hash: 2641969303, Block: 315, Properties: 706},
	{Hash: 2703444126, Block: 315, Properties: 706},
	{Hash: 3502616825, Block: 315, Properties: 706},
	{Hash: 3564091648, Block: 315, Properties: 706},
	{Hash: 3379667179, Block: 315, Properties: 706},
	{Hash: 3441142002, Block: 315, Properties: 706},
	{Hash: 3256717533, Block: 315, Properties: 706},
	{Hash: 3318192356, Block: 315, Properties: 706},
	{Hash: 3133767887, Block: 315, Properties: 706},
	{Hash: 3195242710, Block: 315, Properties: 706},
}
