// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// RedstoneLamp is the generated definition for minecraft:redstone_lamp.
var RedstoneLamp = Block{
	Name:           "minecraft:redstone_lamp",
	TranslationKey: "tile.redstone_lamp.name",
}

var redstoneLampStates = [...]State{
	{Hash: 670839919, Block: 86, Properties: 233},
}
