// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// ReinforcedDeepslate is the generated definition for minecraft:reinforced_deepslate.
var ReinforcedDeepslate = Block{
	Name:           "minecraft:reinforced_deepslate",
	TranslationKey: "tile.reinforced_deepslate.name",
}

var reinforcedDeepslateStates = [...]State{
	{Hash: 1769900828, Block: 740, Properties: 1321},
}
