// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// ResinBrickSlab is the generated definition for minecraft:resin_brick_slab.
var ResinBrickSlab = Block{
	Name:           "minecraft:resin_brick_slab",
	TranslationKey: "tile.resin_brick_slab.name",
}

var resinBrickSlabStates = [...]State{
	{Hash: 45026994, Block: 1086, Properties: 1787},
	{Hash: 592893587, Block: 1086, Properties: 1788},
}
