// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// ResinBrickStairs is the generated definition for minecraft:resin_brick_stairs.
var ResinBrickStairs = Block{
	Name:           "minecraft:resin_brick_stairs",
	TranslationKey: "tile.resin_brick_stairs.name",
}

var resinBrickStairsStates = [...]State{
	{Hash: 234418979, Block: 828, Properties: 1433},
	{Hash: 295893802, Block: 828, Properties: 1434},
	{Hash: 357368625, Block: 828, Properties: 1435},
	{Hash: 418843448, Block: 828, Properties: 1436},
	{Hash: 2249507270, Block: 828, Properties: 1437},
	{Hash: 2188032447, Block: 828, Properties: 1438},
	{Hash: 2372456916, Block: 828, Properties: 1439},
	{Hash: 2310982093, Block: 828, Properties: 1440},
}
