// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// RespawnAnchor is the generated definition for minecraft:respawn_anchor.
var RespawnAnchor = Block{
	Name:           "minecraft:respawn_anchor",
	TranslationKey: "tile.respawn_anchor.name",
}

var respawnAnchorStates = [...]State{
	{Hash: 1763447706, Block: 217, Properties: 483},
	{Hash: 1701972883, Block: 217, Properties: 484},
	{Hash: 1886397352, Block: 217, Properties: 485},
	{Hash: 1824922529, Block: 217, Properties: 486},
	{Hash: 1517548414, Block: 217, Properties: 487},
}
