// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SandstoneStairs is the generated definition for minecraft:sandstone_stairs.
var SandstoneStairs = Block{
	Name:           "minecraft:sandstone_stairs",
	TranslationKey: "tile.sandstone_stairs.name",
}

var sandstoneStairsStates = [...]State{
	{Hash: 4174249877, Block: 312, Properties: 698},
	{Hash: 4235724700, Block: 312, Properties: 699},
	{Hash: 4051300231, Block: 312, Properties: 700},
	{Hash: 4112775054, Block: 312, Properties: 701},
	{Hash: 2101721944, Block: 312, Properties: 702},
	{Hash: 2040247121, Block: 312, Properties: 703},
	{Hash: 1978772298, Block: 312, Properties: 704},
	{Hash: 1917297475, Block: 312, Properties: 705},
}
