// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SandstoneSlab is the generated definition for minecraft:sandstone_slab.
var SandstoneSlab = Block{
	Name:           "minecraft:sandstone_slab",
	TranslationKey: "tile.stone_slab.sand.name",
}

var sandstoneSlabStates = [...]State{
	{Hash: 2601975572, Block: 138, Properties: 346},
	{Hash: 2907657641, Block: 138, Properties: 347},
}
