// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SandstoneDoubleSlab is the generated definition for minecraft:sandstone_double_slab.
var SandstoneDoubleSlab = Block{
	Name:           "minecraft:sandstone_double_slab",
	TranslationKey: "tile.double_stone_slab.sand.name",
}

var sandstoneDoubleSlabStates = [...]State{
	{Hash: 2367678067, Block: 154, Properties: 151},
	{Hash: 426355436, Block: 154, Properties: 151},
}
