// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Scaffolding is the generated definition for minecraft:scaffolding.
var Scaffolding = Block{
	Name:           "minecraft:scaffolding",
	TranslationKey: "tile.scaffolding.name",
}

var scaffoldingStates = [...]State{
	{Hash: 2498125071, Block: 311, Properties: 697},
	{Hash: 3119082376, Block: 311, Properties: 697},
	{Hash: 3389478825, Block: 311, Properties: 697},
	{Hash: 1006940914, Block: 311, Properties: 697},
	{Hash: 1186940507, Block: 311, Properties: 697},
	{Hash: 2248292420, Block: 311, Properties: 697},
	{Hash: 1681806037, Block: 311, Properties: 697},
	{Hash: 1384186846, Block: 311, Properties: 697},
	{Hash: 1442818500, Block: 311, Properties: 697},
	{Hash: 4174388947, Block: 311, Properties: 697},
	{Hash: 2334172254, Block: 311, Properties: 697},
	{Hash: 2062247485, Block: 311, Properties: 697},
	{Hash: 131633936, Block: 311, Properties: 697},
	{Hash: 3303598991, Block: 311, Properties: 697},
	{Hash: 626499466, Block: 311, Properties: 697},
	{Hash: 2439493417, Block: 311, Properties: 697},
}
