// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SmallAmethystBud is the generated definition for minecraft:small_amethyst_bud.
var SmallAmethystBud = Block{
	Name:           "minecraft:small_amethyst_bud",
	TranslationKey: "tile.small_amethyst_bud.name",
}

var smallAmethystBudStates = [...]State{
	{Hash: 4100747486, Block: 123, Properties: 306},
	{Hash: 3032920933, Block: 123, Properties: 307},
	{Hash: 2290012126, Block: 123, Properties: 308},
	{Hash: 115994256, Block: 123, Properties: 309},
	{Hash: 2584252973, Block: 123, Properties: 310},
	{Hash: 576651015, Block: 123, Properties: 311},
}
