// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SmoothStone is the generated definition for minecraft:smooth_stone.
var SmoothStone = Block{
	Name:           "minecraft:smooth_stone",
	TranslationKey: "tile.smooth_stone.name",
}

var smoothStoneStates = [...]State{
	{Hash: 555751865, Block: 537, Properties: 234},
}
