// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SmoothStoneSlab is the generated definition for minecraft:smooth_stone_slab.
var SmoothStoneSlab = Block{
	Name:           "minecraft:smooth_stone_slab",
	TranslationKey: "tile.stone_slab.stone.name",
}

var smoothStoneSlabStates = [...]State{
	{Hash: 98367658, Block: 1139, Properties: 829},
	{Hash: 3884087355, Block: 1139, Properties: 830},
}
