// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SmoothRedSandstoneStairs is the generated definition for minecraft:smooth_red_sandstone_stairs.
var SmoothRedSandstoneStairs = Block{
	Name:           "minecraft:smooth_red_sandstone_stairs",
	TranslationKey: "tile.smooth_red_sandstone_stairs.name",
}

var smoothRedSandstoneStairsStates = [...]State{
	{Hash: 1060425153, Block: 686, Properties: 1245},
	{Hash: 1121899976, Block: 686, Properties: 1246},
	{Hash: 937475507, Block: 686, Properties: 1247},
	{Hash: 998950330, Block: 686, Properties: 1248},
	{Hash: 2494045220, Block: 686, Properties: 1249},
	{Hash: 2432570397, Block: 686, Properties: 1250},
	{Hash: 2371095574, Block: 686, Properties: 1251},
	{Hash: 2309620751, Block: 686, Properties: 1252},
}
