// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SmoothBasalt is the generated definition for minecraft:smooth_basalt.
var SmoothBasalt = Block{
	Name:           "minecraft:smooth_basalt",
	TranslationKey: "tile.smooth_basalt.name",
}

var smoothBasaltStates = [...]State{
	{Hash: 368734180, Block: 271, Properties: 12},
}
