// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SoulLantern is the generated definition for minecraft:soul_lantern.
var SoulLantern = Block{
	Name:           "minecraft:soul_lantern",
	TranslationKey: "tile.soul_lantern.name",
}

var soulLanternStates = [...]State{
	{Hash: 3342854247, Block: 726, Properties: 1287},
	{Hash: 2287547676, Block: 726, Properties: 1288},
}
