// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SoulCampfire is the generated definition for minecraft:soul_campfire.
var SoulCampfire = Block{
	Name:           "minecraft:soul_campfire",
	TranslationKey: "tile.soul_campfire.name",
}

var soulCampfireStates = [...]State{
	{Hash: 1167306394, Block: 1312, Properties: 1930},
	{Hash: 1825062515, Block: 1312, Properties: 1930},
	{Hash: 2286863764, Block: 1312, Properties: 1930},
	{Hash: 227648673, Block: 1312, Properties: 1930},
	{Hash: 366306909, Block: 1312, Properties: 1294},
	{Hash: 3751330998, Block: 1312, Properties: 1294},
	{Hash: 251829039, Block: 1312, Properties: 1294},
	{Hash: 653876244, Block: 1312, Properties: 1294},
}
