// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SoulFire is the generated definition for minecraft:soul_fire.
var SoulFire = Block{
	Name:           "minecraft:soul_fire",
	TranslationKey: "tile.soul_fire.name",
}

var soulFireStates = [...]State{
	{Hash: 4018844187, Block: 161, Properties: 389},
	{Hash: 4080319010, Block: 161, Properties: 389},
	{Hash: 4141793833, Block: 161, Properties: 389},
	{Hash: 4203268656, Block: 161, Properties: 389},
	{Hash: 3772944895, Block: 161, Properties: 389},
	{Hash: 3834419718, Block: 161, Properties: 389},
	{Hash: 3895894541, Block: 161, Properties: 389},
	{Hash: 3957369364, Block: 161, Properties: 389},
	{Hash: 3527045603, Block: 161, Properties: 389},
	{Hash: 3588520426, Block: 161, Properties: 389},
	{Hash: 3649995249, Block: 161, Properties: 389},
	{Hash: 3711470072, Block: 161, Properties: 389},
	{Hash: 3281146311, Block: 161, Properties: 389},
	{Hash: 3342621134, Block: 161, Properties: 389},
	{Hash: 3404095957, Block: 161, Properties: 389},
	{Hash: 3465570780, Block: 161, Properties: 389},
}
