// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SpruceSapling is the generated definition for minecraft:spruce_sapling.
var SpruceSapling = Block{
	Name:           "minecraft:spruce_sapling",
	TranslationKey: "tile.sapling.spruce.name",
}

var spruceSaplingStates = [...]State{
	{Hash: 1772161361, Block: 428, Properties: 370},
	{Hash: 716854790, Block: 428, Properties: 370},
}
