// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SpruceStairs is the generated definition for minecraft:spruce_stairs.
var SpruceStairs = Block{
	Name:           "minecraft:spruce_stairs",
	TranslationKey: "tile.spruce_stairs.name",
}

var spruceStairsStates = [...]State{
	{Hash: 925629167, Block: 32, Properties: 85},
	{Hash: 987103990, Block: 32, Properties: 86},
	{Hash: 1048578813, Block: 32, Properties: 87},
	{Hash: 1110053636, Block: 32, Properties: 88},
	{Hash: 1720244322, Block: 32, Properties: 89},
	{Hash: 1658769499, Block: 32, Properties: 90},
	{Hash: 1843193968, Block: 32, Properties: 91},
	{Hash: 1781719145, Block: 32, Properties: 92},
}
