// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// StandingSign is the generated definition for minecraft:standing_sign.
var StandingSign = Block{
	Name:           "minecraft:standing_sign",
	TranslationKey: "tile.standing_sign.name",
}

var standingSignStates = [...]State{
	{Hash: 3253555881, Block: 715, Properties: 1269},
	{Hash: 3315030704, Block: 715, Properties: 1269},
	{Hash: 3130606235, Block: 715, Properties: 1269},
	{Hash: 3192081058, Block: 715, Properties: 1269},
	{Hash: 3007656589, Block: 715, Properties: 1269},
	{Hash: 3069131412, Block: 715, Properties: 1269},
	{Hash: 2884706943, Block: 715, Properties: 1269},
	{Hash: 2946181766, Block: 715, Properties: 1269},
	{Hash: 2761757297, Block: 715, Properties: 1269},
	{Hash: 2823232120, Block: 715, Properties: 1269},
	{Hash: 2638807651, Block: 715, Properties: 1269},
	{Hash: 2700282474, Block: 715, Properties: 1269},
	{Hash: 2515858005, Block: 715, Properties: 1269},
	{Hash: 2577332828, Block: 715, Properties: 1269},
	{Hash: 2392908359, Block: 715, Properties: 1269},
	{Hash: 2454383182, Block: 715, Properties: 1269},
}
