// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// StonePressurePlate is the generated definition for minecraft:stone_pressure_plate.
var StonePressurePlate = Block{
	Name:           "minecraft:stone_pressure_plate",
	TranslationKey: "tile.stone_pressure_plate.name",
}

var stonePressurePlateStates = [...]State{
	{Hash: 3248307340, Block: 385, Properties: 800},
	{Hash: 3186832517, Block: 385, Properties: 801},
	{Hash: 3125357694, Block: 385, Properties: 801},
	{Hash: 3063882871, Block: 385, Properties: 801},
	{Hash: 3494206632, Block: 385, Properties: 801},
	{Hash: 3432731809, Block: 385, Properties: 801},
	{Hash: 3371256986, Block: 385, Properties: 801},
	{Hash: 3309782163, Block: 385, Properties: 801},
	{Hash: 3740105924, Block: 385, Properties: 801},
	{Hash: 3678631101, Block: 385, Properties: 801},
	{Hash: 3617156278, Block: 385, Properties: 801},
	{Hash: 3555681455, Block: 385, Properties: 801},
	{Hash: 3986005216, Block: 385, Properties: 801},
	{Hash: 3924530393, Block: 385, Properties: 801},
	{Hash: 3863055570, Block: 385, Properties: 801},
	{Hash: 3801580747, Block: 385, Properties: 801},
}
