// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// StrippedSpruceWood is the generated definition for minecraft:stripped_spruce_wood.
var StrippedSpruceWood = Block{
	Name:           "minecraft:stripped_spruce_wood",
	TranslationKey: "tile.wood.stripped.spruce.name",
}

var strippedSpruceWoodStates = [...]State{
	{Hash: 1957875066, Block: 213, Properties: 216},
	{Hash: 3013181637, Block: 213, Properties: 216},
	{Hash: 902568495, Block: 213, Properties: 216},
}
