// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// StrippedAcaciaLog is the generated definition for minecraft:stripped_acacia_log.
var StrippedAcaciaLog = Block{
	Name:           "minecraft:stripped_acacia_log",
	TranslationKey: "tile.stripped_acacia_log.name",
}

var strippedAcaciaLogStates = [...]State{
	{Hash: 1367858272, Block: 752, Properties: 891},
	{Hash: 2423164843, Block: 752, Properties: 891},
	{Hash: 238810689, Block: 752, Properties: 891},
}
