// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// StrippedDarkOakLog is the generated definition for minecraft:stripped_dark_oak_log.
var StrippedDarkOakLog = Block{
	Name:           "minecraft:stripped_dark_oak_log",
	TranslationKey: "tile.stripped_dark_oak_log.name",
}

var strippedDarkOakLogStates = [...]State{
	{Hash: 1920611122, Block: 66, Properties: 10},
	{Hash: 2975917693, Block: 66, Properties: 10},
	{Hash: 865304551, Block: 66, Properties: 10},
}
