// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// StrippedJungleWood is the generated definition for minecraft:stripped_jungle_wood.
var StrippedJungleWood = Block{
	Name:           "minecraft:stripped_jungle_wood",
	TranslationKey: "tile.wood.stripped.jungle.name",
}

var strippedJungleWoodStates = [...]State{
	{Hash: 490498551, Block: 130, Properties: 215},
	{Hash: 3730159276, Block: 130, Properties: 215},
	{Hash: 1545805122, Block: 130, Properties: 215},
}
