// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// StrippedMangroveWood is the generated definition for minecraft:stripped_mangrove_wood.
var StrippedMangroveWood = Block{
	Name:           "minecraft:stripped_mangrove_wood",
	TranslationKey: "tile.stripped_mangrove_wood.name",
}

var strippedMangroveWoodStates = [...]State{
	{Hash: 1014956299, Block: 434, Properties: 821},
	{Hash: 4254617024, Block: 434, Properties: 821},
	{Hash: 2070262870, Block: 434, Properties: 821},
}
