// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// StrippedCrimsonHyphae is the generated definition for minecraft:stripped_crimson_hyphae.
var StrippedCrimsonHyphae = Block{
	Name:           "minecraft:stripped_crimson_hyphae",
	TranslationKey: "tile.stripped_crimson_hyphae.name",
}

var strippedCrimsonHyphaeStates = [...]State{
	{Hash: 1851001188, Block: 908, Properties: 872},
	{Hash: 2906307759, Block: 908, Properties: 872},
	{Hash: 721953605, Block: 908, Properties: 872},
}
