// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// SuspiciousGravel is the generated definition for minecraft:suspicious_gravel.
var SuspiciousGravel = Block{
	Name:           "minecraft:suspicious_gravel",
	TranslationKey: "tile.suspicious_gravel.name",
}

var suspiciousGravelStates = [...]State{
	{Hash: 1055929607, Block: 582, Properties: 1052},
	{Hash: 623036, Block: 582, Properties: 1052},
	{Hash: 2137681700, Block: 582, Properties: 1052},
	{Hash: 3192988271, Block: 582, Properties: 1052},
	{Hash: 2124375457, Block: 582, Properties: 1052},
	{Hash: 1069068886, Block: 582, Properties: 1052},
	{Hash: 826109438, Block: 582, Properties: 1052},
	{Hash: 1881416009, Block: 582, Properties: 1052},
}
