// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Target is the generated definition for minecraft:target.
var Target = Block{
	Name:           "minecraft:target",
	TranslationKey: "tile.target.name",
}

var targetStates = [...]State{
	{Hash: 3452856560, Block: 881, Properties: 1077},
}
