// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Tnt is the generated definition for minecraft:tnt.
var Tnt = Block{
	Name:           "minecraft:tnt",
	TranslationKey: "tile.tnt.name",
}

var tntStates = [...]State{
	{Hash: 622850821, Block: 951, Properties: 543},
	{Hash: 3862511546, Block: 951, Properties: 543},
}
