// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// Torch is the generated definition for minecraft:torch.
var Torch = Block{
	Name:           "minecraft:torch",
	TranslationKey: "tile.torch.name",
}

var torchStates = [...]State{
	{Hash: 3106938104, Block: 236, Properties: 519},
	{Hash: 3604393666, Block: 236, Properties: 520},
	{Hash: 1452174040, Block: 236, Properties: 521},
	{Hash: 501794947, Block: 236, Properties: 522},
	{Hash: 908039153, Block: 236, Properties: 523},
	{Hash: 4090812401, Block: 236, Properties: 519},
}
