// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// TrialSpawner is the generated definition for minecraft:trial_spawner.
var TrialSpawner = Block{
	Name:           "minecraft:trial_spawner",
	TranslationKey: "tile.trial_spawner.name",
}

var trialSpawnerStates = [...]State{
	{Hash: 3330348502, Block: 1323, Properties: 1953},
	{Hash: 3268873679, Block: 1323, Properties: 1954},
	{Hash: 3453298148, Block: 1323, Properties: 1955},
	{Hash: 3391823325, Block: 1323, Properties: 1955},
	{Hash: 3576247794, Block: 1323, Properties: 1955},
	{Hash: 3514772971, Block: 1323, Properties: 1953},
	{Hash: 1946252613, Block: 1323, Properties: 1953},
	{Hash: 2007727436, Block: 1323, Properties: 1954},
	{Hash: 1823302967, Block: 1323, Properties: 1955},
	{Hash: 1884777790, Block: 1323, Properties: 1955},
	{Hash: 2192151905, Block: 1323, Properties: 1955},
	{Hash: 2253626728, Block: 1323, Properties: 1953},
}
