// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// TubeCoralFan is the generated definition for minecraft:tube_coral_fan.
var TubeCoralFan = Block{
	Name:           "minecraft:tube_coral_fan",
	TranslationKey: "tile.coral_fan.blue_fan.name",
}

var tubeCoralFanStates = [...]State{
	{Hash: 1658024058, Block: 84, Properties: 214},
	{Hash: 1596549235, Block: 84, Properties: 214},
}
