// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// TuffBrickSlab is the generated definition for minecraft:tuff_brick_slab.
var TuffBrickSlab = Block{
	Name:           "minecraft:tuff_brick_slab",
	TranslationKey: "tile.tuff_brick_slab.name",
}

var tuffBrickSlabStates = [...]State{
	{Hash: 390504169, Block: 353, Properties: 105},
	{Hash: 3789318030, Block: 353, Properties: 106},
}
