// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// TuffSlab is the generated definition for minecraft:tuff_slab.
var TuffSlab = Block{
	Name:           "minecraft:tuff_slab",
	TranslationKey: "tile.tuff_slab.name",
}

var tuffSlabStates = [...]State{
	{Hash: 3192937949, Block: 93, Properties: 105},
	{Hash: 998569210, Block: 93, Properties: 106},
}
