// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// TurtleEgg is the generated definition for minecraft:turtle_egg.
var TurtleEgg = Block{
	Name:           "minecraft:turtle_egg",
	TranslationKey: "tile.turtle_egg.name",
}

var turtleEggStates = [...]State{
	{Hash: 567624840, Block: 1303, Properties: 1923},
	{Hash: 4084258994, Block: 1303, Properties: 1923},
	{Hash: 461839134, Block: 1303, Properties: 1923},
	{Hash: 2309516875, Block: 1303, Properties: 1923},
	{Hash: 4278963058, Block: 1303, Properties: 1923},
	{Hash: 2131145668, Block: 1303, Properties: 1923},
	{Hash: 456401608, Block: 1303, Properties: 1923},
	{Hash: 525642025, Block: 1303, Properties: 1923},
	{Hash: 2262330951, Block: 1303, Properties: 1923},
	{Hash: 2938013925, Block: 1303, Properties: 1923},
	{Hash: 2327160413, Block: 1303, Properties: 1923},
	{Hash: 3059255034, Block: 1303, Properties: 1923},
}
