// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// UnderwaterTorch is the generated definition for minecraft:underwater_torch.
var UnderwaterTorch = Block{
	Name:           "minecraft:underwater_torch",
	TranslationKey: "tile.underwater_torch.name",
}

var underwaterTorchStates = [...]State{
	{Hash: 3816711773, Block: 284, Properties: 645},
	{Hash: 2995373697, Block: 284, Properties: 646},
	{Hash: 410179955, Block: 284, Properties: 647},
	{Hash: 3794757418, Block: 284, Properties: 648},
	{Hash: 1938573548, Block: 284, Properties: 649},
	{Hash: 2838823732, Block: 284, Properties: 645},
}
