// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// UnpoweredRepeater is the generated definition for minecraft:unpowered_repeater.
var UnpoweredRepeater = Block{
	Name:           "minecraft:unpowered_repeater",
	TranslationKey: "tile.unpowered_repeater.name",
}

var unpoweredRepeaterStates = [...]State{
	{Hash: 669018815, Block: 684, Properties: 362},
	{Hash: 4067202120, Block: 684, Properties: 362},
	{Hash: 1771579365, Block: 684, Properties: 362},
	{Hash: 1251242258, Block: 684, Properties: 362},
	{Hash: 730493638, Block: 684, Properties: 362},
	{Hash: 4005727297, Block: 684, Properties: 362},
	{Hash: 1833054188, Block: 684, Properties: 362},
	{Hash: 1189767435, Block: 684, Properties: 362},
	{Hash: 791968461, Block: 684, Properties: 362},
	{Hash: 3944252474, Block: 684, Properties: 362},
	{Hash: 1648629719, Block: 684, Properties: 362},
	{Hash: 1374191904, Block: 684, Properties: 362},
	{Hash: 853443284, Block: 684, Properties: 362},
	{Hash: 3882777651, Block: 684, Properties: 362},
	{Hash: 1710104542, Block: 684, Properties: 362},
	{Hash: 1312717081, Block: 684, Properties: 362},
}
