// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WarpedStairs is the generated definition for minecraft:warped_stairs.
var WarpedStairs = Block{
	Name:           "minecraft:warped_stairs",
	TranslationKey: "tile.warped_stairs.name",
}

var warpedStairsStates = [...]State{
	{Hash: 1804931902, Block: 347, Properties: 751},
	{Hash: 1743457079, Block: 347, Properties: 752},
	{Hash: 1927881548, Block: 347, Properties: 753},
	{Hash: 1866406725, Block: 347, Properties: 754},
	{Hash: 4002847451, Block: 347, Properties: 755},
	{Hash: 4064322274, Block: 347, Properties: 756},
	{Hash: 4125797097, Block: 347, Properties: 757},
	{Hash: 4187271920, Block: 347, Properties: 758},
}
