// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WarpedHyphae is the generated definition for minecraft:warped_hyphae.
var WarpedHyphae = Block{
	Name:           "minecraft:warped_hyphae",
	TranslationKey: "tile.warped_hyphae.name",
}

var warpedHyphaeStates = [...]State{
	{Hash: 16963668, Block: 771, Properties: 1259},
	{Hash: 1072270239, Block: 771, Properties: 1259},
	{Hash: 3182883381, Block: 771, Properties: 1259},
}
