// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WaxedLightningRod is the generated definition for minecraft:waxed_lightning_rod.
var WaxedLightningRod = Block{
	Name:           "minecraft:waxed_lightning_rod",
	TranslationKey: "tile.waxed_lightning_rod.name",
}

var waxedLightningRodStates = [...]State{
	{Hash: 1910125425, Block: 319, Properties: 290},
	{Hash: 946623014, Block: 319, Properties: 290},
	{Hash: 3120776259, Block: 319, Properties: 291},
	{Hash: 1592340992, Block: 319, Properties: 291},
	{Hash: 588506485, Block: 319, Properties: 292},
	{Hash: 3936612602, Block: 319, Properties: 292},
	{Hash: 854818854, Block: 319, Properties: 290},
	{Hash: 2001929585, Block: 319, Properties: 290},
	{Hash: 2065469688, Block: 319, Properties: 291},
	{Hash: 2647647563, Block: 319, Properties: 291},
	{Hash: 3828167210, Block: 319, Properties: 292},
	{Hash: 696951877, Block: 319, Properties: 292},
}
