// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WaxedCutCopperStairs is the generated definition for minecraft:waxed_cut_copper_stairs.
var WaxedCutCopperStairs = Block{
	Name:           "minecraft:waxed_cut_copper_stairs",
	TranslationKey: "tile.waxed_cut_copper_stairs.name",
}

var waxedCutCopperStairsStates = [...]State{
	{Hash: 2829617817, Block: 155, Properties: 373},
	{Hash: 2891092640, Block: 155, Properties: 374},
	{Hash: 2706668171, Block: 155, Properties: 375},
	{Hash: 2768142994, Block: 155, Properties: 376},
	{Hash: 1562814268, Block: 155, Properties: 377},
	{Hash: 1501339445, Block: 155, Properties: 378},
	{Hash: 1439864622, Block: 155, Properties: 379},
	{Hash: 1378389799, Block: 155, Properties: 380},
}
