// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WaxedWeatheredCopperBars is the generated definition for minecraft:waxed_weathered_copper_bars.
var WaxedWeatheredCopperBars = Block{
	Name:           "minecraft:waxed_weathered_copper_bars",
	TranslationKey: "tile.waxed_weathered_copper_bars.name",
}

var waxedWeatheredCopperBarsStates = [...]State{
	{Hash: 4150193196, Block: 748, Properties: 423},
}
