// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WaxedCopperTrapdoor is the generated definition for minecraft:waxed_copper_trapdoor.
var WaxedCopperTrapdoor = Block{
	Name:           "minecraft:waxed_copper_trapdoor",
	TranslationKey: "tile.waxed_copper_trapdoor.name",
}

var waxedCopperTrapdoorStates = [...]State{
	{Hash: 3815159696, Block: 303, Properties: 683},
	{Hash: 556296975, Block: 303, Properties: 683},
	{Hash: 2314775458, Block: 303, Properties: 683},
	{Hash: 201624705, Block: 303, Properties: 683},
	{Hash: 575498971, Block: 303, Properties: 684},
	{Hash: 3795957700, Block: 303, Properties: 684},
	{Hash: 3370082029, Block: 303, Properties: 684},
	{Hash: 3441285430, Block: 303, Properties: 684},
	{Hash: 2760865249, Block: 303, Properties: 685},
	{Hash: 3773725390, Block: 303, Properties: 686},
	{Hash: 4155271251, Block: 303, Properties: 687},
	{Hash: 2094011952, Block: 303, Properties: 688},
	{Hash: 1705558678, Block: 303, Properties: 685},
	{Hash: 534064665, Block: 303, Properties: 686},
	{Hash: 3099964680, Block: 303, Properties: 687},
	{Hash: 3149318523, Block: 303, Properties: 688},
}
