// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WaxedWeatheredCopperGrate is the generated definition for minecraft:waxed_weathered_copper_grate.
var WaxedWeatheredCopperGrate = Block{
	Name:           "minecraft:waxed_weathered_copper_grate",
	TranslationKey: "tile.waxed_weathered_copper_grate.name",
}

var waxedWeatheredCopperGrateStates = [...]State{
	{Hash: 3042987050, Block: 475, Properties: 760},
}
