// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WaxedOxidizedCopperGrate is the generated definition for minecraft:waxed_oxidized_copper_grate.
var WaxedOxidizedCopperGrate = Block{
	Name:           "minecraft:waxed_oxidized_copper_grate",
	TranslationKey: "tile.waxed_oxidized_copper_grate.name",
}

var waxedOxidizedCopperGrateStates = [...]State{
	{Hash: 1235641318, Block: 1318, Properties: 1581},
}
