// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WaxedExposedCopperChain is the generated definition for minecraft:waxed_exposed_copper_chain.
var WaxedExposedCopperChain = Block{
	Name:           "minecraft:waxed_exposed_copper_chain",
	TranslationKey: "tile.waxed_exposed_copper_chain.name",
}

var waxedExposedCopperChainStates = [...]State{
	{Hash: 3095863122, Block: 62, Properties: 19},
	{Hash: 4151169693, Block: 62, Properties: 20},
	{Hash: 2040556551, Block: 62, Properties: 21},
}
