// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WeatheredLightningRod is the generated definition for minecraft:weathered_lightning_rod.
var WeatheredLightningRod = Block{
	Name:           "minecraft:weathered_lightning_rod",
	TranslationKey: "tile.weathered_lightning_rod.name",
}

var weatheredLightningRodStates = [...]State{
	{Hash: 4023338217, Block: 629, Properties: 290},
	{Hash: 3060980926, Block: 629, Properties: 290},
	{Hash: 1056572795, Block: 629, Properties: 291},
	{Hash: 173887896, Block: 629, Properties: 291},
	{Hash: 247030381, Block: 629, Properties: 292},
	{Hash: 122970930, Block: 629, Properties: 292},
	{Hash: 2968031646, Block: 629, Properties: 290},
	{Hash: 4116287497, Block: 629, Properties: 290},
	{Hash: 1266224, Block: 629, Properties: 291},
	{Hash: 1229194467, Block: 629, Properties: 291},
	{Hash: 3486691106, Block: 629, Properties: 292},
	{Hash: 1178277501, Block: 629, Properties: 292},
}
