// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WhiteWool is the generated definition for minecraft:white_wool.
var WhiteWool = Block{
	Name:           "minecraft:white_wool",
	TranslationKey: "tile.wool.white.name",
}

var whiteWoolStates = [...]State{
	{Hash: 2425811598, Block: 661, Properties: 1193},
}
