// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WhiteConcrete is the generated definition for minecraft:white_concrete.
var WhiteConcrete = Block{
	Name:           "minecraft:white_concrete",
	TranslationKey: "tile.concrete.white.name",
}

var whiteConcreteStates = [...]State{
	{Hash: 1075364060, Block: 1321, Properties: 1952},
}
