// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WhiteTulip is the generated definition for minecraft:white_tulip.
var WhiteTulip = Block{
	Name:           "minecraft:white_tulip",
	TranslationKey: "tile.red_flower.tulipWhite.name",
}

var whiteTulipStates = [...]State{
	{Hash: 2914537378, Block: 542, Properties: 121},
}
