// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WhiteCarpet is the generated definition for minecraft:white_carpet.
var WhiteCarpet = Block{
	Name:           "minecraft:white_carpet",
	TranslationKey: "tile.carpet.white.name",
}

var whiteCarpetStates = [...]State{
	{Hash: 1460445510, Block: 1062, Properties: 1769},
}
