// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// WitherRose is the generated definition for minecraft:wither_rose.
var WitherRose = Block{
	Name:           "minecraft:wither_rose",
	TranslationKey: "tile.wither_rose.name",
}

var witherRoseStates = [...]State{
	{Hash: 1070281985, Block: 837, Properties: 121},
}
