// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// YellowStainedGlass is the generated definition for minecraft:yellow_stained_glass.
var YellowStainedGlass = Block{
	Name:           "minecraft:yellow_stained_glass",
	TranslationKey: "tile.stained_glass.yellow.name",
}

var yellowStainedGlassStates = [...]State{
	{Hash: 1576194193, Block: 1157, Properties: 1862},
}
