// Code generated by data/cmd/generate; DO NOT EDIT.

package block

// YellowStainedGlassPane is the generated definition for minecraft:yellow_stained_glass_pane.
var YellowStainedGlassPane = Block{
	Name:           "minecraft:yellow_stained_glass_pane",
	TranslationKey: "tile.stained_glass_pane.yellow.name",
}

var yellowStainedGlassPaneStates = [...]State{
	{Hash: 3137619159, Block: 43, Properties: 49},
}
