// Package mininggen turns pinned block tool evidence into provisional catalog facts.
package mininggen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// GeneratedMarker identifies files owned by the mining generator.
const GeneratedMarker = "// Code generated by data/cmd/mininggen; DO NOT EDIT."

const (
	pickaxe = 1 << iota
	axe
	shovel
	hoe
	sword
	shears
)

type harvestFamily struct {
	tool  uint8
	level int8
}

// The item IDs and material labels describe the pinned Prismarine 1.26.30
// extract. They are not claims about the target Bedrock release.
var harvestFamilies = map[int]harvestFamily{
	941: {pickaxe, 0}, 946: {pickaxe, 1}, 951: {pickaxe, 1}, 956: {pickaxe, 0},
	961: {pickaxe, 2}, 966: {pickaxe, 3}, 971: {pickaxe, 4},
	940: {shovel, 0}, 945: {shovel, 1}, 950: {shovel, 1}, 955: {shovel, 0},
	960: {shovel, 2}, 965: {shovel, 3}, 970: {shovel, 4},
	939: {sword, 0}, 944: {sword, 1}, 949: {sword, 1}, 954: {sword, 0},
	959: {sword, 2}, 964: {sword, 3}, 969: {sword, 4},
	1134: {shears, 0},
}

var materialTools = map[string]uint8{
	"mineable/pickaxe":      pickaxe,
	"mineable/axe":          axe,
	"mineable/shovel":       shovel,
	"mineable/hoe":          hoe,
	"leaves":                shears,
	"coweb":                 sword | shears,
	"wool":                  shears,
	"sword_instantly_mines": sword,
}

var unverifiedMaterials = map[string]bool{"plant": true, "vine_or_glow_lichen": true}

type rawBlock struct {
	Name         string          `json:"name"`
	Material     string          `json:"material"`
	HarvestTools map[string]bool `json:"harvestTools"`
}

type miningFact struct {
	name      string
	effective uint8
	harvest   uint8
	level     int8
}

// Generate emits a sorted lookup of known classifications from authenticated
// Prismarine evidence. Blocks with neither effective nor harvest tools are
// intentionally omitted so the runtime lookup reports them as unknown.
func Generate(data []byte, sourceRef, sourceSHA256, sourceLockSHA256 string) ([]byte, int, error) {
	var raw []rawBlock
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, 0, fmt.Errorf("decode mining evidence: %w", err)
	}
	if len(raw) == 0 || sourceRef == "" || sourceSHA256 == "" || sourceLockSHA256 == "" {
		return nil, 0, fmt.Errorf("mining evidence or source identity is incomplete")
	}
	seen := make(map[string]bool, len(raw))
	facts := make([]miningFact, 0, len(raw))
	for _, block := range raw {
		if block.Name == "" || seen[block.Name] {
			return nil, 0, fmt.Errorf("mining evidence has an empty or duplicate name %q", block.Name)
		}
		seen[block.Name] = true
		fact, err := classify(block)
		if err != nil {
			return nil, 0, fmt.Errorf("minecraft:%s: %w", block.Name, err)
		}
		if fact.effective == 0 && fact.harvest == 0 {
			continue
		}
		fact.name = "minecraft:" + block.Name
		facts = append(facts, fact)
	}
	sort.Slice(facts, func(i, j int) bool { return facts[i].name < facts[j].name })
	var output bytes.Buffer
	fmt.Fprintf(&output, `%s

package block

// MiningEvidenceVersion is the Bedrock version of the provisional tool data.
const MiningEvidenceVersion = "1.26.30"

// MiningEvidenceRevision is the pinned Prismarine minecraft-data commit.
const MiningEvidenceRevision = %q

// MiningEvidenceSHA256 authenticates the source blocks.json file.
const MiningEvidenceSHA256 = %q

// MiningSourceLockSHA256 identifies the complete input lock used to generate this table.
const MiningSourceLockSHA256 = %q

var miningRows = [...]miningRow{
`, GeneratedMarker, sourceRef, sourceSHA256, sourceLockSHA256)
	for _, fact := range facts {
		fmt.Fprintf(&output, "{Name: %q, Facts: MiningFacts{EffectiveTools: %s, HarvestTools: %s, HarvestLevel: %d}},\n", fact.name, toolExpression(fact.effective), toolExpression(fact.harvest), fact.level)
	}
	output.WriteString("}\n")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, 0, fmt.Errorf("format mining catalog: %w", err)
	}
	return formatted, len(facts), nil
}

// toolExpression renders a family set with named constants for reviewable output.
func toolExpression(families uint8) string {
	var names []string
	for _, tool := range []struct {
		mask uint8
		name string
	}{
		{pickaxe, "ToolPickaxe"}, {axe, "ToolAxe"}, {shovel, "ToolShovel"},
		{hoe, "ToolHoe"}, {sword, "ToolSword"}, {shears, "ToolShears"},
	} {
		if families&tool.mask != 0 {
			names = append(names, tool.name)
		}
	}
	if len(names) == 0 {
		return "0"
	}
	return strings.Join(names, " | ")
}

// classify preserves the source's separate effectiveness and drop-tool signals.
func classify(block rawBlock) (miningFact, error) {
	fact := miningFact{level: -1}
	parts := strings.Split(block.Material, ";")
	for _, part := range parts {
		if unverifiedMaterials[part] {
			parts = nil
			break
		}
	}
	for _, part := range parts {
		fact.effective |= materialTools[part]
	}
	for id := range block.HarvestTools {
		number, err := strconv.Atoi(id)
		if err != nil {
			return miningFact{}, fmt.Errorf("harvest tool ID %q: %w", id, err)
		}
		family, ok := harvestFamilies[number]
		if !ok {
			return miningFact{}, fmt.Errorf("unclassified harvest tool ID %d", number)
		}
		fact.harvest |= family.tool
		fact.effective |= family.tool
		if fact.level < 0 || family.level < fact.level {
			fact.level = family.level
		}
	}
	return fact, nil
}
