// Code generated by data/cmd/generate; DO NOT EDIT.

package data

const (
	SchemaVersion  = 1
	CloudburstRef  = "fb969c547236d87a17181941cd585a0eb18f7ceb"
	BDSVersion     = "1.26.32.2"
	BlockShapesRef = "59d4007e322a0acf2b0add59133c81e1f7e4c501"
)

var GeneratedCounts = Counts{
	BlockStates: 16913,
	Biomes:      88,
	VoxelShapes: 57,
	Entities:    96,
	Foods:       38,
}
