//! Shared helpers for formatting and writing generated Rust modules.

use proc_macro2::TokenStream;
use quote::quote;
use std::fs::File;
use std::io::Write;
use std::path::Path;

const GENERATED_HEADER: &str = "// Generated by valentine_gen. Do not edit.\n\n";

fn format_tokens(
    tokens: TokenStream,
    debug_name: Option<&str>,
) -> Result<String, Box<dyn std::error::Error>> {
    let syntax_tree = syn::parse2(tokens.clone()).map_err(|err| {
        if let Some(path) = debug_name {
            let _ = std::fs::write(path, tokens.to_string());
        }
        format!("Failed to parse generated code: {err}")
    })?;

    Ok(prettyplease::unparse(&syntax_tree))
}

pub fn write_rust_file(
    path: &Path,
    tokens: TokenStream,
    debug_name: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut file = File::create(path)?;
    let formatted = format_tokens(tokens, debug_name)?;
    write!(file, "{GENERATED_HEADER}")?;
    write!(file, "{formatted}")?;
    Ok(())
}

pub fn generated_module_tokens(
    doc: Option<&str>,
    imports: TokenStream,
    items: &[TokenStream],
) -> TokenStream {
    let doc_tokens = doc.map(|text| quote! { #![doc = #text] });

    quote! {
        #doc_tokens
        #![allow(non_camel_case_types)]
        #![allow(non_snake_case)]
        #![allow(dead_code)]
        #![allow(unused_parens)]
        #![allow(clippy::all)]
        #imports

        #(#items)*
    }
}
