// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// BellAttachmentFloor is the generated definition for minecraft:bell_attachment_floor.
var BellAttachmentFloor = Shape{
	Name: "minecraft:bell_attachment_floor",
	Boxes: []Box{
		{0, 0, 0.25, 1, 1, 0.75},
	},
}
