// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// CakeBites0 is the generated definition for minecraft:cake_bites_0.
var CakeBites0 = Shape{
	Name: "minecraft:cake_bites_0",
	Boxes: []Box{
		{0.0625, 0, 0.0625, 0.9375, 0.5, 0.9375},
	},
}
