// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// CakeBites1 is the generated definition for minecraft:cake_bites_1.
var CakeBites1 = Shape{
	Name: "minecraft:cake_bites_1",
	Boxes: []Box{
		{0.1875, 0, 0.0625, 0.9375, 0.5, 0.9375},
	},
}
