// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// CandleCake is the generated definition for minecraft:candle_cake.
var CandleCake = Shape{
	Name: "minecraft:candle_cake",
	Boxes: []Box{
		{0.0625, 0, 0.0625, 0.9375, 0.5, 0.9375},
		{0.4375, 0.5, 0.4375, 0.5625, 0.875, 0.5625},
	},
}
