// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// FenceGateInWallOcclusion is the generated definition for minecraft:fence_gate_in_wall_occlusion.
var FenceGateInWallOcclusion = Shape{
	Name: "minecraft:fence_gate_in_wall_occlusion",
	Boxes: []Box{
		{0, 0.125, 0.4375, 0.125, 0.8125, 0.5625},
		{0.875, 0.125, 0.4375, 1, 0.8125, 0.5625},
	},
}
