// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// Fence is the generated definition for minecraft:fence.
var Fence = Shape{
	Name: "minecraft:fence",
	Boxes: []Box{
		{0.375, 0, 0.375, 0.625, 1, 0.625},
	},
}
