// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// Grindstone is the generated definition for minecraft:grindstone.
var Grindstone = Shape{
	Name: "minecraft:grindstone",
	Boxes: []Box{
		{0.125, 0, 0.375, 0.25, 0.8125, 0.625},
		{0.75, 0, 0.375, 0.875, 0.8125, 0.625},
		{0.25, 0.25, 0.125, 0.75, 1, 0.875},
		{0.125, 0.4375, 0.3125, 0.25, 0.8125, 0.375},
		{0.125, 0.4375, 0.625, 0.25, 0.8125, 0.6875},
		{0.75, 0.4375, 0.3125, 0.875, 0.8125, 0.375},
		{0.75, 0.4375, 0.625, 0.875, 0.8125, 0.6875},
	},
}
