// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// PiglinWallHeadFacingNorth is the generated definition for minecraft:piglin_wall_head_facing_north.
var PiglinWallHeadFacingNorth = Shape{
	Name: "minecraft:piglin_wall_head_facing_north",
	Boxes: []Box{
		{0.1875, 0.25, 0.5, 0.8125, 0.75, 1},
	},
}
