// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// PiglinWallHeadFacingSouth is the generated definition for minecraft:piglin_wall_head_facing_south.
var PiglinWallHeadFacingSouth = Shape{
	Name: "minecraft:piglin_wall_head_facing_south",
	Boxes: []Box{
		{0.1875, 0.25, 0, 0.8125, 0.75, 0.5},
	},
}
