// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// ShelfFacingSouth is the generated definition for minecraft:shelf_facing_south.
var ShelfFacingSouth = Shape{
	Name: "minecraft:shelf_facing_south",
	Boxes: []Box{
		{0, 0, 0, 1, 0.25, 0.3125},
		{0, 0.25, 0, 1, 1, 0.1875},
		{0, 0.75, 0.1875, 1, 1, 0.3125},
	},
}
