// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// WallHeadFacingNorth is the generated definition for minecraft:wall_head_facing_north.
var WallHeadFacingNorth = Shape{
	Name: "minecraft:wall_head_facing_north",
	Boxes: []Box{
		{0.25, 0.25, 0.5, 0.75, 0.75, 1},
	},
}
