// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// WallHeadFacingWest is the generated definition for minecraft:wall_head_facing_west.
var WallHeadFacingWest = Shape{
	Name: "minecraft:wall_head_facing_west",
	Boxes: []Box{
		{0.5, 0.25, 0.25, 1, 0.75, 0.75},
	},
}
