// Code generated by data/cmd/generate; DO NOT EDIT.

package voxelshape

// WallHeadFacingSouth is the generated definition for minecraft:wall_head_facing_south.
var WallHeadFacingSouth = Shape{
	Name: "minecraft:wall_head_facing_south",
	Boxes: []Box{
		{0.25, 0.25, 0, 0.75, 0.75, 0.5},
	},
}
