// Code generated by data/cmd/generate; DO NOT EDIT.

package biome

// ColdTaiga is the generated definition for minecraft:cold_taiga.
var ColdTaiga = Biome{
	Name:              "minecraft:cold_taiga",
	ID:                0,
	HasID:             false,
	Temperature:       -0.5,
	Downfall:          0.4,
	Depth:             0.2,
	Scale:             0.2,
	RedSporeDensity:   0,
	BlueSporeDensity:  0,
	AshDensity:        0,
	WhiteAshDensity:   0,
	FoliageSnow:       0,
	MapWaterColorRGBA: 0x205e83a5,
	Rain:              true,
	Tags:              []string{"animal", "cold", "forest", "has_structure_trail_ruins", "monster", "overworld", "spawns_cold_variant_farm_animals", "taiga"},
}
