// Code generated by data/cmd/generate; DO NOT EDIT.

package biome

// CrimsonForest is the generated definition for minecraft:crimson_forest.
var CrimsonForest = Biome{
	Name:              "minecraft:crimson_forest",
	ID:                0,
	HasID:             false,
	Temperature:       2,
	Downfall:          0,
	Depth:             0.1,
	Scale:             0.2,
	RedSporeDensity:   0,
	BlueSporeDensity:  0,
	AshDensity:        0,
	WhiteAshDensity:   0,
	FoliageSnow:       0,
	MapWaterColorRGBA: 0x905957a5,
	Rain:              false,
	Tags:              []string{"crimson_forest", "nether", "netherwart_forest", "spawn_few_zombified_piglins", "spawn_piglin", "spawns_warm_variant_farm_animals"},
}
