// Code generated by data/cmd/generate; DO NOT EDIT.

package biome

// FrozenRiver is the generated definition for minecraft:frozen_river.
var FrozenRiver = Biome{
	Name:              "minecraft:frozen_river",
	ID:                0,
	HasID:             false,
	Temperature:       0,
	Downfall:          0.5,
	Depth:             -0.5,
	Scale:             0,
	RedSporeDensity:   0,
	BlueSporeDensity:  0,
	AshDensity:        0,
	WhiteAshDensity:   0,
	FoliageSnow:       0,
	MapWaterColorRGBA: 0x185390a5,
	Rain:              true,
	Tags:              []string{"frozen", "overworld", "river", "spawns_cold_variant_farm_animals", "spawns_cold_variant_frogs", "spawns_river_mobs", "spawns_snow_foxes", "spawns_white_rabbits"},
}
