// Code generated by data/cmd/generate; DO NOT EDIT.

package biome

// IcePlainsSpikes is the generated definition for minecraft:ice_plains_spikes.
var IcePlainsSpikes = Biome{
	Name:              "minecraft:ice_plains_spikes",
	ID:                0,
	HasID:             false,
	Temperature:       0,
	Downfall:          1,
	Depth:             0.425,
	Scale:             0.45,
	RedSporeDensity:   0,
	BlueSporeDensity:  0,
	AshDensity:        0,
	WhiteAshDensity:   0,
	FoliageSnow:       0,
	MapWaterColorRGBA: 0x60b7ffa6,
	Rain:              true,
	Tags:              []string{"frozen", "ice_plains", "monster", "mutated", "overworld", "spawns_cold_variant_farm_animals", "spawns_cold_variant_frogs", "spawns_white_rabbits"},
}
