// Code generated by data/cmd/generate; DO NOT EDIT.

package biome

// JaggedPeaks is the generated definition for minecraft:jagged_peaks.
var JaggedPeaks = Biome{
	Name:              "minecraft:jagged_peaks",
	ID:                0,
	HasID:             false,
	Temperature:       -0.7,
	Downfall:          0.9,
	Depth:             0.1,
	Scale:             0.2,
	RedSporeDensity:   0,
	BlueSporeDensity:  0,
	AshDensity:        0,
	WhiteAshDensity:   0,
	FoliageSnow:       0,
	MapWaterColorRGBA: 0x60b7ffa6,
	Rain:              true,
	Tags:              []string{"frozen", "jagged_peaks", "monster", "mountains", "overworld", "spawns_cold_variant_farm_animals", "spawns_cold_variant_frogs", "spawns_snow_foxes", "spawns_white_rabbits"},
}
