// Code generated by data/cmd/generate; DO NOT EDIT.

package biome

// JungleMutated is the generated definition for minecraft:jungle_mutated.
var JungleMutated = Biome{
	Name:              "minecraft:jungle_mutated",
	ID:                0,
	HasID:             false,
	Temperature:       0.95,
	Downfall:          0.9,
	Depth:             0.2,
	Scale:             0.4,
	RedSporeDensity:   0,
	BlueSporeDensity:  0,
	AshDensity:        0,
	WhiteAshDensity:   0,
	FoliageSnow:       0,
	MapWaterColorRGBA: 0x1b9ed8a5,
	Rain:              true,
	Tags:              []string{"animal", "jungle", "monster", "mutated", "overworld_generation", "spawns_warm_variant_farm_animals"},
}
