// Code generated by data/cmd/generate; DO NOT EDIT.

package biome

// MushroomIslandShore is the generated definition for minecraft:mushroom_island_shore.
var MushroomIslandShore = Biome{
	Name:              "minecraft:mushroom_island_shore",
	ID:                0,
	HasID:             false,
	Temperature:       0.9,
	Downfall:          1,
	Depth:             0,
	Scale:             0.025,
	RedSporeDensity:   0,
	BlueSporeDensity:  0,
	AshDensity:        0,
	WhiteAshDensity:   0,
	FoliageSnow:       0,
	MapWaterColorRGBA: 0x818193a5,
	Rain:              true,
	Tags:              []string{"mooshroom_island", "overworld", "shore", "spawns_without_patrols"},
}
