// Code generated by data/cmd/generate; DO NOT EDIT.

package biome

// Plains is the generated definition for minecraft:plains.
var Plains = Biome{
	Name:              "minecraft:plains",
	ID:                0,
	HasID:             false,
	Temperature:       0.8,
	Downfall:          0.4,
	Depth:             0.125,
	Scale:             0.05,
	RedSporeDensity:   0,
	BlueSporeDensity:  0,
	AshDensity:        0,
	WhiteAshDensity:   0,
	FoliageSnow:       0,
	MapWaterColorRGBA: 0x44aff5a5,
	Rain:              true,
	Tags:              []string{"animal", "bee_habitat", "monster", "overworld", "plains"},
}
