// Code generated by data/cmd/generate; DO NOT EDIT.

package biome

// StoneBeach is the generated definition for minecraft:stone_beach.
var StoneBeach = Biome{
	Name:              "minecraft:stone_beach",
	ID:                0,
	HasID:             false,
	Temperature:       0.2,
	Downfall:          0.3,
	Depth:             0.1,
	Scale:             0.8,
	RedSporeDensity:   0,
	BlueSporeDensity:  0,
	AshDensity:        0,
	WhiteAshDensity:   0,
	FoliageSnow:       0,
	MapWaterColorRGBA: 0x0d67bba5,
	Rain:              true,
	Tags:              []string{"beach", "monster", "overworld", "stone"},
}
