// Code generated by data/cmd/generate; DO NOT EDIT.

package biome

// SulfurCaves is the generated definition for minecraft:sulfur_caves.
var SulfurCaves = Biome{
	Name:              "minecraft:sulfur_caves",
	ID:                0,
	HasID:             false,
	Temperature:       0.8,
	Downfall:          0.4,
	Depth:             0.1,
	Scale:             0.2,
	RedSporeDensity:   0,
	BlueSporeDensity:  0,
	AshDensity:        0,
	WhiteAshDensity:   0,
	FoliageSnow:       0,
	MapWaterColorRGBA: 0x60b7ffa6,
	Rain:              true,
	Tags:              []string{"caves", "monster", "overworld", "sulfur_caves"},
}
